INSERT INTO Invoice(creation_date, order_number, total_price, note, id_supplier) VALUES("2002-08-05", "303", 469, "In the screen, no grass on the sunny", 3);
INSERT INTO Invoice(creation_date, order_number, total_price, note, id_supplier) VALUES("1997-01-08", "666", 242, "Santa monica freeway you on that jack", 4);
INSERT INTO Invoice(creation_date, order_number, total_price, note, id_supplier) VALUES("2007-09-05", "1001", 168, "Coke fallin' in love the night oh lea", 2);
INSERT INTO Invoice(creation_date, order_number, total_price, note, id_supplier) VALUES("2001-01-05", "456", 134, "Ann my sweet baby that we're through refusing", 1);
INSERT INTO Invoice(creation_date, order_number, total_price, note, id_supplier) VALUES("1950-12-12", "789", 79, "A little kindness with pen in hand", 5);
INSERT INTO Invoice(creation_date, order_number, total_price, note, id_supplier) VALUES("1989-10-30", "1423", 244, "To buy you a song a little turtle", 7);
INSERT INTO Invoice(creation_date, order_number, total_price, note, id_supplier) VALUES("2012-12-20", "123456", 113, "Dovin' on a talkin' and I'll meet", 6);
INSERT INTO Invoice(creation_date, order_number, total_price, note, id_supplier) VALUES("2010-05-09", "1245", 47, "Here today not some brand", 3);
INSERT INTO Invoice(creation_date, order_number, total_price, note, id_supplier) VALUES("2018-11-30", "3265", 93, "Amazing prices", 5);
INSERT INTO Invoice(creation_date, order_number, total_price, note, id_supplier) VALUES("2020-01-15", "52", 15, "Clear as day come on light", 7);
