INSERT INTO Variety(name) VALUES("Abouriou");
INSERT INTO Variety(name) VALUES("Abrustine");
INSERT INTO Variety(name) VALUES("Absinthe");
INSERT INTO Variety(name) VALUES("Acadie Blanc");
INSERT INTO Variety(name) VALUES("Acolon");
INSERT INTO Variety(name) VALUES("Agave Spirit");
INSERT INTO Variety(name) VALUES("Agiorgitiko");
INSERT INTO Variety(name) VALUES("Aglianico");
INSERT INTO Variety(name) VALUES("Aglianico - Piedirosso");
INSERT INTO Variety(name) VALUES("Ahmeur bou Ahmeur");
INSERT INTO Variety(name) VALUES("Aidani");
INSERT INTO Variety(name) VALUES("Airen");
INSERT INTO Variety(name) VALUES("Aladasturi");
INSERT INTO Variety(name) VALUES("Alarijen");
INSERT INTO Variety(name) VALUES("Albalonga");
INSERT INTO Variety(name) VALUES("Albana");
INSERT INTO Variety(name) VALUES("Albanella");
INSERT INTO Variety(name) VALUES("Albarello Blanca");
INSERT INTO Variety(name) VALUES("Albarin Blanco");
INSERT INTO Variety(name) VALUES("Albarino (Alvarinho)");
INSERT INTO Variety(name) VALUES("Albarola");
INSERT INTO Variety(name) VALUES("Albarola - Bosco - Vermentino");
INSERT INTO Variety(name) VALUES("Albarossa");
INSERT INTO Variety(name) VALUES("Albillo");
INSERT INTO Variety(name) VALUES("Albillo Krimskii (Rachuli Tetra)");
INSERT INTO Variety(name) VALUES("Alcohol-Free");
INSERT INTO Variety(name) VALUES("Aleatico");
INSERT INTO Variety(name) VALUES("Alexandrouli");
INSERT INTO Variety(name) VALUES("Alfrocheiro Preto");
INSERT INTO Variety(name) VALUES("Alfrocheiro Preto - Tinta Roriz - Touriga");
INSERT INTO Variety(name) VALUES("Alfrocheiro Preto - Touriga");
INSERT INTO Variety(name) VALUES("Alibernet");
INSERT INTO Variety(name) VALUES("Alicante Bouschet");
INSERT INTO Variety(name) VALUES("Alicante Bouschet - Aragonez");
INSERT INTO Variety(name) VALUES("Alicante Bouschet - Aragonez - Trincadeira");
INSERT INTO Variety(name) VALUES("Alicante Bouschet - Touriga");
INSERT INTO Variety(name) VALUES("Alicante Ganzin");
INSERT INTO Variety(name) VALUES("Aligote");
INSERT INTO Variety(name) VALUES("Alphonse Lavallee");
INSERT INTO Variety(name) VALUES("Altesse");
INSERT INTO Variety(name) VALUES("Alvarelhao");
INSERT INTO Variety(name) VALUES("Amigne");
INSERT INTO Variety(name) VALUES("Ancellotta");
INSERT INTO Variety(name) VALUES("Andre");
INSERT INTO Variety(name) VALUES("Antao Vaz");
INSERT INTO Variety(name) VALUES("Antao Vaz - Arinto (Pederna)");
INSERT INTO Variety(name) VALUES("Aragonez (Tinta Roriz) - Castelao");
INSERT INTO Variety(name) VALUES("Aramon");
INSERT INTO Variety(name) VALUES("Aranel");
INSERT INTO Variety(name) VALUES("Arany Sarfeher");
INSERT INTO Variety(name) VALUES("Arbane");
INSERT INTO Variety(name) VALUES("Arbois");
INSERT INTO Variety(name) VALUES("Areni Noir");
INSERT INTO Variety(name) VALUES("Argaman");
INSERT INTO Variety(name) VALUES("Argant");
INSERT INTO Variety(name) VALUES("Arinarnoa");
INSERT INTO Variety(name) VALUES("Arinto (Pederna)");
INSERT INTO Variety(name) VALUES("Arinto (Pederna) - Fernao Pires");
INSERT INTO Variety(name) VALUES("Arinto (Pederna) - Loureiro");
INSERT INTO Variety(name) VALUES("Arneis");
INSERT INTO Variety(name) VALUES("Arriloba");
INSERT INTO Variety(name) VALUES("Arrufiac");
INSERT INTO Variety(name) VALUES("Aspiran");
INSERT INTO Variety(name) VALUES("Assyrtiko");
INSERT INTO Variety(name) VALUES("Athiri");
INSERT INTO Variety(name) VALUES("Aubin Vert");
INSERT INTO Variety(name) VALUES("Aubun");
INSERT INTO Variety(name) VALUES("Aurore");
INSERT INTO Variety(name) VALUES("Auxerrois");
INSERT INTO Variety(name) VALUES("Avana");
INSERT INTO Variety(name) VALUES("Avarengo");
INSERT INTO Variety(name) VALUES("Avesso");
INSERT INTO Variety(name) VALUES("Avgoustiatis");
INSERT INTO Variety(name) VALUES("Awamori");
INSERT INTO Variety(name) VALUES("Azal Branco");
INSERT INTO Variety(name) VALUES("Azal Tinto");
INSERT INTO Variety(name) VALUES("Babeasca Neagra");
INSERT INTO Variety(name) VALUES("Babic");
INSERT INTO Variety(name) VALUES("Bacchus");
INSERT INTO Variety(name) VALUES("Bachet");
INSERT INTO Variety(name) VALUES("Baco Blanc");
INSERT INTO Variety(name) VALUES("Baco Noir");
INSERT INTO Variety(name) VALUES("Baga");
INSERT INTO Variety(name) VALUES("Baijiu");
INSERT INTO Variety(name) VALUES("Baltica");
INSERT INTO Variety(name) VALUES("Barbarossa");
INSERT INTO Variety(name) VALUES("Barbera");
INSERT INTO Variety(name) VALUES("Barbera - Bonarda (Croatina)");
INSERT INTO Variety(name) VALUES("Barbera - Dolcetto - Nebbiolo");
INSERT INTO Variety(name) VALUES("Barbera - Nebbiolo");
INSERT INTO Variety(name) VALUES("Barbera - Sangiovese");
INSERT INTO Variety(name) VALUES("Baroque");
INSERT INTO Variety(name) VALUES("Barsaglina");
INSERT INTO Variety(name) VALUES("Batiki");
INSERT INTO Variety(name) VALUES("Beaunoir");
INSERT INTO Variety(name) VALUES("Beer");
INSERT INTO Variety(name) VALUES("Bellone Bianco");
INSERT INTO Variety(name) VALUES("Bequignol");
INSERT INTO Variety(name) VALUES("Bervedino");
INSERT INTO Variety(name) VALUES("Bianchello (Biancame)");
INSERT INTO Variety(name) VALUES("Bianchetta Genovese");
INSERT INTO Variety(name) VALUES("Bianco d'Alessano");
INSERT INTO Variety(name) VALUES("Bianco d'Alessano - Verdeca");
INSERT INTO Variety(name) VALUES("Biancolella");
INSERT INTO Variety(name) VALUES("Biancone");
INSERT INTO Variety(name) VALUES("Biancu Gentile");
INSERT INTO Variety(name) VALUES("Bical");
INSERT INTO Variety(name) VALUES("Bigolona");
INSERT INTO Variety(name) VALUES("Bitters");
INSERT INTO Variety(name) VALUES("Black Monukka");
INSERT INTO Variety(name) VALUES("Black Spanish (Lenoir)");
INSERT INTO Variety(name) VALUES("Blanc du Bois");
INSERT INTO Variety(name) VALUES("Blanqueiron");
INSERT INTO Variety(name) VALUES("Blatina");
INSERT INTO Variety(name) VALUES("Blauburger");
INSERT INTO Variety(name) VALUES("Blauer Wildbacher");
INSERT INTO Variety(name) VALUES("Blaufrankisch - Cabernet");
INSERT INTO Variety(name) VALUES("Blaufrankisch - Cabernet - Merlot");
INSERT INTO Variety(name) VALUES("Blaufrankisch (Lemberger)");
INSERT INTO Variety(name) VALUES("Blaufrankisch - Zweigelt");
INSERT INTO Variety(name) VALUES("Bobal");
INSERT INTO Variety(name) VALUES("Bobal Blanco");
INSERT INTO Variety(name) VALUES("Bogazkere");
INSERT INTO Variety(name) VALUES("Bogazkere - Okuzgozu");
INSERT INTO Variety(name) VALUES("Bogdanusa");
INSERT INTO Variety(name) VALUES("Bombino Bianco");
INSERT INTO Variety(name) VALUES("Bombino Nero");
INSERT INTO Variety(name) VALUES("Bonarda - Malbec");
INSERT INTO Variety(name) VALUES("Bonarda Piemontese");
INSERT INTO Variety(name) VALUES("Bondola");
INSERT INTO Variety(name) VALUES("Bordeaux Blend Red");
INSERT INTO Variety(name) VALUES("Bordeaux Blend White");
INSERT INTO Variety(name) VALUES("Bosco");
INSERT INTO Variety(name) VALUES("Bourboulenc");
INSERT INTO Variety(name) VALUES("Bouvier");
INSERT INTO Variety(name) VALUES("Brachetto");
INSERT INTO Variety(name) VALUES("Brandy");
INSERT INTO Variety(name) VALUES("Braquet");
INSERT INTO Variety(name) VALUES("Brauner Veltliner");
INSERT INTO Variety(name) VALUES("Brianna");
INSERT INTO Variety(name) VALUES("Bronner");
INSERT INTO Variety(name) VALUES("Bronx");
INSERT INTO Variety(name) VALUES("Brunal");
INSERT INTO Variety(name) VALUES("Brun Fourca");
INSERT INTO Variety(name) VALUES("Bual (Malvasia Fina)");
INSERT INTO Variety(name) VALUES("Bukettraube");
INSERT INTO Variety(name) VALUES("Burger");
INSERT INTO Variety(name) VALUES("Cabernet Blanc");
INSERT INTO Variety(name) VALUES("Cabernet - Carignan - Grenache");
INSERT INTO Variety(name) VALUES("Cabernet - Carignan - Syrah");
INSERT INTO Variety(name) VALUES("Cabernet Cubin");
INSERT INTO Variety(name) VALUES("Cabernet Dorio");
INSERT INTO Variety(name) VALUES("Cabernet Dorsa");
INSERT INTO Variety(name) VALUES("Cabernet Franc");
INSERT INTO Variety(name) VALUES("Cabernet Franc - Cabernet Sauvignon");
INSERT INTO Variety(name) VALUES("Cabernet Franc - Gamay");
INSERT INTO Variety(name) VALUES("Cabernet Franc - Malbec");
INSERT INTO Variety(name) VALUES("Cabernet Franc - Merlot");
INSERT INTO Variety(name) VALUES("Cabernet Franc - Pinot Noir");
INSERT INTO Variety(name) VALUES("Cabernet Gernischt");
INSERT INTO Variety(name) VALUES("Cabernet - Grenache - Merlot - Syrah");
INSERT INTO Variety(name) VALUES("Cabernet - Grenache - Mourvedre - Syrah");
INSERT INTO Variety(name) VALUES("Cabernet - Grenache - Syrah");
INSERT INTO Variety(name) VALUES("Cabernet Jura");
INSERT INTO Variety(name) VALUES("Cabernet - Malbec - Syrah");
INSERT INTO Variety(name) VALUES("Cabernet - Merlot - Montepulciano");
INSERT INTO Variety(name) VALUES("Cabernet - Merlot - Sangiovese");
INSERT INTO Variety(name) VALUES("Cabernet - Merlot - Syrah");
INSERT INTO Variety(name) VALUES("Cabernet - Merlot - Tempranillo");
INSERT INTO Variety(name) VALUES("Cabernet - Merlot - Zinfandel");
INSERT INTO Variety(name) VALUES("Cabernet - Merlot - Zweigelt");
INSERT INTO Variety(name) VALUES("Cabernet Mitos");
INSERT INTO Variety(name) VALUES("Cabernet - Montepulciano");
INSERT INTO Variety(name) VALUES("Cabernet Moravia");
INSERT INTO Variety(name) VALUES("Cabernet - Mourvedre - Syrah");
INSERT INTO Variety(name) VALUES("Cabernet - Nero d'Avola");
INSERT INTO Variety(name) VALUES("Cabernet - Petit Verdot");
INSERT INTO Variety(name) VALUES("Cabernet Pfeffer");
INSERT INTO Variety(name) VALUES("Cabernet - Pinotage");
INSERT INTO Variety(name) VALUES("Cabernet - Sangiovese");
INSERT INTO Variety(name) VALUES("Cabernet - Sangiovese - Syrah");
INSERT INTO Variety(name) VALUES("Cabernet Sauvignon");
INSERT INTO Variety(name) VALUES("Cabernet Sauvignon - Carignan");
INSERT INTO Variety(name) VALUES("Cabernet Sauvignon - Carmenere");
INSERT INTO Variety(name) VALUES("Cabernet Sauvignon - Cinsaut");
INSERT INTO Variety(name) VALUES("Cabernet Sauvignon - Malbec");
INSERT INTO Variety(name) VALUES("Cabernet Sauvignon - Merlot");
INSERT INTO Variety(name) VALUES("Cabernet Sauvignon - Pinot Noir");
INSERT INTO Variety(name) VALUES("Cabernets - Grolleau");
INSERT INTO Variety(name) VALUES("Cabernet - Syrah/Shiraz");
INSERT INTO Variety(name) VALUES("Cabernet - Syrah - Tempranillo");
INSERT INTO Variety(name) VALUES("Cabernet - Syrah - Zinfandel");
INSERT INTO Variety(name) VALUES("Cabernet - Tannat");
INSERT INTO Variety(name) VALUES("Cabernet - Tempranillo");
INSERT INTO Variety(name) VALUES("Cabernet - Zinfandel");
INSERT INTO Variety(name) VALUES("Cab Franc - Gamay - Malbec");
INSERT INTO Variety(name) VALUES("Cachaca");
INSERT INTO Variety(name) VALUES("Cagnulari");
INSERT INTO Variety(name) VALUES("Caino Tinto");
INSERT INTO Variety(name) VALUES("Caladoc");
INSERT INTO Variety(name) VALUES("Calbanesco");
INSERT INTO Variety(name) VALUES("Calitor");
INSERT INTO Variety(name) VALUES("Cal Karasi");
INSERT INTO Variety(name) VALUES("Callet");
INSERT INTO Variety(name) VALUES("Calzin");
INSERT INTO Variety(name) VALUES("Camaralet de Lasseube");
INSERT INTO Variety(name) VALUES("Camarate");
INSERT INTO Variety(name) VALUES("Canaiolo");
INSERT INTO Variety(name) VALUES("Canaiolo Bianco");
INSERT INTO Variety(name) VALUES("Cannabis Drink");
INSERT INTO Variety(name) VALUES("Canocazo");
INSERT INTO Variety(name) VALUES("Carcajolo Blanc");
INSERT INTO Variety(name) VALUES("Carcajolo Nero");
INSERT INTO Variety(name) VALUES("Caricalasino");
INSERT INTO Variety(name) VALUES("Carignan Blanc");
INSERT INTO Variety(name) VALUES("Carignan (Carinena)");
INSERT INTO Variety(name) VALUES("Carignan - Grenache - Syrah");
INSERT INTO Variety(name) VALUES("Carignan - Grenache - Tempranillo");
INSERT INTO Variety(name) VALUES("Carignan Gris");
INSERT INTO Variety(name) VALUES("Carignan - Merlot");
INSERT INTO Variety(name) VALUES("Carignan - Syrah");
INSERT INTO Variety(name) VALUES("Carinena - Garnacha");
INSERT INTO Variety(name) VALUES("Carmenere");
INSERT INTO Variety(name) VALUES("Carmenere - Syrah");
INSERT INTO Variety(name) VALUES("Carmine");
INSERT INTO Variety(name) VALUES("Carminoir");
INSERT INTO Variety(name) VALUES("Carnelian");
INSERT INTO Variety(name) VALUES("Carrasquin");
INSERT INTO Variety(name) VALUES("Carricante");
INSERT INTO Variety(name) VALUES("Carricante - Catarratto");
INSERT INTO Variety(name) VALUES("Casavecchia");
INSERT INTO Variety(name) VALUES("Casetta");
INSERT INTO Variety(name) VALUES("Cassady");
INSERT INTO Variety(name) VALUES("Castelao");
INSERT INTO Variety(name) VALUES("Castelao - Touriga");
INSERT INTO Variety(name) VALUES("Catarratto");
INSERT INTO Variety(name) VALUES("Catarratto - Chardonnay");
INSERT INTO Variety(name) VALUES("Catarratto - Grillo - Inzolia");
INSERT INTO Variety(name) VALUES("Catarratto - Inzolia");
INSERT INTO Variety(name) VALUES("Catawba");
INSERT INTO Variety(name) VALUES("Cava Blend");
INSERT INTO Variety(name) VALUES("Cayetana");
INSERT INTO Variety(name) VALUES("Cayuga");
INSERT INTO Variety(name) VALUES("Cecubo");
INSERT INTO Variety(name) VALUES("Centesimino (Savignon Rosso)");
INSERT INTO Variety(name) VALUES("Centurion");
INSERT INTO Variety(name) VALUES("Cerceal");
INSERT INTO Variety(name) VALUES("Cereza");
INSERT INTO Variety(name) VALUES("Cesanese");
INSERT INTO Variety(name) VALUES("Cesar");
INSERT INTO Variety(name) VALUES("Cetinka");
INSERT INTO Variety(name) VALUES("Chambourcin");
INSERT INTO Variety(name) VALUES("Champagne Blend");
INSERT INTO Variety(name) VALUES("Chancellor");
INSERT INTO Variety(name) VALUES("Charbono (Bonarda)");
INSERT INTO Variety(name) VALUES("Chardonel");
INSERT INTO Variety(name) VALUES("Chardonnay");
INSERT INTO Variety(name) VALUES("Chardonnay - Chenin Blanc");
INSERT INTO Variety(name) VALUES("Chardonnay - Colombard");
INSERT INTO Variety(name) VALUES("Chardonnay - Garganega");
INSERT INTO Variety(name) VALUES("Chardonnay - Gewurztraminer");
INSERT INTO Variety(name) VALUES("Chardonnay - Muscat");
INSERT INTO Variety(name) VALUES("Chardonnay Musque");
INSERT INTO Variety(name) VALUES("Chardonnay - Pinot Blanc");
INSERT INTO Variety(name) VALUES("Chardonnay - Pinot Blanc - Pinot Noir");
INSERT INTO Variety(name) VALUES("Chardonnay - Pinot Gris");
INSERT INTO Variety(name) VALUES("Chardonnay - Pinot Noir");
INSERT INTO Variety(name) VALUES("Chardonnay - Riesling");
INSERT INTO Variety(name) VALUES("Chardonnay Rose");
INSERT INTO Variety(name) VALUES("Chardonnay - Roussanne");
INSERT INTO Variety(name) VALUES("Chardonnay - Roussanne - Viognier");
INSERT INTO Variety(name) VALUES("Chardonnay - Sauvignon Blanc");
INSERT INTO Variety(name) VALUES("Chardonnay - Sauvignon - Semillon");
INSERT INTO Variety(name) VALUES("Chardonnay - Savagnin");
INSERT INTO Variety(name) VALUES("Chardonnay - Semillon");
INSERT INTO Variety(name) VALUES("Chardonnay - Torrontes");
INSERT INTO Variety(name) VALUES("Chardonnay - Verdelho");
INSERT INTO Variety(name) VALUES("Chardonnay - Vermentino");
INSERT INTO Variety(name) VALUES("Chardonnay - Viognier");
INSERT INTO Variety(name) VALUES("Chardonnay - Viura");
INSERT INTO Variety(name) VALUES("Chardonnay - Xarel-lo");
INSERT INTO Variety(name) VALUES("Charmont");
INSERT INTO Variety(name) VALUES("Chasan");
INSERT INTO Variety(name) VALUES("Chasselas");
INSERT INTO Variety(name) VALUES("Chelois");
INSERT INTO Variety(name) VALUES("Chenanson");
INSERT INTO Variety(name) VALUES("Chenel");
INSERT INTO Variety(name) VALUES("Chenin Blanc");
INSERT INTO Variety(name) VALUES("Chianti Blend");
INSERT INTO Variety(name) VALUES("Cider");
INSERT INTO Variety(name) VALUES("Cienna");
INSERT INTO Variety(name) VALUES("Ciliegiolo");
INSERT INTO Variety(name) VALUES("Cinsaut");
INSERT INTO Variety(name) VALUES("Cinsaut - Grenache");
INSERT INTO Variety(name) VALUES("Cinsaut - Grenache - Mourvedre");
INSERT INTO Variety(name) VALUES("Cinsaut - Grenache - Syrah");
INSERT INTO Variety(name) VALUES("Cinsaut - Mourvedre");
INSERT INTO Variety(name) VALUES("Cinsaut - Mourvedre - Syrah");
INSERT INTO Variety(name) VALUES("Cinsaut - Pinotage");
INSERT INTO Variety(name) VALUES("Cinsaut - Syrah");
INSERT INTO Variety(name) VALUES("Cividino");
INSERT INTO Variety(name) VALUES("Clairette");
INSERT INTO Variety(name) VALUES("Clairette - Marsanne");
INSERT INTO Variety(name) VALUES("Clairette - Marsanne - Ugni");
INSERT INTO Variety(name) VALUES("Clairette - Muscat");
INSERT INTO Variety(name) VALUES("Clairette - Rolle");
INSERT INTO Variety(name) VALUES("Clairette - Ugni Blanc");
INSERT INTO Variety(name) VALUES("Claret de Gers");
INSERT INTO Variety(name) VALUES("Clinton");
INSERT INTO Variety(name) VALUES("Cococciola");
INSERT INTO Variety(name) VALUES("Coda di Volpe");
INSERT INTO Variety(name) VALUES("Codega do Larinho");
INSERT INTO Variety(name) VALUES("Colombard");
INSERT INTO Variety(name) VALUES("Colombard - Folle - Ugni");
INSERT INTO Variety(name) VALUES("Colombard - Ugni Blanc");
INSERT INTO Variety(name) VALUES("Colorino");
INSERT INTO Variety(name) VALUES("Completer");
INSERT INTO Variety(name) VALUES("Concord");
INSERT INTO Variety(name) VALUES("Corinto Nero");
INSERT INTO Variety(name) VALUES("Cornalin");
INSERT INTO Variety(name) VALUES("Cornifesto");
INSERT INTO Variety(name) VALUES("Corot Noir");
INSERT INTO Variety(name) VALUES("Cortese");
INSERT INTO Variety(name) VALUES("Corvina");
INSERT INTO Variety(name) VALUES("Corvina - Rondinella");
INSERT INTO Variety(name) VALUES("Corvinone");
INSERT INTO Variety(name) VALUES("Couderc Noir");
INSERT INTO Variety(name) VALUES("Counoise");
INSERT INTO Variety(name) VALUES("Courbu Blanc");
INSERT INTO Variety(name) VALUES("Criolla Grande");
INSERT INTO Variety(name) VALUES("Croatina");
INSERT INTO Variety(name) VALUES("Crouchen (Cape Riesling)");
INSERT INTO Variety(name) VALUES("Crovino");
INSERT INTO Variety(name) VALUES("Cserszegi Fuszeres");
INSERT INTO Variety(name) VALUES("Cygne Blanc");
INSERT INTO Variety(name) VALUES("Cyser");
INSERT INTO Variety(name) VALUES("Dafni");
INSERT INTO Variety(name) VALUES("Damaschino");
INSERT INTO Variety(name) VALUES("Dameron");
INSERT INTO Variety(name) VALUES("Darnekusa");
INSERT INTO Variety(name) VALUES("Debina");
INSERT INTO Variety(name) VALUES("Debit");
INSERT INTO Variety(name) VALUES("De Chaunac");
INSERT INTO Variety(name) VALUES("Delaware");
INSERT INTO Variety(name) VALUES("Diamond");
INSERT INTO Variety(name) VALUES("Dimiat");
INSERT INTO Variety(name) VALUES("Dindarella");
INSERT INTO Variety(name) VALUES("Diolinoir");
INSERT INTO Variety(name) VALUES("Dobricic");
INSERT INTO Variety(name) VALUES("Dolcetto");
INSERT INTO Variety(name) VALUES("Domina");
INSERT INTO Variety(name) VALUES("Dona Blanca");
INSERT INTO Variety(name) VALUES("Donzelinho Branco");
INSERT INTO Variety(name) VALUES("Doral");
INSERT INTO Variety(name) VALUES("Dornfelder");
INSERT INTO Variety(name) VALUES("Dorona di Venezia");
INSERT INTO Variety(name) VALUES("Doux d'Henry");
INSERT INTO Variety(name) VALUES("Drink Mixer");
INSERT INTO Variety(name) VALUES("Dunkelfelder");
INSERT INTO Variety(name) VALUES("Duras");
INSERT INTO Variety(name) VALUES("Duras - Fer Servadou");
INSERT INTO Variety(name) VALUES("Duras - Fer - Syrah");
INSERT INTO Variety(name) VALUES("Duras - Syrah");
INSERT INTO Variety(name) VALUES("Durella");
INSERT INTO Variety(name) VALUES("Durif - Shiraz");
INSERT INTO Variety(name) VALUES("Durize");
INSERT INTO Variety(name) VALUES("Dzvelshava");
INSERT INTO Variety(name) VALUES("Early Muscat");
INSERT INTO Variety(name) VALUES("Eau-de-Vie");
INSERT INTO Variety(name) VALUES("Edelweiss");
INSERT INTO Variety(name) VALUES("Edelzwicker Blend");
INSERT INTO Variety(name) VALUES("Egiodola");
INSERT INTO Variety(name) VALUES("Ehrenfelser");
INSERT INTO Variety(name) VALUES("Elbling");
INSERT INTO Variety(name) VALUES("Elvira");
INSERT INTO Variety(name) VALUES("Emerald Riesling");
INSERT INTO Variety(name) VALUES("Emir");
INSERT INTO Variety(name) VALUES("Enantio");
INSERT INTO Variety(name) VALUES("Encruzado");
INSERT INTO Variety(name) VALUES("Erbaluce");
INSERT INTO Variety(name) VALUES("Espadeiro");
INSERT INTO Variety(name) VALUES("Etraire de l'Adui");
INSERT INTO Variety(name) VALUES("Eyholzer");
INSERT INTO Variety(name) VALUES("Ezerjo");
INSERT INTO Variety(name) VALUES("Faber");
INSERT INTO Variety(name) VALUES("Falanghina");
INSERT INTO Variety(name) VALUES("Fernao Pires");
INSERT INTO Variety(name) VALUES("Fer Servadou");
INSERT INTO Variety(name) VALUES("Feteasca Alba");
INSERT INTO Variety(name) VALUES("Feteasca Neagra");
INSERT INTO Variety(name) VALUES("Feteasca Regala");
INSERT INTO Variety(name) VALUES("Fiano");
INSERT INTO Variety(name) VALUES("Findling");
INSERT INTO Variety(name) VALUES("Flavored - Spiced - Fruit Wine");
INSERT INTO Variety(name) VALUES("Flora");
INSERT INTO Variety(name) VALUES("Florental");
INSERT INTO Variety(name) VALUES("Foglia Tonda");
INSERT INTO Variety(name) VALUES("Fogoneu");
INSERT INTO Variety(name) VALUES("Folgasao");
INSERT INTO Variety(name) VALUES("Folle Blanche");
INSERT INTO Variety(name) VALUES("Forastera");
INSERT INTO Variety(name) VALUES("Fortana");
INSERT INTO Variety(name) VALUES("Francavilla");
INSERT INTO Variety(name) VALUES("Franc Noir de la Haute-Saone");
INSERT INTO Variety(name) VALUES("Francusa");
INSERT INTO Variety(name) VALUES("Frappato");
INSERT INTO Variety(name) VALUES("Frappato - Nero d'Avola");
INSERT INTO Variety(name) VALUES("Freisa");
INSERT INTO Variety(name) VALUES("Freisamer");
INSERT INTO Variety(name) VALUES("Friulano");
INSERT INTO Variety(name) VALUES("Frontenac");
INSERT INTO Variety(name) VALUES("Frontenac Gris");
INSERT INTO Variety(name) VALUES("Fruhburgunder");
INSERT INTO Variety(name) VALUES("Fruhroter Veltliner");
INSERT INTO Variety(name) VALUES("Fumin");
INSERT INTO Variety(name) VALUES("Furmint");
INSERT INTO Variety(name) VALUES("Gaglioppo");
INSERT INTO Variety(name) VALUES("Gaidoura");
INSERT INTO Variety(name) VALUES("Gamaret");
INSERT INTO Variety(name) VALUES("Gamaret - Garanoir");
INSERT INTO Variety(name) VALUES("Gamaret - Garanoir - Pinot Noir");
INSERT INTO Variety(name) VALUES("Gamay");
INSERT INTO Variety(name) VALUES("Gamay - Grolleau Noir");
INSERT INTO Variety(name) VALUES("Gamay - Pinot Noir");
INSERT INTO Variety(name) VALUES("Gamay - Poulsard");
INSERT INTO Variety(name) VALUES("Gamba di Pernice");
INSERT INTO Variety(name) VALUES("Garanoir");
INSERT INTO Variety(name) VALUES("Garganega");
INSERT INTO Variety(name) VALUES("Garganega - Pinot Grigio");
INSERT INTO Variety(name) VALUES("Garnacha - Tempranillo");
INSERT INTO Variety(name) VALUES("Garrido");
INSERT INTO Variety(name) VALUES("Gellewza");
INSERT INTO Variety(name) VALUES("Genever (Jenever)");
INSERT INTO Variety(name) VALUES("Gewurztraminer");
INSERT INTO Variety(name) VALUES("Gewurztraminer - Riesling");
INSERT INTO Variety(name) VALUES("Gin");
INSERT INTO Variety(name) VALUES("Gin Liqueur");
INSERT INTO Variety(name) VALUES("Girgentina");
INSERT INTO Variety(name) VALUES("Giro");
INSERT INTO Variety(name) VALUES("Glera (Prosecco)");
INSERT INTO Variety(name) VALUES("Godello");
INSERT INTO Variety(name) VALUES("Goldburger");
INSERT INTO Variety(name) VALUES("Goldriesling");
INSERT INTO Variety(name) VALUES("Gouais Blanc");
INSERT INTO Variety(name) VALUES("Gouveio");
INSERT INTO Variety(name) VALUES("Graciano");
INSERT INTO Variety(name) VALUES("Grappa");
INSERT INTO Variety(name) VALUES("Grechetto");
INSERT INTO Variety(name) VALUES("Grechetto Rosso");
INSERT INTO Variety(name) VALUES("Greco");
INSERT INTO Variety(name) VALUES("Greco Bianco");
INSERT INTO Variety(name) VALUES("Greco Nero");
INSERT INTO Variety(name) VALUES("Green Hungarian");
INSERT INTO Variety(name) VALUES("Grenache Blanc");
INSERT INTO Variety(name) VALUES("Grenache Blanc - Grenache Gris");
INSERT INTO Variety(name) VALUES("Grenache Blanc - Vermentino");
INSERT INTO Variety(name) VALUES("Grenache (Garnacha)");
INSERT INTO Variety(name) VALUES("Grenache Gris");
INSERT INTO Variety(name) VALUES("Grenache - Merlot - Syrah");
INSERT INTO Variety(name) VALUES("Grenache - Mourvedre");
INSERT INTO Variety(name) VALUES("Grenache - Mourvedre - Syrah");
INSERT INTO Variety(name) VALUES("Grenache - Sangiovese");
INSERT INTO Variety(name) VALUES("Grenache - Syrah");
INSERT INTO Variety(name) VALUES("Grignolino");
INSERT INTO Variety(name) VALUES("Grillo");
INSERT INTO Variety(name) VALUES("Gringet");
INSERT INTO Variety(name) VALUES("Grk");
INSERT INTO Variety(name) VALUES("Grolleau Gris");
INSERT INTO Variety(name) VALUES("Grolleau Noir");
INSERT INTO Variety(name) VALUES("Groppello");
INSERT INTO Variety(name) VALUES("Gros Manseng");
INSERT INTO Variety(name) VALUES("Gros Manseng - Petit Manseng");
INSERT INTO Variety(name) VALUES("Gros Manseng - Sauvignon Blanc");
INSERT INTO Variety(name) VALUES("Gros Verdot");
INSERT INTO Variety(name) VALUES("Gruner Veltliner");
INSERT INTO Variety(name) VALUES("Gutenborner");
INSERT INTO Variety(name) VALUES("Happoshu");
INSERT INTO Variety(name) VALUES("Hard Seltzer");
INSERT INTO Variety(name) VALUES("Harslevelu");
INSERT INTO Variety(name) VALUES("Helfensteiner");
INSERT INTO Variety(name) VALUES("Heroldrebe");
INSERT INTO Variety(name) VALUES("Himbertscha");
INSERT INTO Variety(name) VALUES("Hondarrabi Beltza");
INSERT INTO Variety(name) VALUES("Hondarrabi Zuri");
INSERT INTO Variety(name) VALUES("Honey");
INSERT INTO Variety(name) VALUES("Humagne Blanche");
INSERT INTO Variety(name) VALUES("Humagne Rouge");
INSERT INTO Variety(name) VALUES("Huxelrebe");
INSERT INTO Variety(name) VALUES("Inzolia");
INSERT INTO Variety(name) VALUES("Irsay Oliver");
INSERT INTO Variety(name) VALUES("Isabella");
INSERT INTO Variety(name) VALUES("Ives");
INSERT INTO Variety(name) VALUES("Jacquere");
INSERT INTO Variety(name) VALUES("Jampal");
INSERT INTO Variety(name) VALUES("Johanniter");
INSERT INTO Variety(name) VALUES("Joubertin");
INSERT INTO Variety(name) VALUES("Juan Garcia");
INSERT INTO Variety(name) VALUES("Juhfark");
INSERT INTO Variety(name) VALUES("Jurancon Blanc");
INSERT INTO Variety(name) VALUES("Jurancon Noir (Folle Noire)");
INSERT INTO Variety(name) VALUES("Juwel");
INSERT INTO Variety(name) VALUES("Kabar");
INSERT INTO Variety(name) VALUES("Kadarka Blau");
INSERT INTO Variety(name) VALUES("Kalecik Karasi");
INSERT INTO Variety(name) VALUES("Kanzler");
INSERT INTO Variety(name) VALUES("Karasakiz");
INSERT INTO Variety(name) VALUES("Katsano");
INSERT INTO Variety(name) VALUES("Keduretuli (Mujuretuli)");
INSERT INTO Variety(name) VALUES("Kekmedoc");
INSERT INTO Variety(name) VALUES("Keknyelu");
INSERT INTO Variety(name) VALUES("Kerner");
INSERT INTO Variety(name) VALUES("Kombucha");
INSERT INTO Variety(name) VALUES("Koshu");
INSERT INTO Variety(name) VALUES("Kotsifali");
INSERT INTO Variety(name) VALUES("Kotsifali - Mandilaria");
INSERT INTO Variety(name) VALUES("Koverszolo (Grasa de Cotnari)");
INSERT INTO Variety(name) VALUES("Kovidinka");
INSERT INTO Variety(name) VALUES("Krakhuna");
INSERT INTO Variety(name) VALUES("Krassato");
INSERT INTO Variety(name) VALUES("Kuldzhinskii (Kouldjinka)");
INSERT INTO Variety(name) VALUES("La Crescent");
INSERT INTO Variety(name) VALUES("Lacrima");
INSERT INTO Variety(name) VALUES("La Crosse");
INSERT INTO Variety(name) VALUES("Lado");
INSERT INTO Variety(name) VALUES("Lagorthi");
INSERT INTO Variety(name) VALUES("Lagrein");
INSERT INTO Variety(name) VALUES("Lambrusco");
INSERT INTO Variety(name) VALUES("Landot Noir");
INSERT INTO Variety(name) VALUES("Lasin");
INSERT INTO Variety(name) VALUES("Lauzet");
INSERT INTO Variety(name) VALUES("Leanyka");
INSERT INTO Variety(name) VALUES("Lemberger - Trollinger");
INSERT INTO Variety(name) VALUES("Len de l'El");
INSERT INTO Variety(name) VALUES("Len de l'El - Mauzac");
INSERT INTO Variety(name) VALUES("Leon Millot");
INSERT INTO Variety(name) VALUES("Liatiko");
INSERT INTO Variety(name) VALUES("Liebfraumilch");
INSERT INTO Variety(name) VALUES("Limnio");
INSERT INTO Variety(name) VALUES("Liqueur");
INSERT INTO Variety(name) VALUES("Liqueur - Anise");
INSERT INTO Variety(name) VALUES("Liqueur - Chocolate");
INSERT INTO Variety(name) VALUES("Liqueur - Coffee");
INSERT INTO Variety(name) VALUES("Liqueur - Cream");
INSERT INTO Variety(name) VALUES("Liqueur - Egg");
INSERT INTO Variety(name) VALUES("Liqueur - Fruit");
INSERT INTO Variety(name) VALUES("Liqueur - Herb - Spice");
INSERT INTO Variety(name) VALUES("Liqueur - Nut");
INSERT INTO Variety(name) VALUES("Liqueur - Toffee");
INSERT INTO Variety(name) VALUES("Listan Negro");
INSERT INTO Variety(name) VALUES("Lledoner Pelut");
INSERT INTO Variety(name) VALUES("Loureiro");
INSERT INTO Variety(name) VALUES("Lucie Kuhlmann");
INSERT INTO Variety(name) VALUES("Luglienga Bianca");
INSERT INTO Variety(name) VALUES("Lumassina");
INSERT INTO Variety(name) VALUES("Macabeo - Parellada - Xarel-lo");
INSERT INTO Variety(name) VALUES("Macabeo (Viura)");
INSERT INTO Variety(name) VALUES("Maceratino");
INSERT INTO Variety(name) VALUES("Madeleine Angevine");
INSERT INTO Variety(name) VALUES("Magliocco Canino");
INSERT INTO Variety(name) VALUES("Majarca Alba");
INSERT INTO Variety(name) VALUES("Makgeolli");
INSERT INTO Variety(name) VALUES("Malagousia");
INSERT INTO Variety(name) VALUES("Malbec");
INSERT INTO Variety(name) VALUES("Malbec - Merlot");
INSERT INTO Variety(name) VALUES("Malbec - Merlot - Tannat");
INSERT INTO Variety(name) VALUES("Malbec - Pinot Noir");
INSERT INTO Variety(name) VALUES("Malbec - Syrah");
INSERT INTO Variety(name) VALUES("Malbo Gentile");
INSERT INTO Variety(name) VALUES("Malt Beverage");
INSERT INTO Variety(name) VALUES("Malvar");
INSERT INTO Variety(name) VALUES("Malvasia");
INSERT INTO Variety(name) VALUES("Malvasia Bianca");
INSERT INTO Variety(name) VALUES("Malvasia di Candia");
INSERT INTO Variety(name) VALUES("Malvasia Nera");
INSERT INTO Variety(name) VALUES("Malvasia Nera - Negroamaro");
INSERT INTO Variety(name) VALUES("Malvasia - Trebbiano");
INSERT INTO Variety(name) VALUES("Mandilaria (Amorghiano)");
INSERT INTO Variety(name) VALUES("Mansengs - Petit Courbu");
INSERT INTO Variety(name) VALUES("Manto Negro");
INSERT INTO Variety(name) VALUES("Mantonico Bianco");
INSERT INTO Variety(name) VALUES("Manzoni Bianco");
INSERT INTO Variety(name) VALUES("Marastina");
INSERT INTO Variety(name) VALUES("Maratheftiko");
INSERT INTO Variety(name) VALUES("Marechal Foch");
INSERT INTO Variety(name) VALUES("Marmajuelo");
INSERT INTO Variety(name) VALUES("Marquette");
INSERT INTO Variety(name) VALUES("Marsanne");
INSERT INTO Variety(name) VALUES("Marsanne - Roussanne");
INSERT INTO Variety(name) VALUES("Marselan");
INSERT INTO Variety(name) VALUES("Marzemino");
INSERT INTO Variety(name) VALUES("Matrassa");
INSERT INTO Variety(name) VALUES("Maturana Blanca");
INSERT INTO Variety(name) VALUES("Maturana Tinta");
INSERT INTO Variety(name) VALUES("Mauzac");
INSERT INTO Variety(name) VALUES("Mavro");
INSERT INTO Variety(name) VALUES("Mavrodaphne");
INSERT INTO Variety(name) VALUES("Mavrotragano");
INSERT INTO Variety(name) VALUES("Mavrud");
INSERT INTO Variety(name) VALUES("Mayolet");
INSERT INTO Variety(name) VALUES("Melara");
INSERT INTO Variety(name) VALUES("Melnik");
INSERT INTO Variety(name) VALUES("Melody");
INSERT INTO Variety(name) VALUES("Melomel");
INSERT INTO Variety(name) VALUES("Melon de Bourgogne");
INSERT INTO Variety(name) VALUES("Melon Queue Rouge");
INSERT INTO Variety(name) VALUES("Mencia");
INSERT INTO Variety(name) VALUES("Merille");
INSERT INTO Variety(name) VALUES("Meritage");
INSERT INTO Variety(name) VALUES("Merlot");
INSERT INTO Variety(name) VALUES("Merlot Blanc");
INSERT INTO Variety(name) VALUES("Merlot - Montepulciano");
INSERT INTO Variety(name) VALUES("Merlot - Nero d'Avola");
INSERT INTO Variety(name) VALUES("Merlot - Sagrantino - Sangiovese");
INSERT INTO Variety(name) VALUES("Merlot - Sangiovese");
INSERT INTO Variety(name) VALUES("Merlot - Sangiovese - Syrah");
INSERT INTO Variety(name) VALUES("Merlot - Syrah");
INSERT INTO Variety(name) VALUES("Merlot - Tannat");
INSERT INTO Variety(name) VALUES("Merlot - Tempranillo");
INSERT INTO Variety(name) VALUES("Merseguera");
INSERT INTO Variety(name) VALUES("Merwah");
INSERT INTO Variety(name) VALUES("Merzling");
INSERT INTO Variety(name) VALUES("Mezcal");
INSERT INTO Variety(name) VALUES("Milgranet");
INSERT INTO Variety(name) VALUES("Minhota");
INSERT INTO Variety(name) VALUES("Minnella");
INSERT INTO Variety(name) VALUES("Mischurnitz");
INSERT INTO Variety(name) VALUES("Miss Blanc");
INSERT INTO Variety(name) VALUES("Molinara");
INSERT INTO Variety(name) VALUES("Moll");
INSERT INTO Variety(name) VALUES("Monastrell - Tempranillo");
INSERT INTO Variety(name) VALUES("Mondeuse Blanche");
INSERT INTO Variety(name) VALUES("Mondeuse Noire");
INSERT INTO Variety(name) VALUES("Monica");
INSERT INTO Variety(name) VALUES("Montepulciano");
INSERT INTO Variety(name) VALUES("Montepulciano - Sangiovese");
INSERT INTO Variety(name) VALUES("Montepulciano - Syrah");
INSERT INTO Variety(name) VALUES("Montonega");
INSERT INTO Variety(name) VALUES("Montuni");
INSERT INTO Variety(name) VALUES("Moravia Agria");
INSERT INTO Variety(name) VALUES("Moreto");
INSERT INTO Variety(name) VALUES("Morio-Muskat");
INSERT INTO Variety(name) VALUES("Moristel");
INSERT INTO Variety(name) VALUES("Moscato Giallo");
INSERT INTO Variety(name) VALUES("Moscato Rosa");
INSERT INTO Variety(name) VALUES("Moschofilero");
INSERT INTO Variety(name) VALUES("Moschofilero - Roditis");
INSERT INTO Variety(name) VALUES("Mourisco Tinto");
INSERT INTO Variety(name) VALUES("Mourvedre (Monastrell)");
INSERT INTO Variety(name) VALUES("Mourvedre - Syrah");
INSERT INTO Variety(name) VALUES("Mtsvani");
INSERT INTO Variety(name) VALUES("Muller-Thurgau");
INSERT INTO Variety(name) VALUES("Muscadelle");
INSERT INTO Variety(name) VALUES("Muscadine");
INSERT INTO Variety(name) VALUES("Muscardin");
INSERT INTO Variety(name) VALUES("Muscat");
INSERT INTO Variety(name) VALUES("Muscat Bailey A");
INSERT INTO Variety(name) VALUES("Muscat Blanc a Petits Grains");
INSERT INTO Variety(name) VALUES("Muscat Hamburg (Muskat Trollinger)");
INSERT INTO Variety(name) VALUES("Muscat of Alexandria");
INSERT INTO Variety(name) VALUES("Muscat Ottonel");
INSERT INTO Variety(name) VALUES("Muscat - Viognier");
INSERT INTO Variety(name) VALUES("Muskat Moravsky");
INSERT INTO Variety(name) VALUES("Narince");
INSERT INTO Variety(name) VALUES("Nascetta");
INSERT INTO Variety(name) VALUES("Nasco");
INSERT INTO Variety(name) VALUES("Nebbiolo");
INSERT INTO Variety(name) VALUES("Negoska");
INSERT INTO Variety(name) VALUES("Negrara");
INSERT INTO Variety(name) VALUES("Negrette");
INSERT INTO Variety(name) VALUES("Negroamaro");
INSERT INTO Variety(name) VALUES("Negroamaro - Primitivo");
INSERT INTO Variety(name) VALUES("Nerello Cappuccio");
INSERT INTO Variety(name) VALUES("Nerello Cappuccio - Nerello Mascalese");
INSERT INTO Variety(name) VALUES("Nerello Mascalese");
INSERT INTO Variety(name) VALUES("Nero Buono");
INSERT INTO Variety(name) VALUES("Nero d'Avola");
INSERT INTO Variety(name) VALUES("Nero d'Avola - Syrah");
INSERT INTO Variety(name) VALUES("Neuburger");
INSERT INTO Variety(name) VALUES("New-make Spirit");
INSERT INTO Variety(name) VALUES("Neyret");
INSERT INTO Variety(name) VALUES("Niagara");
INSERT INTO Variety(name) VALUES("Nielluccio - Sciaccarello");
INSERT INTO Variety(name) VALUES("Nincusa");
INSERT INTO Variety(name) VALUES("Noah");
INSERT INTO Variety(name) VALUES("Noblessa");
INSERT INTO Variety(name) VALUES("Nobling");
INSERT INTO Variety(name) VALUES("Nocera");
INSERT INTO Variety(name) VALUES("Noiret");
INSERT INTO Variety(name) VALUES("Norton");
INSERT INTO Variety(name) VALUES("Nosiola");
INSERT INTO Variety(name) VALUES("Nuragus");
INSERT INTO Variety(name) VALUES("Obaideh");
INSERT INTO Variety(name) VALUES("Ojaleshi");
INSERT INTO Variety(name) VALUES("Okuzgozu");
INSERT INTO Variety(name) VALUES("Olivella");
INSERT INTO Variety(name) VALUES("Ondenc");
INSERT INTO Variety(name) VALUES("Opthalmo");
INSERT INTO Variety(name) VALUES("Optima");
INSERT INTO Variety(name) VALUES("Orion");
INSERT INTO Variety(name) VALUES("Orleans");
INSERT INTO Variety(name) VALUES("Ortega");
INSERT INTO Variety(name) VALUES("Ortrugo");
INSERT INTO Variety(name) VALUES("Orvieto Blend");
INSERT INTO Variety(name) VALUES("Oseleta");
INSERT INTO Variety(name) VALUES("Osiris");
INSERT INTO Variety(name) VALUES("Osteiner");
INSERT INTO Variety(name) VALUES("Pais (Mission)");
INSERT INTO Variety(name) VALUES("Palas");
INSERT INTO Variety(name) VALUES("Palava");
INSERT INTO Variety(name) VALUES("Pallagrello Bianco");
INSERT INTO Variety(name) VALUES("Pallagrello Nero");
INSERT INTO Variety(name) VALUES("Palomino");
INSERT INTO Variety(name) VALUES("Pamid");
INSERT INTO Variety(name) VALUES("Pampanuto");
INSERT INTO Variety(name) VALUES("Papazkarasi");
INSERT INTO Variety(name) VALUES("Parc");
INSERT INTO Variety(name) VALUES("Parellada");
INSERT INTO Variety(name) VALUES("Parraleta");
INSERT INTO Variety(name) VALUES("Pascal Blanc");
INSERT INTO Variety(name) VALUES("Passerina");
INSERT INTO Variety(name) VALUES("Passerina - Pecorino - Trebbiano");
INSERT INTO Variety(name) VALUES("Pecorino");
INSERT INTO Variety(name) VALUES("Pedral");
INSERT INTO Variety(name) VALUES("Pedro Ximenez");
INSERT INTO Variety(name) VALUES("Pelaverga");
INSERT INTO Variety(name) VALUES("Peloursin");
INSERT INTO Variety(name) VALUES("Perdea");
INSERT INTO Variety(name) VALUES("Perle");
INSERT INTO Variety(name) VALUES("Perricone");
INSERT INTO Variety(name) VALUES("Persan");
INSERT INTO Variety(name) VALUES("Petit Bouschet");
INSERT INTO Variety(name) VALUES("Petit Courbu");
INSERT INTO Variety(name) VALUES("Petite Arvine");
INSERT INTO Variety(name) VALUES("Petite Sirah (Durif)");
INSERT INTO Variety(name) VALUES("Petite Sirah - Syrah - Zinfandel");
INSERT INTO Variety(name) VALUES("Petite Sirah - Zinfandel");
INSERT INTO Variety(name) VALUES("Petit Manseng");
INSERT INTO Variety(name) VALUES("Petit Meslier");
INSERT INTO Variety(name) VALUES("Petit Rouge");
INSERT INTO Variety(name) VALUES("Petit Verdot");
INSERT INTO Variety(name) VALUES("Petroulianos");
INSERT INTO Variety(name) VALUES("Peurion");
INSERT INTO Variety(name) VALUES("Phoenix");
INSERT INTO Variety(name) VALUES("Piccola Nera");
INSERT INTO Variety(name) VALUES("Picolit");
INSERT INTO Variety(name) VALUES("Picpoul");
INSERT INTO Variety(name) VALUES("Picpoul Noir");
INSERT INTO Variety(name) VALUES("Piculit Neri");
INSERT INTO Variety(name) VALUES("Piedirosso");
INSERT INTO Variety(name) VALUES("Pignerol");
INSERT INTO Variety(name) VALUES("Pignola");
INSERT INTO Variety(name) VALUES("Pignolo");
INSERT INTO Variety(name) VALUES("Pinard");
INSERT INTO Variety(name) VALUES("Pineau d'Aunis");
INSERT INTO Variety(name) VALUES("Pinella (Pinello)");
INSERT INTO Variety(name) VALUES("Pink Gin");
INSERT INTO Variety(name) VALUES("Pinotage");
INSERT INTO Variety(name) VALUES("Pinotage - Shiraz");
INSERT INTO Variety(name) VALUES("Pinot Blanc");
INSERT INTO Variety(name) VALUES("Pinot Blanc - Pinot Noir");
INSERT INTO Variety(name) VALUES("Pinot d'Alsace");
INSERT INTO Variety(name) VALUES("Pinot Grigio");
INSERT INTO Variety(name) VALUES("Pinot Grigio - Zibibbo");
INSERT INTO Variety(name) VALUES("Pinot Gris");
INSERT INTO Variety(name) VALUES("Pinot Gris - Sauvignon Blanc");
INSERT INTO Variety(name) VALUES("Pinot Meunier");
INSERT INTO Variety(name) VALUES("Pinot Meunier - Pinot Noir");
INSERT INTO Variety(name) VALUES("Pinot Noir");
INSERT INTO Variety(name) VALUES("Pinot Noir - Syrah");
INSERT INTO Variety(name) VALUES("Pinot Noir - Zweigelt");
INSERT INTO Variety(name) VALUES("Pinot - Poulsard - Trousseau");
INSERT INTO Variety(name) VALUES("Pisco");
INSERT INTO Variety(name) VALUES("Planta Fina de Pedralba");
INSERT INTO Variety(name) VALUES("Planta Nova");
INSERT INTO Variety(name) VALUES("Plantet");
INSERT INTO Variety(name) VALUES("Plavac Mali");
INSERT INTO Variety(name) VALUES("Plavac Veli");
INSERT INTO Variety(name) VALUES("Plavina");
INSERT INTO Variety(name) VALUES("Plyto");
INSERT INTO Variety(name) VALUES("Pollera Nera");
INSERT INTO Variety(name) VALUES("Pontac");
INSERT INTO Variety(name) VALUES("Portan");
INSERT INTO Variety(name) VALUES("Port Blend Red");
INSERT INTO Variety(name) VALUES("Port Blend White");
INSERT INTO Variety(name) VALUES("Portugieser");
INSERT INTO Variety(name) VALUES("Portuguese Red Blend");
INSERT INTO Variety(name) VALUES("Portuguese White Blend");
INSERT INTO Variety(name) VALUES("Posip");
INSERT INTO Variety(name) VALUES("Poulsard");
INSERT INTO Variety(name) VALUES("Precoce de Malingre");
INSERT INTO Variety(name) VALUES("Premetta");
INSERT INTO Variety(name) VALUES("Premixed Drinks");
INSERT INTO Variety(name) VALUES("Prie Blanc");
INSERT INTO Variety(name) VALUES("Prieto Picudo");
INSERT INTO Variety(name) VALUES("Primitivo");
INSERT INTO Variety(name) VALUES("Prokupac");
INSERT INTO Variety(name) VALUES("Prunelard Blanc");
INSERT INTO Variety(name) VALUES("Prunelard Noir");
INSERT INTO Variety(name) VALUES("Pugnitello");
INSERT INTO Variety(name) VALUES("Quagliano");
INSERT INTO Variety(name) VALUES("Rabo de Ovelha");
INSERT INTO Variety(name) VALUES("Raboso");
INSERT INTO Variety(name) VALUES("Radler-Shandy");
INSERT INTO Variety(name) VALUES("Raffiat de Moncade");
INSERT INTO Variety(name) VALUES("Ramisco");
INSERT INTO Variety(name) VALUES("Rare Red Blend");
INSERT INTO Variety(name) VALUES("Rare Rose Blend");
INSERT INTO Variety(name) VALUES("Rare White Blend");
INSERT INTO Variety(name) VALUES("Rassegui");
INSERT INTO Variety(name) VALUES("Ratafia");
INSERT INTO Variety(name) VALUES("Rathay");
INSERT INTO Variety(name) VALUES("Rauschling");
INSERT INTO Variety(name) VALUES("Ravat Blanc");
INSERT INTO Variety(name) VALUES("Ravat Vignoles");
INSERT INTO Variety(name) VALUES("Rayon d'Or");
INSERT INTO Variety(name) VALUES("Rebo");
INSERT INTO Variety(name) VALUES("Refosco");
INSERT INTO Variety(name) VALUES("Regent");
INSERT INTO Variety(name) VALUES("Regner");
INSERT INTO Variety(name) VALUES("Reichensteiner");
INSERT INTO Variety(name) VALUES("Reze");
INSERT INTO Variety(name) VALUES("Ribolla");
INSERT INTO Variety(name) VALUES("Rieslaner");
INSERT INTO Variety(name) VALUES("Riesling");
INSERT INTO Variety(name) VALUES("Riesling - Silvaner");
INSERT INTO Variety(name) VALUES("Rioja Red Blend");
INSERT INTO Variety(name) VALUES("Rioja White Blend");
INSERT INTO Variety(name) VALUES("Rkatsiteli");
INSERT INTO Variety(name) VALUES("Robola");
INSERT INTO Variety(name) VALUES("Roditis");
INSERT INTO Variety(name) VALUES("Roesler");
INSERT INTO Variety(name) VALUES("Rolle - Ugni Blanc");
INSERT INTO Variety(name) VALUES("Romorantin");
INSERT INTO Variety(name) VALUES("Rondinella");
INSERT INTO Variety(name) VALUES("Rondo");
INSERT INTO Variety(name) VALUES("Roscetto");
INSERT INTO Variety(name) VALUES("Rossara");
INSERT INTO Variety(name) VALUES("Rossese");
INSERT INTO Variety(name) VALUES("Rossola Nera");
INSERT INTO Variety(name) VALUES("Rotberger");
INSERT INTO Variety(name) VALUES("Roter Gutedel");
INSERT INTO Variety(name) VALUES("Roter Riesling");
INSERT INTO Variety(name) VALUES("Roter Traminer (Savagnin Rose)");
INSERT INTO Variety(name) VALUES("Roter Veltliner");
INSERT INTO Variety(name) VALUES("Rotgipfler");
INSERT INTO Variety(name) VALUES("Rougeon");
INSERT INTO Variety(name) VALUES("Roussanne");
INSERT INTO Variety(name) VALUES("Roussanne - Viognier");
INSERT INTO Variety(name) VALUES("Royalty");
INSERT INTO Variety(name) VALUES("Rubienne");
INSERT INTO Variety(name) VALUES("Rubin Bolgarskii");
INSERT INTO Variety(name) VALUES("Rubired");
INSERT INTO Variety(name) VALUES("Ruby Cabernet");
INSERT INTO Variety(name) VALUES("Ruche");
INSERT INTO Variety(name) VALUES("Rufete (Tinta Pinheira)");
INSERT INTO Variety(name) VALUES("Rum");
INSERT INTO Variety(name) VALUES("Rum - Liqueur - Flavored");
INSERT INTO Variety(name) VALUES("Sacy");
INSERT INTO Variety(name) VALUES("Sagrantino");
INSERT INTO Variety(name) VALUES("Sagrantino - Sangiovese");
INSERT INTO Variety(name) VALUES("Saint-Croix");
INSERT INTO Variety(name) VALUES("Saint-Jeannet");
INSERT INTO Variety(name) VALUES("Saint-Macaire");
INSERT INTO Variety(name) VALUES("Saint-Pepin");
INSERT INTO Variety(name) VALUES("Sake");
INSERT INTO Variety(name) VALUES("Samtrot");
INSERT INTO Variety(name) VALUES("Sangiovese");
INSERT INTO Variety(name) VALUES("Sangiovese - Syrah");
INSERT INTO Variety(name) VALUES("Sangria");
INSERT INTO Variety(name) VALUES("Sankt Laurent");
INSERT INTO Variety(name) VALUES("Santa Maria");
INSERT INTO Variety(name) VALUES("Saperavi");
INSERT INTO Variety(name) VALUES("Sauvignon Blanc");
INSERT INTO Variety(name) VALUES("Sauvignon Blanc - Semillon");
INSERT INTO Variety(name) VALUES("Sauvignon Blanc - Ugni Blanc");
INSERT INTO Variety(name) VALUES("Sauvignon Blanc - Verdejo");
INSERT INTO Variety(name) VALUES("Sauvignon Blanc - Vermentino");
INSERT INTO Variety(name) VALUES("Sauvignon Blanc - Viognier");
INSERT INTO Variety(name) VALUES("Sauvignon Gris");
INSERT INTO Variety(name) VALUES("Savagnin");
INSERT INTO Variety(name) VALUES("Savatiano");
INSERT INTO Variety(name) VALUES("Scheurebe");
INSERT INTO Variety(name) VALUES("Schiava");
INSERT INTO Variety(name) VALUES("Schioppettino");
INSERT INTO Variety(name) VALUES("Schnapps");
INSERT INTO Variety(name) VALUES("Schonburger");
INSERT INTO Variety(name) VALUES("Sciaccarello (Mammolo)");
INSERT INTO Variety(name) VALUES("Scuppernong");
INSERT INTO Variety(name) VALUES("Semidano");
INSERT INTO Variety(name) VALUES("Semillon");
INSERT INTO Variety(name) VALUES("Semillon - Rolle");
INSERT INTO Variety(name) VALUES("Sercial");
INSERT INTO Variety(name) VALUES("Seyval Blanc");
INSERT INTO Variety(name) VALUES("Sgavetta");
INSERT INTO Variety(name) VALUES("Sherry Blend");
INSERT INTO Variety(name) VALUES("Shiraz");
INSERT INTO Variety(name) VALUES("Shochu");
INSERT INTO Variety(name) VALUES("Sideritis");
INSERT INTO Variety(name) VALUES("Siegerrebe");
INSERT INTO Variety(name) VALUES("Silcher");
INSERT INTO Variety(name) VALUES("Silvaner");
INSERT INTO Variety(name) VALUES("Siria (Roupeiro)");
INSERT INTO Variety(name) VALUES("Skrlet");
INSERT INTO Variety(name) VALUES("Smederevka");
INSERT INTO Variety(name) VALUES("Soave Blend");
INSERT INTO Variety(name) VALUES("Soju");
INSERT INTO Variety(name) VALUES("Solaris");
INSERT INTO Variety(name) VALUES("Sotol");
INSERT INTO Variety(name) VALUES("Southern Rhone Red Blend");
INSERT INTO Variety(name) VALUES("Southern Rhone White Blend");
INSERT INTO Variety(name) VALUES("Spergola");
INSERT INTO Variety(name) VALUES("Stavroto");
INSERT INTO Variety(name) VALUES("Steuben");
INSERT INTO Variety(name) VALUES("Sultana");
INSERT INTO Variety(name) VALUES("Sumoll");
INSERT INTO Variety(name) VALUES("Sumoll Blanco");
INSERT INTO Variety(name) VALUES("Susumaniello");
INSERT INTO Variety(name) VALUES("Symphony");
INSERT INTO Variety(name) VALUES("Syrah");
INSERT INTO Variety(name) VALUES("Syrah - Tempranillo");
INSERT INTO Variety(name) VALUES("Syrah - Touriga");
INSERT INTO Variety(name) VALUES("Syrah - Viognier");
INSERT INTO Variety(name) VALUES("Syrah - Zinfandel");
INSERT INTO Variety(name) VALUES("Szagos Feher");
INSERT INTO Variety(name) VALUES("Taminga");
INSERT INTO Variety(name) VALUES("Tannat");
INSERT INTO Variety(name) VALUES("Tarrango");
INSERT INTO Variety(name) VALUES("Tavkveri");
INSERT INTO Variety(name) VALUES("Tazzelenghe");
INSERT INTO Variety(name) VALUES("Tempranillo");
INSERT INTO Variety(name) VALUES("Tempranillo Blanco");
INSERT INTO Variety(name) VALUES("Tequila");
INSERT INTO Variety(name) VALUES("Teroldego");
INSERT INTO Variety(name) VALUES("Terrantez");
INSERT INTO Variety(name) VALUES("Terret Blanc");
INSERT INTO Variety(name) VALUES("Terret Gris");
INSERT INTO Variety(name) VALUES("Terret Noir");
INSERT INTO Variety(name) VALUES("Tibouren");
INSERT INTO Variety(name) VALUES("Timorasso");
INSERT INTO Variety(name) VALUES("Tinta Amarela (Trincadeira)");
INSERT INTO Variety(name) VALUES("Tinta Barroca");
INSERT INTO Variety(name) VALUES("Tinta Barroca - Tinta Roriz - Touriga");
INSERT INTO Variety(name) VALUES("Tinta Caiada");
INSERT INTO Variety(name) VALUES("Tinta Carvalha");
INSERT INTO Variety(name) VALUES("Tinta Francisca");
INSERT INTO Variety(name) VALUES("Tinta Negra Mole");
INSERT INTO Variety(name) VALUES("Tinta Roriz (Aragonez) - Touriga");
INSERT INTO Variety(name) VALUES("Tinta Roriz - Tinto Cao - Touriga");
INSERT INTO Variety(name) VALUES("Tintilia");
INSERT INTO Variety(name) VALUES("Tinto Cao");
INSERT INTO Variety(name) VALUES("Tintore di Tramonti");
INSERT INTO Variety(name) VALUES("Titan");
INSERT INTO Variety(name) VALUES("Tokaji Blend");
INSERT INTO Variety(name) VALUES("Torbato");
INSERT INTO Variety(name) VALUES("Torrontes");
INSERT INTO Variety(name) VALUES("Touriga Franca");
INSERT INTO Variety(name) VALUES("Touriga Franca - Touriga Nacional");
INSERT INTO Variety(name) VALUES("Touriga Nacional");
INSERT INTO Variety(name) VALUES("Trajadura (Treixadura)");
INSERT INTO Variety(name) VALUES("Traminer");
INSERT INTO Variety(name) VALUES("Traminette");
INSERT INTO Variety(name) VALUES("Trbljan");
INSERT INTO Variety(name) VALUES("Trebbiano Spoletino");
INSERT INTO Variety(name) VALUES("Trebbiano (Ugni Blanc)");
INSERT INTO Variety(name) VALUES("Trepat");
INSERT INTO Variety(name) VALUES("Trincadeira das Pratas");
INSERT INTO Variety(name) VALUES("Triomphe");
INSERT INTO Variety(name) VALUES("Trousseau (Bastardo)");
INSERT INTO Variety(name) VALUES("Trousseau Gris");
INSERT INTO Variety(name) VALUES("Tsaoussi");
INSERT INTO Variety(name) VALUES("Tsitska");
INSERT INTO Variety(name) VALUES("Tsolikouri");
INSERT INTO Variety(name) VALUES("Turan (Agria)");
INSERT INTO Variety(name) VALUES("Umeshu");
INSERT INTO Variety(name) VALUES("Usakhelauri");
INSERT INTO Variety(name) VALUES("Uva del Fantini");
INSERT INTO Variety(name) VALUES("Uva di Troia");
INSERT INTO Variety(name) VALUES("Uva Longanesi");
INSERT INTO Variety(name) VALUES("Uva Rara");
INSERT INTO Variety(name) VALUES("Vaccarese");
INSERT INTO Variety(name) VALUES("Valdiguie");
INSERT INTO Variety(name) VALUES("Valiant");
INSERT INTO Variety(name) VALUES("Valpolicella Blend");
INSERT INTO Variety(name) VALUES("Ventura");
INSERT INTO Variety(name) VALUES("Verdanel");
INSERT INTO Variety(name) VALUES("Verdea");
INSERT INTO Variety(name) VALUES("Verdeca");
INSERT INTO Variety(name) VALUES("Verdejo");
INSERT INTO Variety(name) VALUES("Verdejo - Viura");
INSERT INTO Variety(name) VALUES("Verdelet");
INSERT INTO Variety(name) VALUES("Verdelho");
INSERT INTO Variety(name) VALUES("Verdesse");
INSERT INTO Variety(name) VALUES("Verdicchio");
INSERT INTO Variety(name) VALUES("Verdil");
INSERT INTO Variety(name) VALUES("Verdiso");
INSERT INTO Variety(name) VALUES("Verdoncho");
INSERT INTO Variety(name) VALUES("Verduzzo");
INSERT INTO Variety(name) VALUES("Vermentino Nero");
INSERT INTO Variety(name) VALUES("Vermentino (Rolle)");
INSERT INTO Variety(name) VALUES("Vermouth");
INSERT INTO Variety(name) VALUES("Vernaccia");
INSERT INTO Variety(name) VALUES("Vernaccia Nera");
INSERT INTO Variety(name) VALUES("Vertzami");
INSERT INTO Variety(name) VALUES("Vespaiolo");
INSERT INTO Variety(name) VALUES("Vespolina");
INSERT INTO Variety(name) VALUES("Vidadillo (Crespiello)");
INSERT INTO Variety(name) VALUES("Vidal");
INSERT INTO Variety(name) VALUES("Vidiano");
INSERT INTO Variety(name) VALUES("Vien de Nus");
INSERT INTO Variety(name) VALUES("Vijariego Blanco");
INSERT INTO Variety(name) VALUES("Vijariego Negro");
INSERT INTO Variety(name) VALUES("Vilana");
INSERT INTO Variety(name) VALUES("Villard Blanc");
INSERT INTO Variety(name) VALUES("Vin de Liqueur");
INSERT INTO Variety(name) VALUES("Vinhao (Sousao)");
INSERT INTO Variety(name) VALUES("Viognier");
INSERT INTO Variety(name) VALUES("Viosinho");
INSERT INTO Variety(name) VALUES("Vital");
INSERT INTO Variety(name) VALUES("Vitovska");
INSERT INTO Variety(name) VALUES("Vodka");
INSERT INTO Variety(name) VALUES("Vodka - Flavored");
INSERT INTO Variety(name) VALUES("Volitsa (Volidza)");
INSERT INTO Variety(name) VALUES("Voudomato");
INSERT INTO Variety(name) VALUES("Vradiano");
INSERT INTO Variety(name) VALUES("Vranac");
INSERT INTO Variety(name) VALUES("Vugava");
INSERT INTO Variety(name) VALUES("Vuillermin");
INSERT INTO Variety(name) VALUES("Welschriesling");
INSERT INTO Variety(name) VALUES("Whiskey - America");
INSERT INTO Variety(name) VALUES("Whiskey Bourbon");
INSERT INTO Variety(name) VALUES("Whiskey Corn");
INSERT INTO Variety(name) VALUES("Whiskey - Irish");
INSERT INTO Variety(name) VALUES("Whiskey - Liqueur - Flavored");
INSERT INTO Variety(name) VALUES("Whiskey - Rye");
INSERT INTO Variety(name) VALUES("Whiskey - Wheat");
INSERT INTO Variety(name) VALUES("Whisky - Australia");
INSERT INTO Variety(name) VALUES("Whisky - Canada");
INSERT INTO Variety(name) VALUES("Whisky - India");
INSERT INTO Variety(name) VALUES("Whisky - Japan");
INSERT INTO Variety(name) VALUES("Whisky - Whiskey Blended");
INSERT INTO Variety(name) VALUES("Whisky - Whiskey Grain");
INSERT INTO Variety(name) VALUES("Whisky - Whiskey Malt");
INSERT INTO Variety(name) VALUES("Wurzer");
INSERT INTO Variety(name) VALUES("Xarel-lo");
INSERT INTO Variety(name) VALUES("Xinomavro");
INSERT INTO Variety(name) VALUES("Xynisteri");
INSERT INTO Variety(name) VALUES("Zalema");
INSERT INTO Variety(name) VALUES("Zefir");
INSERT INTO Variety(name) VALUES("Zelen");
INSERT INTO Variety(name) VALUES("Zenit");
INSERT INTO Variety(name) VALUES("Zeta");
INSERT INTO Variety(name) VALUES("Zeus");
INSERT INTO Variety(name) VALUES("Zierfandler");
INSERT INTO Variety(name) VALUES("Zilavka");
INSERT INTO Variety(name) VALUES("Zinfandel");
INSERT INTO Variety(name) VALUES("Zlahtina");
INSERT INTO Variety(name) VALUES("Zweigelt");
