INSERT INTO Style(name) VALUES("Red");
INSERT INTO Style(name) VALUES("White");
INSERT INTO Style(name) VALUES("Sparkling");
INSERT INTO Style(name) VALUES("Rosé");
INSERT INTO Style(name) VALUES("Orange");
INSERT INTO Style(name) VALUES("Dessert");
INSERT INTO Style(name) VALUES("Dessert/Fortified");
INSERT INTO Style(name) VALUES("Dessert/Ice");
INSERT INTO Style(name) VALUES("Dessert/Aromatized");
INSERT INTO Style(name) VALUES("Dessert/Fruit");
INSERT INTO Style(name) VALUES("Dessert/Noble rot");
INSERT INTO Style(name) VALUES("Dessert/Straw");
INSERT INTO Style(name) VALUES("Other");
INSERT INTO Style(name) VALUES("Other/Table");
INSERT INTO Style(name) VALUES("Other/Natural");
INSERT INTO Style(name) VALUES("Other/Biodynamic");
INSERT INTO Style(name) VALUES("Other/Organic");
INSERT INTO Style(name) VALUES("Other/Kosher");
