INSERT INTO Style( ID , NAME ) VALUES( 1 , ' Red ');
INSERT INTO Style( ID , NAME ) VALUES( 2 , ' White ');
INSERT INTO Style( ID , NAME ) VALUES( 3 , ' Sparkling ');
INSERT INTO Style( ID , NAME ) VALUES( 4 , ' Rosé ');
INSERT INTO Style( ID , NAME ) VALUES( 5 , ' Orange ');
INSERT INTO Style( ID , NAME ) VALUES( 6 , ' Dessert ');
INSERT INTO Style( ID , NAME ) VALUES( 7 , ' Dessert/Fortified ');
INSERT INTO Style( ID , NAME ) VALUES( 8 , ' Dessert/Ice ');
INSERT INTO Style( ID , NAME ) VALUES( 9 , ' Dessert/Aromatized ');
INSERT INTO Style( ID , NAME ) VALUES( 10 , ' Dessert/Fruit ');
INSERT INTO Style( ID , NAME ) VALUES( 11 , ' Dessert/Noble rot ');
INSERT INTO Style( ID , NAME ) VALUES( 12 , ' Dessert/Straw ');
INSERT INTO Style( ID , NAME ) VALUES( 13 , ' Other ');
INSERT INTO Style( ID , NAME ) VALUES( 14 , ' Other/Table ');
INSERT INTO Style( ID , NAME ) VALUES( 15 , ' Other/Natural ');
INSERT INTO Style( ID , NAME ) VALUES( 16 , ' Other/Biodynamic ');
INSERT INTO Style( ID , NAME ) VALUES( 17 , ' Other/Organic ');
INSERT INTO Style( ID , NAME ) VALUES( 18 , ' Other/Kosher ');
