INSERT IGNORE INTO Variety(id, name) VALUES(1, "Abouriou");
INSERT IGNORE INTO Variety(id, name) VALUES(2, "Abrustine");
INSERT IGNORE INTO Variety(id, name) VALUES(3, "Absinthe");
INSERT IGNORE INTO Variety(id, name) VALUES(4, "Acadie Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(5, "Acolon");
INSERT IGNORE INTO Variety(id, name) VALUES(6, "Agave Spirit");
INSERT IGNORE INTO Variety(id, name) VALUES(7, "Agiorgitiko");
INSERT IGNORE INTO Variety(id, name) VALUES(8, "Aglianico");
INSERT IGNORE INTO Variety(id, name) VALUES(9, "Aglianico - Piedirosso");
INSERT IGNORE INTO Variety(id, name) VALUES(10, "Ahmeur bou Ahmeur");
INSERT IGNORE INTO Variety(id, name) VALUES(11, "Aidani");
INSERT IGNORE INTO Variety(id, name) VALUES(12, "Airen");
INSERT IGNORE INTO Variety(id, name) VALUES(13, "Aladasturi");
INSERT IGNORE INTO Variety(id, name) VALUES(14, "Alarijen");
INSERT IGNORE INTO Variety(id, name) VALUES(15, "Albalonga");
INSERT IGNORE INTO Variety(id, name) VALUES(16, "Albana");
INSERT IGNORE INTO Variety(id, name) VALUES(17, "Albanella");
INSERT IGNORE INTO Variety(id, name) VALUES(18, "Albarello Blanca");
INSERT IGNORE INTO Variety(id, name) VALUES(19, "Albarin Blanco");
INSERT IGNORE INTO Variety(id, name) VALUES(20, "Albarino (Alvarinho)");
INSERT IGNORE INTO Variety(id, name) VALUES(21, "Albarola");
INSERT IGNORE INTO Variety(id, name) VALUES(22, "Albarola - Bosco - Vermentino");
INSERT IGNORE INTO Variety(id, name) VALUES(23, "Albarossa");
INSERT IGNORE INTO Variety(id, name) VALUES(24, "Albillo");
INSERT IGNORE INTO Variety(id, name) VALUES(25, "Albillo Krimskii (Rachuli Tetra)");
INSERT IGNORE INTO Variety(id, name) VALUES(26, "Alcohol-Free");
INSERT IGNORE INTO Variety(id, name) VALUES(27, "Aleatico");
INSERT IGNORE INTO Variety(id, name) VALUES(28, "Alexandrouli");
INSERT IGNORE INTO Variety(id, name) VALUES(29, "Alfrocheiro Preto");
INSERT IGNORE INTO Variety(id, name) VALUES(30, "Alfrocheiro Preto - Tinta Roriz - Touriga");
INSERT IGNORE INTO Variety(id, name) VALUES(31, "Alfrocheiro Preto - Touriga");
INSERT IGNORE INTO Variety(id, name) VALUES(32, "Alibernet");
INSERT IGNORE INTO Variety(id, name) VALUES(33, "Alicante Bouschet");
INSERT IGNORE INTO Variety(id, name) VALUES(34, "Alicante Bouschet - Aragonez");
INSERT IGNORE INTO Variety(id, name) VALUES(35, "Alicante Bouschet - Aragonez - Trincadeira");
INSERT IGNORE INTO Variety(id, name) VALUES(36, "Alicante Bouschet - Touriga");
INSERT IGNORE INTO Variety(id, name) VALUES(37, "Alicante Ganzin");
INSERT IGNORE INTO Variety(id, name) VALUES(38, "Aligote");
INSERT IGNORE INTO Variety(id, name) VALUES(39, "Alphonse Lavallee");
INSERT IGNORE INTO Variety(id, name) VALUES(40, "Altesse");
INSERT IGNORE INTO Variety(id, name) VALUES(41, "Alvarelhao");
INSERT IGNORE INTO Variety(id, name) VALUES(42, "Amigne");
INSERT IGNORE INTO Variety(id, name) VALUES(43, "Ancellotta");
INSERT IGNORE INTO Variety(id, name) VALUES(44, "Andre");
INSERT IGNORE INTO Variety(id, name) VALUES(45, "Antao Vaz");
INSERT IGNORE INTO Variety(id, name) VALUES(46, "Antao Vaz - Arinto (Pederna)");
INSERT IGNORE INTO Variety(id, name) VALUES(47, "Aragonez (Tinta Roriz) - Castelao");
INSERT IGNORE INTO Variety(id, name) VALUES(48, "Aramon");
INSERT IGNORE INTO Variety(id, name) VALUES(49, "Aranel");
INSERT IGNORE INTO Variety(id, name) VALUES(50, "Arany Sarfeher");
INSERT IGNORE INTO Variety(id, name) VALUES(51, "Arbane");
INSERT IGNORE INTO Variety(id, name) VALUES(52, "Arbois");
INSERT IGNORE INTO Variety(id, name) VALUES(53, "Areni Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(54, "Argaman");
INSERT IGNORE INTO Variety(id, name) VALUES(55, "Argant");
INSERT IGNORE INTO Variety(id, name) VALUES(56, "Arinarnoa");
INSERT IGNORE INTO Variety(id, name) VALUES(57, "Arinto (Pederna)");
INSERT IGNORE INTO Variety(id, name) VALUES(58, "Arinto (Pederna) - Fernao Pires");
INSERT IGNORE INTO Variety(id, name) VALUES(59, "Arinto (Pederna) - Loureiro");
INSERT IGNORE INTO Variety(id, name) VALUES(60, "Arneis");
INSERT IGNORE INTO Variety(id, name) VALUES(61, "Arriloba");
INSERT IGNORE INTO Variety(id, name) VALUES(62, "Arrufiac");
INSERT IGNORE INTO Variety(id, name) VALUES(63, "Aspiran");
INSERT IGNORE INTO Variety(id, name) VALUES(64, "Assyrtiko");
INSERT IGNORE INTO Variety(id, name) VALUES(65, "Athiri");
INSERT IGNORE INTO Variety(id, name) VALUES(66, "Aubin Vert");
INSERT IGNORE INTO Variety(id, name) VALUES(67, "Aubun");
INSERT IGNORE INTO Variety(id, name) VALUES(68, "Aurore");
INSERT IGNORE INTO Variety(id, name) VALUES(69, "Auxerrois");
INSERT IGNORE INTO Variety(id, name) VALUES(70, "Avana");
INSERT IGNORE INTO Variety(id, name) VALUES(71, "Avarengo");
INSERT IGNORE INTO Variety(id, name) VALUES(72, "Avesso");
INSERT IGNORE INTO Variety(id, name) VALUES(73, "Avgoustiatis");
INSERT IGNORE INTO Variety(id, name) VALUES(74, "Awamori");
INSERT IGNORE INTO Variety(id, name) VALUES(75, "Azal Branco");
INSERT IGNORE INTO Variety(id, name) VALUES(76, "Azal Tinto");
INSERT IGNORE INTO Variety(id, name) VALUES(77, "Babeasca Neagra");
INSERT IGNORE INTO Variety(id, name) VALUES(78, "Babic");
INSERT IGNORE INTO Variety(id, name) VALUES(79, "Bacchus");
INSERT IGNORE INTO Variety(id, name) VALUES(80, "Bachet");
INSERT IGNORE INTO Variety(id, name) VALUES(81, "Baco Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(82, "Baco Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(83, "Baga");
INSERT IGNORE INTO Variety(id, name) VALUES(84, "Baijiu");
INSERT IGNORE INTO Variety(id, name) VALUES(85, "Baltica");
INSERT IGNORE INTO Variety(id, name) VALUES(86, "Barbarossa");
INSERT IGNORE INTO Variety(id, name) VALUES(87, "Barbera");
INSERT IGNORE INTO Variety(id, name) VALUES(88, "Barbera - Bonarda (Croatina)");
INSERT IGNORE INTO Variety(id, name) VALUES(89, "Barbera - Dolcetto - Nebbiolo");
INSERT IGNORE INTO Variety(id, name) VALUES(90, "Barbera - Nebbiolo");
INSERT IGNORE INTO Variety(id, name) VALUES(91, "Barbera - Sangiovese");
INSERT IGNORE INTO Variety(id, name) VALUES(92, "Baroque");
INSERT IGNORE INTO Variety(id, name) VALUES(93, "Barsaglina");
INSERT IGNORE INTO Variety(id, name) VALUES(94, "Batiki");
INSERT IGNORE INTO Variety(id, name) VALUES(95, "Beaunoir");
INSERT IGNORE INTO Variety(id, name) VALUES(96, "Beer");
INSERT IGNORE INTO Variety(id, name) VALUES(97, "Bellone Bianco");
INSERT IGNORE INTO Variety(id, name) VALUES(98, "Bequignol");
INSERT IGNORE INTO Variety(id, name) VALUES(99, "Bervedino");
INSERT IGNORE INTO Variety(id, name) VALUES(100, "Bianchello (Biancame)");
INSERT IGNORE INTO Variety(id, name) VALUES(101, "Bianchetta Genovese");
INSERT IGNORE INTO Variety(id, name) VALUES(102, "Bianco d'Alessano");
INSERT IGNORE INTO Variety(id, name) VALUES(103, "Bianco d'Alessano - Verdeca");
INSERT IGNORE INTO Variety(id, name) VALUES(104, "Biancolella");
INSERT IGNORE INTO Variety(id, name) VALUES(105, "Biancone");
INSERT IGNORE INTO Variety(id, name) VALUES(106, "Biancu Gentile");
INSERT IGNORE INTO Variety(id, name) VALUES(107, "Bical");
INSERT IGNORE INTO Variety(id, name) VALUES(108, "Bigolona");
INSERT IGNORE INTO Variety(id, name) VALUES(109, "Bitters");
INSERT IGNORE INTO Variety(id, name) VALUES(110, "Black Monukka");
INSERT IGNORE INTO Variety(id, name) VALUES(111, "Black Spanish (Lenoir)");
INSERT IGNORE INTO Variety(id, name) VALUES(112, "Blanc du Bois");
INSERT IGNORE INTO Variety(id, name) VALUES(113, "Blanqueiron");
INSERT IGNORE INTO Variety(id, name) VALUES(114, "Blatina");
INSERT IGNORE INTO Variety(id, name) VALUES(115, "Blauburger");
INSERT IGNORE INTO Variety(id, name) VALUES(116, "Blauer Wildbacher");
INSERT IGNORE INTO Variety(id, name) VALUES(117, "Blaufrankisch - Cabernet");
INSERT IGNORE INTO Variety(id, name) VALUES(118, "Blaufrankisch - Cabernet - Merlot");
INSERT IGNORE INTO Variety(id, name) VALUES(119, "Blaufrankisch (Lemberger)");
INSERT IGNORE INTO Variety(id, name) VALUES(120, "Blaufrankisch - Zweigelt");
INSERT IGNORE INTO Variety(id, name) VALUES(121, "Bobal");
INSERT IGNORE INTO Variety(id, name) VALUES(122, "Bobal Blanco");
INSERT IGNORE INTO Variety(id, name) VALUES(123, "Bogazkere");
INSERT IGNORE INTO Variety(id, name) VALUES(124, "Bogazkere - Okuzgozu");
INSERT IGNORE INTO Variety(id, name) VALUES(125, "Bogdanusa");
INSERT IGNORE INTO Variety(id, name) VALUES(126, "Bombino Bianco");
INSERT IGNORE INTO Variety(id, name) VALUES(127, "Bombino Nero");
INSERT IGNORE INTO Variety(id, name) VALUES(128, "Bonarda - Malbec");
INSERT IGNORE INTO Variety(id, name) VALUES(129, "Bonarda Piemontese");
INSERT IGNORE INTO Variety(id, name) VALUES(130, "Bondola");
INSERT IGNORE INTO Variety(id, name) VALUES(131, "Bordeaux Blend Red");
INSERT IGNORE INTO Variety(id, name) VALUES(132, "Bordeaux Blend White");
INSERT IGNORE INTO Variety(id, name) VALUES(133, "Bosco");
INSERT IGNORE INTO Variety(id, name) VALUES(134, "Bourboulenc");
INSERT IGNORE INTO Variety(id, name) VALUES(135, "Bouvier");
INSERT IGNORE INTO Variety(id, name) VALUES(136, "Brachetto");
INSERT IGNORE INTO Variety(id, name) VALUES(137, "Brandy");
INSERT IGNORE INTO Variety(id, name) VALUES(138, "Braquet");
INSERT IGNORE INTO Variety(id, name) VALUES(139, "Brauner Veltliner");
INSERT IGNORE INTO Variety(id, name) VALUES(140, "Brianna");
INSERT IGNORE INTO Variety(id, name) VALUES(141, "Bronner");
INSERT IGNORE INTO Variety(id, name) VALUES(142, "Bronx");
INSERT IGNORE INTO Variety(id, name) VALUES(143, "Brunal");
INSERT IGNORE INTO Variety(id, name) VALUES(144, "Brun Fourca");
INSERT IGNORE INTO Variety(id, name) VALUES(145, "Bual (Malvasia Fina)");
INSERT IGNORE INTO Variety(id, name) VALUES(146, "Bukettraube");
INSERT IGNORE INTO Variety(id, name) VALUES(147, "Burger");
INSERT IGNORE INTO Variety(id, name) VALUES(148, "Cabernet Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(149, "Cabernet - Carignan - Grenache");
INSERT IGNORE INTO Variety(id, name) VALUES(150, "Cabernet - Carignan - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(151, "Cabernet Cubin");
INSERT IGNORE INTO Variety(id, name) VALUES(152, "Cabernet Dorio");
INSERT IGNORE INTO Variety(id, name) VALUES(153, "Cabernet Dorsa");
INSERT IGNORE INTO Variety(id, name) VALUES(154, "Cabernet Franc");
INSERT IGNORE INTO Variety(id, name) VALUES(155, "Cabernet Franc - Cabernet Sauvignon");
INSERT IGNORE INTO Variety(id, name) VALUES(156, "Cabernet Franc - Gamay");
INSERT IGNORE INTO Variety(id, name) VALUES(157, "Cabernet Franc - Malbec");
INSERT IGNORE INTO Variety(id, name) VALUES(158, "Cabernet Franc - Merlot");
INSERT IGNORE INTO Variety(id, name) VALUES(159, "Cabernet Franc - Pinot Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(160, "Cabernet Gernischt");
INSERT IGNORE INTO Variety(id, name) VALUES(161, "Cabernet - Grenache - Merlot - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(162, "Cabernet - Grenache - Mourvedre - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(163, "Cabernet - Grenache - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(164, "Cabernet Jura");
INSERT IGNORE INTO Variety(id, name) VALUES(165, "Cabernet - Malbec - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(166, "Cabernet - Merlot - Montepulciano");
INSERT IGNORE INTO Variety(id, name) VALUES(167, "Cabernet - Merlot - Sangiovese");
INSERT IGNORE INTO Variety(id, name) VALUES(168, "Cabernet - Merlot - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(169, "Cabernet - Merlot - Tempranillo");
INSERT IGNORE INTO Variety(id, name) VALUES(170, "Cabernet - Merlot - Zinfandel");
INSERT IGNORE INTO Variety(id, name) VALUES(171, "Cabernet - Merlot - Zweigelt");
INSERT IGNORE INTO Variety(id, name) VALUES(172, "Cabernet Mitos");
INSERT IGNORE INTO Variety(id, name) VALUES(173, "Cabernet - Montepulciano");
INSERT IGNORE INTO Variety(id, name) VALUES(174, "Cabernet Moravia");
INSERT IGNORE INTO Variety(id, name) VALUES(175, "Cabernet - Mourvedre - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(176, "Cabernet - Nero d'Avola");
INSERT IGNORE INTO Variety(id, name) VALUES(177, "Cabernet - Petit Verdot");
INSERT IGNORE INTO Variety(id, name) VALUES(178, "Cabernet Pfeffer");
INSERT IGNORE INTO Variety(id, name) VALUES(179, "Cabernet - Pinotage");
INSERT IGNORE INTO Variety(id, name) VALUES(180, "Cabernet - Sangiovese");
INSERT IGNORE INTO Variety(id, name) VALUES(181, "Cabernet - Sangiovese - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(182, "Cabernet Sauvignon");
INSERT IGNORE INTO Variety(id, name) VALUES(183, "Cabernet Sauvignon - Carignan");
INSERT IGNORE INTO Variety(id, name) VALUES(184, "Cabernet Sauvignon - Carmenere");
INSERT IGNORE INTO Variety(id, name) VALUES(185, "Cabernet Sauvignon - Cinsaut");
INSERT IGNORE INTO Variety(id, name) VALUES(186, "Cabernet Sauvignon - Malbec");
INSERT IGNORE INTO Variety(id, name) VALUES(187, "Cabernet Sauvignon - Merlot");
INSERT IGNORE INTO Variety(id, name) VALUES(188, "Cabernet Sauvignon - Pinot Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(189, "Cabernets - Grolleau");
INSERT IGNORE INTO Variety(id, name) VALUES(190, "Cabernet - Syrah/Shiraz");
INSERT IGNORE INTO Variety(id, name) VALUES(191, "Cabernet - Syrah - Tempranillo");
INSERT IGNORE INTO Variety(id, name) VALUES(192, "Cabernet - Syrah - Zinfandel");
INSERT IGNORE INTO Variety(id, name) VALUES(193, "Cabernet - Tannat");
INSERT IGNORE INTO Variety(id, name) VALUES(194, "Cabernet - Tempranillo");
INSERT IGNORE INTO Variety(id, name) VALUES(195, "Cabernet - Zinfandel");
INSERT IGNORE INTO Variety(id, name) VALUES(196, "Cab Franc - Gamay - Malbec");
INSERT IGNORE INTO Variety(id, name) VALUES(197, "Cachaca");
INSERT IGNORE INTO Variety(id, name) VALUES(198, "Cagnulari");
INSERT IGNORE INTO Variety(id, name) VALUES(199, "Caino Tinto");
INSERT IGNORE INTO Variety(id, name) VALUES(200, "Caladoc");
INSERT IGNORE INTO Variety(id, name) VALUES(201, "Calbanesco");
INSERT IGNORE INTO Variety(id, name) VALUES(202, "Calitor");
INSERT IGNORE INTO Variety(id, name) VALUES(203, "Cal Karasi");
INSERT IGNORE INTO Variety(id, name) VALUES(204, "Callet");
INSERT IGNORE INTO Variety(id, name) VALUES(205, "Calzin");
INSERT IGNORE INTO Variety(id, name) VALUES(206, "Camaralet de Lasseube");
INSERT IGNORE INTO Variety(id, name) VALUES(207, "Camarate");
INSERT IGNORE INTO Variety(id, name) VALUES(208, "Canaiolo");
INSERT IGNORE INTO Variety(id, name) VALUES(209, "Canaiolo Bianco");
INSERT IGNORE INTO Variety(id, name) VALUES(210, "Cannabis Drink");
INSERT IGNORE INTO Variety(id, name) VALUES(211, "Canocazo");
INSERT IGNORE INTO Variety(id, name) VALUES(212, "Carcajolo Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(213, "Carcajolo Nero");
INSERT IGNORE INTO Variety(id, name) VALUES(214, "Caricalasino");
INSERT IGNORE INTO Variety(id, name) VALUES(215, "Carignan Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(216, "Carignan (Carinena)");
INSERT IGNORE INTO Variety(id, name) VALUES(217, "Carignan - Grenache - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(218, "Carignan - Grenache - Tempranillo");
INSERT IGNORE INTO Variety(id, name) VALUES(219, "Carignan Gris");
INSERT IGNORE INTO Variety(id, name) VALUES(220, "Carignan - Merlot");
INSERT IGNORE INTO Variety(id, name) VALUES(221, "Carignan - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(222, "Carinena - Garnacha");
INSERT IGNORE INTO Variety(id, name) VALUES(223, "Carmenere");
INSERT IGNORE INTO Variety(id, name) VALUES(224, "Carmenere - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(225, "Carmine");
INSERT IGNORE INTO Variety(id, name) VALUES(226, "Carminoir");
INSERT IGNORE INTO Variety(id, name) VALUES(227, "Carnelian");
INSERT IGNORE INTO Variety(id, name) VALUES(228, "Carrasquin");
INSERT IGNORE INTO Variety(id, name) VALUES(229, "Carricante");
INSERT IGNORE INTO Variety(id, name) VALUES(230, "Carricante - Catarratto");
INSERT IGNORE INTO Variety(id, name) VALUES(231, "Casavecchia");
INSERT IGNORE INTO Variety(id, name) VALUES(232, "Casetta");
INSERT IGNORE INTO Variety(id, name) VALUES(233, "Cassady");
INSERT IGNORE INTO Variety(id, name) VALUES(234, "Castelao");
INSERT IGNORE INTO Variety(id, name) VALUES(235, "Castelao - Touriga");
INSERT IGNORE INTO Variety(id, name) VALUES(236, "Catarratto");
INSERT IGNORE INTO Variety(id, name) VALUES(237, "Catarratto - Chardonnay");
INSERT IGNORE INTO Variety(id, name) VALUES(238, "Catarratto - Grillo - Inzolia");
INSERT IGNORE INTO Variety(id, name) VALUES(239, "Catarratto - Inzolia");
INSERT IGNORE INTO Variety(id, name) VALUES(240, "Catawba");
INSERT IGNORE INTO Variety(id, name) VALUES(241, "Cava Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(242, "Cayetana");
INSERT IGNORE INTO Variety(id, name) VALUES(243, "Cayuga");
INSERT IGNORE INTO Variety(id, name) VALUES(244, "Cecubo");
INSERT IGNORE INTO Variety(id, name) VALUES(245, "Centesimino (Savignon Rosso)");
INSERT IGNORE INTO Variety(id, name) VALUES(246, "Centurion");
INSERT IGNORE INTO Variety(id, name) VALUES(247, "Cerceal");
INSERT IGNORE INTO Variety(id, name) VALUES(248, "Cereza");
INSERT IGNORE INTO Variety(id, name) VALUES(249, "Cesanese");
INSERT IGNORE INTO Variety(id, name) VALUES(250, "Cesar");
INSERT IGNORE INTO Variety(id, name) VALUES(251, "Cetinka");
INSERT IGNORE INTO Variety(id, name) VALUES(252, "Chambourcin");
INSERT IGNORE INTO Variety(id, name) VALUES(253, "Champagne Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(254, "Chancellor");
INSERT IGNORE INTO Variety(id, name) VALUES(255, "Charbono (Bonarda)");
INSERT IGNORE INTO Variety(id, name) VALUES(256, "Chardonel");
INSERT IGNORE INTO Variety(id, name) VALUES(257, "Chardonnay");
INSERT IGNORE INTO Variety(id, name) VALUES(258, "Chardonnay - Chenin Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(259, "Chardonnay - Colombard");
INSERT IGNORE INTO Variety(id, name) VALUES(260, "Chardonnay - Garganega");
INSERT IGNORE INTO Variety(id, name) VALUES(261, "Chardonnay - Gewurztraminer");
INSERT IGNORE INTO Variety(id, name) VALUES(262, "Chardonnay - Muscat");
INSERT IGNORE INTO Variety(id, name) VALUES(263, "Chardonnay Musque");
INSERT IGNORE INTO Variety(id, name) VALUES(264, "Chardonnay - Pinot Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(265, "Chardonnay - Pinot Blanc - Pinot Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(266, "Chardonnay - Pinot Gris");
INSERT IGNORE INTO Variety(id, name) VALUES(267, "Chardonnay - Pinot Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(268, "Chardonnay - Riesling");
INSERT IGNORE INTO Variety(id, name) VALUES(269, "Chardonnay Rose");
INSERT IGNORE INTO Variety(id, name) VALUES(270, "Chardonnay - Roussanne");
INSERT IGNORE INTO Variety(id, name) VALUES(271, "Chardonnay - Roussanne - Viognier");
INSERT IGNORE INTO Variety(id, name) VALUES(272, "Chardonnay - Sauvignon Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(273, "Chardonnay - Sauvignon - Semillon");
INSERT IGNORE INTO Variety(id, name) VALUES(274, "Chardonnay - Savagnin");
INSERT IGNORE INTO Variety(id, name) VALUES(275, "Chardonnay - Semillon");
INSERT IGNORE INTO Variety(id, name) VALUES(276, "Chardonnay - Torrontes");
INSERT IGNORE INTO Variety(id, name) VALUES(277, "Chardonnay - Verdelho");
INSERT IGNORE INTO Variety(id, name) VALUES(278, "Chardonnay - Vermentino");
INSERT IGNORE INTO Variety(id, name) VALUES(279, "Chardonnay - Viognier");
INSERT IGNORE INTO Variety(id, name) VALUES(280, "Chardonnay - Viura");
INSERT IGNORE INTO Variety(id, name) VALUES(281, "Chardonnay - Xarel-lo");
INSERT IGNORE INTO Variety(id, name) VALUES(282, "Charmont");
INSERT IGNORE INTO Variety(id, name) VALUES(283, "Chasan");
INSERT IGNORE INTO Variety(id, name) VALUES(284, "Chasselas");
INSERT IGNORE INTO Variety(id, name) VALUES(285, "Chelois");
INSERT IGNORE INTO Variety(id, name) VALUES(286, "Chenanson");
INSERT IGNORE INTO Variety(id, name) VALUES(287, "Chenel");
INSERT IGNORE INTO Variety(id, name) VALUES(288, "Chenin Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(289, "Chianti Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(290, "Cider");
INSERT IGNORE INTO Variety(id, name) VALUES(291, "Cienna");
INSERT IGNORE INTO Variety(id, name) VALUES(292, "Ciliegiolo");
INSERT IGNORE INTO Variety(id, name) VALUES(293, "Cinsaut");
INSERT IGNORE INTO Variety(id, name) VALUES(294, "Cinsaut - Grenache");
INSERT IGNORE INTO Variety(id, name) VALUES(295, "Cinsaut - Grenache - Mourvedre");
INSERT IGNORE INTO Variety(id, name) VALUES(296, "Cinsaut - Grenache - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(297, "Cinsaut - Mourvedre");
INSERT IGNORE INTO Variety(id, name) VALUES(298, "Cinsaut - Mourvedre - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(299, "Cinsaut - Pinotage");
INSERT IGNORE INTO Variety(id, name) VALUES(300, "Cinsaut - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(301, "Cividino");
INSERT IGNORE INTO Variety(id, name) VALUES(302, "Clairette");
INSERT IGNORE INTO Variety(id, name) VALUES(303, "Clairette - Marsanne");
INSERT IGNORE INTO Variety(id, name) VALUES(304, "Clairette - Marsanne - Ugni");
INSERT IGNORE INTO Variety(id, name) VALUES(305, "Clairette - Muscat");
INSERT IGNORE INTO Variety(id, name) VALUES(306, "Clairette - Rolle");
INSERT IGNORE INTO Variety(id, name) VALUES(307, "Clairette - Ugni Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(308, "Claret de Gers");
INSERT IGNORE INTO Variety(id, name) VALUES(309, "Clinton");
INSERT IGNORE INTO Variety(id, name) VALUES(310, "Cococciola");
INSERT IGNORE INTO Variety(id, name) VALUES(311, "Coda di Volpe");
INSERT IGNORE INTO Variety(id, name) VALUES(312, "Codega do Larinho");
INSERT IGNORE INTO Variety(id, name) VALUES(313, "Colombard");
INSERT IGNORE INTO Variety(id, name) VALUES(314, "Colombard - Folle - Ugni");
INSERT IGNORE INTO Variety(id, name) VALUES(315, "Colombard - Ugni Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(316, "Colorino");
INSERT IGNORE INTO Variety(id, name) VALUES(317, "Completer");
INSERT IGNORE INTO Variety(id, name) VALUES(318, "Concord");
INSERT IGNORE INTO Variety(id, name) VALUES(319, "Corinto Nero");
INSERT IGNORE INTO Variety(id, name) VALUES(320, "Cornalin");
INSERT IGNORE INTO Variety(id, name) VALUES(321, "Cornifesto");
INSERT IGNORE INTO Variety(id, name) VALUES(322, "Corot Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(323, "Cortese");
INSERT IGNORE INTO Variety(id, name) VALUES(324, "Corvina");
INSERT IGNORE INTO Variety(id, name) VALUES(325, "Corvina - Rondinella");
INSERT IGNORE INTO Variety(id, name) VALUES(326, "Corvinone");
INSERT IGNORE INTO Variety(id, name) VALUES(327, "Couderc Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(328, "Counoise");
INSERT IGNORE INTO Variety(id, name) VALUES(329, "Courbu Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(330, "Criolla Grande");
INSERT IGNORE INTO Variety(id, name) VALUES(331, "Croatina");
INSERT IGNORE INTO Variety(id, name) VALUES(332, "Crouchen (Cape Riesling)");
INSERT IGNORE INTO Variety(id, name) VALUES(333, "Crovino");
INSERT IGNORE INTO Variety(id, name) VALUES(334, "Cserszegi Fuszeres");
INSERT IGNORE INTO Variety(id, name) VALUES(335, "Cygne Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(336, "Cyser");
INSERT IGNORE INTO Variety(id, name) VALUES(337, "Dafni");
INSERT IGNORE INTO Variety(id, name) VALUES(338, "Damaschino");
INSERT IGNORE INTO Variety(id, name) VALUES(339, "Dameron");
INSERT IGNORE INTO Variety(id, name) VALUES(340, "Darnekusa");
INSERT IGNORE INTO Variety(id, name) VALUES(341, "Debina");
INSERT IGNORE INTO Variety(id, name) VALUES(342, "Debit");
INSERT IGNORE INTO Variety(id, name) VALUES(343, "De Chaunac");
INSERT IGNORE INTO Variety(id, name) VALUES(344, "Delaware");
INSERT IGNORE INTO Variety(id, name) VALUES(345, "Diamond");
INSERT IGNORE INTO Variety(id, name) VALUES(346, "Dimiat");
INSERT IGNORE INTO Variety(id, name) VALUES(347, "Dindarella");
INSERT IGNORE INTO Variety(id, name) VALUES(348, "Diolinoir");
INSERT IGNORE INTO Variety(id, name) VALUES(349, "Dobricic");
INSERT IGNORE INTO Variety(id, name) VALUES(350, "Dolcetto");
INSERT IGNORE INTO Variety(id, name) VALUES(351, "Domina");
INSERT IGNORE INTO Variety(id, name) VALUES(352, "Dona Blanca");
INSERT IGNORE INTO Variety(id, name) VALUES(353, "Donzelinho Branco");
INSERT IGNORE INTO Variety(id, name) VALUES(354, "Doral");
INSERT IGNORE INTO Variety(id, name) VALUES(355, "Dornfelder");
INSERT IGNORE INTO Variety(id, name) VALUES(356, "Dorona di Venezia");
INSERT IGNORE INTO Variety(id, name) VALUES(357, "Doux d'Henry");
INSERT IGNORE INTO Variety(id, name) VALUES(358, "Drink Mixer");
INSERT IGNORE INTO Variety(id, name) VALUES(359, "Dunkelfelder");
INSERT IGNORE INTO Variety(id, name) VALUES(360, "Duras");
INSERT IGNORE INTO Variety(id, name) VALUES(361, "Duras - Fer Servadou");
INSERT IGNORE INTO Variety(id, name) VALUES(362, "Duras - Fer - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(363, "Duras - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(364, "Durella");
INSERT IGNORE INTO Variety(id, name) VALUES(365, "Durif - Shiraz");
INSERT IGNORE INTO Variety(id, name) VALUES(366, "Durize");
INSERT IGNORE INTO Variety(id, name) VALUES(367, "Dzvelshava");
INSERT IGNORE INTO Variety(id, name) VALUES(368, "Early Muscat");
INSERT IGNORE INTO Variety(id, name) VALUES(369, "Eau-de-Vie");
INSERT IGNORE INTO Variety(id, name) VALUES(370, "Edelweiss");
INSERT IGNORE INTO Variety(id, name) VALUES(371, "Edelzwicker Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(372, "Egiodola");
INSERT IGNORE INTO Variety(id, name) VALUES(373, "Ehrenfelser");
INSERT IGNORE INTO Variety(id, name) VALUES(374, "Elbling");
INSERT IGNORE INTO Variety(id, name) VALUES(375, "Elvira");
INSERT IGNORE INTO Variety(id, name) VALUES(376, "Emerald Riesling");
INSERT IGNORE INTO Variety(id, name) VALUES(377, "Emir");
INSERT IGNORE INTO Variety(id, name) VALUES(378, "Enantio");
INSERT IGNORE INTO Variety(id, name) VALUES(379, "Encruzado");
INSERT IGNORE INTO Variety(id, name) VALUES(380, "Erbaluce");
INSERT IGNORE INTO Variety(id, name) VALUES(381, "Espadeiro");
INSERT IGNORE INTO Variety(id, name) VALUES(382, "Etraire de l'Adui");
INSERT IGNORE INTO Variety(id, name) VALUES(383, "Eyholzer");
INSERT IGNORE INTO Variety(id, name) VALUES(384, "Ezerjo");
INSERT IGNORE INTO Variety(id, name) VALUES(385, "Faber");
INSERT IGNORE INTO Variety(id, name) VALUES(386, "Falanghina");
INSERT IGNORE INTO Variety(id, name) VALUES(387, "Fernao Pires");
INSERT IGNORE INTO Variety(id, name) VALUES(388, "Fer Servadou");
INSERT IGNORE INTO Variety(id, name) VALUES(389, "Feteasca Alba");
INSERT IGNORE INTO Variety(id, name) VALUES(390, "Feteasca Neagra");
INSERT IGNORE INTO Variety(id, name) VALUES(391, "Feteasca Regala");
INSERT IGNORE INTO Variety(id, name) VALUES(392, "Fiano");
INSERT IGNORE INTO Variety(id, name) VALUES(393, "Findling");
INSERT IGNORE INTO Variety(id, name) VALUES(394, "Flavored - Spiced - Fruit Wine");
INSERT IGNORE INTO Variety(id, name) VALUES(395, "Flora");
INSERT IGNORE INTO Variety(id, name) VALUES(396, "Florental");
INSERT IGNORE INTO Variety(id, name) VALUES(397, "Foglia Tonda");
INSERT IGNORE INTO Variety(id, name) VALUES(398, "Fogoneu");
INSERT IGNORE INTO Variety(id, name) VALUES(399, "Folgasao");
INSERT IGNORE INTO Variety(id, name) VALUES(400, "Folle Blanche");
INSERT IGNORE INTO Variety(id, name) VALUES(401, "Forastera");
INSERT IGNORE INTO Variety(id, name) VALUES(402, "Fortana");
INSERT IGNORE INTO Variety(id, name) VALUES(403, "Francavilla");
INSERT IGNORE INTO Variety(id, name) VALUES(404, "Franc Noir de la Haute-Saone");
INSERT IGNORE INTO Variety(id, name) VALUES(405, "Francusa");
INSERT IGNORE INTO Variety(id, name) VALUES(406, "Frappato");
INSERT IGNORE INTO Variety(id, name) VALUES(407, "Frappato - Nero d'Avola");
INSERT IGNORE INTO Variety(id, name) VALUES(408, "Freisa");
INSERT IGNORE INTO Variety(id, name) VALUES(409, "Freisamer");
INSERT IGNORE INTO Variety(id, name) VALUES(410, "Friulano");
INSERT IGNORE INTO Variety(id, name) VALUES(411, "Frontenac");
INSERT IGNORE INTO Variety(id, name) VALUES(412, "Frontenac Gris");
INSERT IGNORE INTO Variety(id, name) VALUES(413, "Fruhburgunder");
INSERT IGNORE INTO Variety(id, name) VALUES(414, "Fruhroter Veltliner");
INSERT IGNORE INTO Variety(id, name) VALUES(415, "Fumin");
INSERT IGNORE INTO Variety(id, name) VALUES(416, "Furmint");
INSERT IGNORE INTO Variety(id, name) VALUES(417, "Gaglioppo");
INSERT IGNORE INTO Variety(id, name) VALUES(418, "Gaidoura");
INSERT IGNORE INTO Variety(id, name) VALUES(419, "Gamaret");
INSERT IGNORE INTO Variety(id, name) VALUES(420, "Gamaret - Garanoir");
INSERT IGNORE INTO Variety(id, name) VALUES(421, "Gamaret - Garanoir - Pinot Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(422, "Gamay");
INSERT IGNORE INTO Variety(id, name) VALUES(423, "Gamay - Grolleau Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(424, "Gamay - Pinot Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(425, "Gamay - Poulsard");
INSERT IGNORE INTO Variety(id, name) VALUES(426, "Gamba di Pernice");
INSERT IGNORE INTO Variety(id, name) VALUES(427, "Garanoir");
INSERT IGNORE INTO Variety(id, name) VALUES(428, "Garganega");
INSERT IGNORE INTO Variety(id, name) VALUES(429, "Garganega - Pinot Grigio");
INSERT IGNORE INTO Variety(id, name) VALUES(430, "Garnacha - Tempranillo");
INSERT IGNORE INTO Variety(id, name) VALUES(431, "Garrido");
INSERT IGNORE INTO Variety(id, name) VALUES(432, "Gellewza");
INSERT IGNORE INTO Variety(id, name) VALUES(433, "Genever (Jenever)");
INSERT IGNORE INTO Variety(id, name) VALUES(434, "Gewurztraminer");
INSERT IGNORE INTO Variety(id, name) VALUES(435, "Gewurztraminer - Riesling");
INSERT IGNORE INTO Variety(id, name) VALUES(436, "Gin");
INSERT IGNORE INTO Variety(id, name) VALUES(437, "Gin Liqueur");
INSERT IGNORE INTO Variety(id, name) VALUES(438, "Girgentina");
INSERT IGNORE INTO Variety(id, name) VALUES(439, "Giro");
INSERT IGNORE INTO Variety(id, name) VALUES(440, "Glera (Prosecco)");
INSERT IGNORE INTO Variety(id, name) VALUES(441, "Godello");
INSERT IGNORE INTO Variety(id, name) VALUES(442, "Goldburger");
INSERT IGNORE INTO Variety(id, name) VALUES(443, "Goldriesling");
INSERT IGNORE INTO Variety(id, name) VALUES(444, "Gouais Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(445, "Gouveio");
INSERT IGNORE INTO Variety(id, name) VALUES(446, "Graciano");
INSERT IGNORE INTO Variety(id, name) VALUES(447, "Grappa");
INSERT IGNORE INTO Variety(id, name) VALUES(448, "Grechetto");
INSERT IGNORE INTO Variety(id, name) VALUES(449, "Grechetto Rosso");
INSERT IGNORE INTO Variety(id, name) VALUES(450, "Greco");
INSERT IGNORE INTO Variety(id, name) VALUES(451, "Greco Bianco");
INSERT IGNORE INTO Variety(id, name) VALUES(452, "Greco Nero");
INSERT IGNORE INTO Variety(id, name) VALUES(453, "Green Hungarian");
INSERT IGNORE INTO Variety(id, name) VALUES(454, "Grenache Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(455, "Grenache Blanc - Grenache Gris");
INSERT IGNORE INTO Variety(id, name) VALUES(456, "Grenache Blanc - Vermentino");
INSERT IGNORE INTO Variety(id, name) VALUES(457, "Grenache (Garnacha)");
INSERT IGNORE INTO Variety(id, name) VALUES(458, "Grenache Gris");
INSERT IGNORE INTO Variety(id, name) VALUES(459, "Grenache - Merlot - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(460, "Grenache - Mourvedre");
INSERT IGNORE INTO Variety(id, name) VALUES(461, "Grenache - Mourvedre - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(462, "Grenache - Sangiovese");
INSERT IGNORE INTO Variety(id, name) VALUES(463, "Grenache - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(464, "Grignolino");
INSERT IGNORE INTO Variety(id, name) VALUES(465, "Grillo");
INSERT IGNORE INTO Variety(id, name) VALUES(466, "Gringet");
INSERT IGNORE INTO Variety(id, name) VALUES(467, "Grk");
INSERT IGNORE INTO Variety(id, name) VALUES(468, "Grolleau Gris");
INSERT IGNORE INTO Variety(id, name) VALUES(469, "Grolleau Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(470, "Groppello");
INSERT IGNORE INTO Variety(id, name) VALUES(471, "Gros Manseng");
INSERT IGNORE INTO Variety(id, name) VALUES(472, "Gros Manseng - Petit Manseng");
INSERT IGNORE INTO Variety(id, name) VALUES(473, "Gros Manseng - Sauvignon Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(474, "Gros Verdot");
INSERT IGNORE INTO Variety(id, name) VALUES(475, "Gruner Veltliner");
INSERT IGNORE INTO Variety(id, name) VALUES(476, "Gutenborner");
INSERT IGNORE INTO Variety(id, name) VALUES(477, "Happoshu");
INSERT IGNORE INTO Variety(id, name) VALUES(478, "Hard Seltzer");
INSERT IGNORE INTO Variety(id, name) VALUES(479, "Harslevelu");
INSERT IGNORE INTO Variety(id, name) VALUES(480, "Helfensteiner");
INSERT IGNORE INTO Variety(id, name) VALUES(481, "Heroldrebe");
INSERT IGNORE INTO Variety(id, name) VALUES(482, "Himbertscha");
INSERT IGNORE INTO Variety(id, name) VALUES(483, "Hondarrabi Beltza");
INSERT IGNORE INTO Variety(id, name) VALUES(484, "Hondarrabi Zuri");
INSERT IGNORE INTO Variety(id, name) VALUES(485, "Honey");
INSERT IGNORE INTO Variety(id, name) VALUES(486, "Humagne Blanche");
INSERT IGNORE INTO Variety(id, name) VALUES(487, "Humagne Rouge");
INSERT IGNORE INTO Variety(id, name) VALUES(488, "Huxelrebe");
INSERT IGNORE INTO Variety(id, name) VALUES(489, "Inzolia");
INSERT IGNORE INTO Variety(id, name) VALUES(490, "Irsay Oliver");
INSERT IGNORE INTO Variety(id, name) VALUES(491, "Isabella");
INSERT IGNORE INTO Variety(id, name) VALUES(492, "Ives");
INSERT IGNORE INTO Variety(id, name) VALUES(493, "Jacquere");
INSERT IGNORE INTO Variety(id, name) VALUES(494, "Jampal");
INSERT IGNORE INTO Variety(id, name) VALUES(495, "Johanniter");
INSERT IGNORE INTO Variety(id, name) VALUES(496, "Joubertin");
INSERT IGNORE INTO Variety(id, name) VALUES(497, "Juan Garcia");
INSERT IGNORE INTO Variety(id, name) VALUES(498, "Juhfark");
INSERT IGNORE INTO Variety(id, name) VALUES(499, "Jurancon Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(500, "Jurancon Noir (Folle Noire)");
INSERT IGNORE INTO Variety(id, name) VALUES(501, "Juwel");
INSERT IGNORE INTO Variety(id, name) VALUES(502, "Kabar");
INSERT IGNORE INTO Variety(id, name) VALUES(503, "Kadarka Blau");
INSERT IGNORE INTO Variety(id, name) VALUES(504, "Kalecik Karasi");
INSERT IGNORE INTO Variety(id, name) VALUES(505, "Kanzler");
INSERT IGNORE INTO Variety(id, name) VALUES(506, "Karasakiz");
INSERT IGNORE INTO Variety(id, name) VALUES(507, "Katsano");
INSERT IGNORE INTO Variety(id, name) VALUES(508, "Keduretuli (Mujuretuli)");
INSERT IGNORE INTO Variety(id, name) VALUES(509, "Kekmedoc");
INSERT IGNORE INTO Variety(id, name) VALUES(510, "Keknyelu");
INSERT IGNORE INTO Variety(id, name) VALUES(511, "Kerner");
INSERT IGNORE INTO Variety(id, name) VALUES(512, "Kombucha");
INSERT IGNORE INTO Variety(id, name) VALUES(513, "Koshu");
INSERT IGNORE INTO Variety(id, name) VALUES(514, "Kotsifali");
INSERT IGNORE INTO Variety(id, name) VALUES(515, "Kotsifali - Mandilaria");
INSERT IGNORE INTO Variety(id, name) VALUES(516, "Koverszolo (Grasa de Cotnari)");
INSERT IGNORE INTO Variety(id, name) VALUES(517, "Kovidinka");
INSERT IGNORE INTO Variety(id, name) VALUES(518, "Krakhuna");
INSERT IGNORE INTO Variety(id, name) VALUES(519, "Krassato");
INSERT IGNORE INTO Variety(id, name) VALUES(520, "Kuldzhinskii (Kouldjinka)");
INSERT IGNORE INTO Variety(id, name) VALUES(521, "La Crescent");
INSERT IGNORE INTO Variety(id, name) VALUES(522, "Lacrima");
INSERT IGNORE INTO Variety(id, name) VALUES(523, "La Crosse");
INSERT IGNORE INTO Variety(id, name) VALUES(524, "Lado");
INSERT IGNORE INTO Variety(id, name) VALUES(525, "Lagorthi");
INSERT IGNORE INTO Variety(id, name) VALUES(526, "Lagrein");
INSERT IGNORE INTO Variety(id, name) VALUES(527, "Lambrusco");
INSERT IGNORE INTO Variety(id, name) VALUES(528, "Landot Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(529, "Lasin");
INSERT IGNORE INTO Variety(id, name) VALUES(530, "Lauzet");
INSERT IGNORE INTO Variety(id, name) VALUES(531, "Leanyka");
INSERT IGNORE INTO Variety(id, name) VALUES(532, "Lemberger - Trollinger");
INSERT IGNORE INTO Variety(id, name) VALUES(533, "Len de l'El");
INSERT IGNORE INTO Variety(id, name) VALUES(534, "Len de l'El - Mauzac");
INSERT IGNORE INTO Variety(id, name) VALUES(535, "Leon Millot");
INSERT IGNORE INTO Variety(id, name) VALUES(536, "Liatiko");
INSERT IGNORE INTO Variety(id, name) VALUES(537, "Liebfraumilch");
INSERT IGNORE INTO Variety(id, name) VALUES(538, "Limnio");
INSERT IGNORE INTO Variety(id, name) VALUES(539, "Liqueur");
INSERT IGNORE INTO Variety(id, name) VALUES(540, "Liqueur - Anise");
INSERT IGNORE INTO Variety(id, name) VALUES(541, "Liqueur - Chocolate");
INSERT IGNORE INTO Variety(id, name) VALUES(542, "Liqueur - Coffee");
INSERT IGNORE INTO Variety(id, name) VALUES(543, "Liqueur - Cream");
INSERT IGNORE INTO Variety(id, name) VALUES(544, "Liqueur - Egg");
INSERT IGNORE INTO Variety(id, name) VALUES(545, "Liqueur - Fruit");
INSERT IGNORE INTO Variety(id, name) VALUES(546, "Liqueur - Herb - Spice");
INSERT IGNORE INTO Variety(id, name) VALUES(547, "Liqueur - Nut");
INSERT IGNORE INTO Variety(id, name) VALUES(548, "Liqueur - Toffee");
INSERT IGNORE INTO Variety(id, name) VALUES(549, "Listan Negro");
INSERT IGNORE INTO Variety(id, name) VALUES(550, "Lledoner Pelut");
INSERT IGNORE INTO Variety(id, name) VALUES(551, "Loureiro");
INSERT IGNORE INTO Variety(id, name) VALUES(552, "Lucie Kuhlmann");
INSERT IGNORE INTO Variety(id, name) VALUES(553, "Luglienga Bianca");
INSERT IGNORE INTO Variety(id, name) VALUES(554, "Lumassina");
INSERT IGNORE INTO Variety(id, name) VALUES(555, "Macabeo - Parellada - Xarel-lo");
INSERT IGNORE INTO Variety(id, name) VALUES(556, "Macabeo (Viura)");
INSERT IGNORE INTO Variety(id, name) VALUES(557, "Maceratino");
INSERT IGNORE INTO Variety(id, name) VALUES(558, "Madeleine Angevine");
INSERT IGNORE INTO Variety(id, name) VALUES(559, "Magliocco Canino");
INSERT IGNORE INTO Variety(id, name) VALUES(560, "Majarca Alba");
INSERT IGNORE INTO Variety(id, name) VALUES(561, "Makgeolli");
INSERT IGNORE INTO Variety(id, name) VALUES(562, "Malagousia");
INSERT IGNORE INTO Variety(id, name) VALUES(563, "Malbec");
INSERT IGNORE INTO Variety(id, name) VALUES(564, "Malbec - Merlot");
INSERT IGNORE INTO Variety(id, name) VALUES(565, "Malbec - Merlot - Tannat");
INSERT IGNORE INTO Variety(id, name) VALUES(566, "Malbec - Pinot Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(567, "Malbec - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(568, "Malbo Gentile");
INSERT IGNORE INTO Variety(id, name) VALUES(569, "Malt Beverage");
INSERT IGNORE INTO Variety(id, name) VALUES(570, "Malvar");
INSERT IGNORE INTO Variety(id, name) VALUES(571, "Malvasia");
INSERT IGNORE INTO Variety(id, name) VALUES(572, "Malvasia Bianca");
INSERT IGNORE INTO Variety(id, name) VALUES(573, "Malvasia di Candia");
INSERT IGNORE INTO Variety(id, name) VALUES(574, "Malvasia Nera");
INSERT IGNORE INTO Variety(id, name) VALUES(575, "Malvasia Nera - Negroamaro");
INSERT IGNORE INTO Variety(id, name) VALUES(576, "Malvasia - Trebbiano");
INSERT IGNORE INTO Variety(id, name) VALUES(577, "Mandilaria (Amorghiano)");
INSERT IGNORE INTO Variety(id, name) VALUES(578, "Mansengs - Petit Courbu");
INSERT IGNORE INTO Variety(id, name) VALUES(579, "Manto Negro");
INSERT IGNORE INTO Variety(id, name) VALUES(580, "Mantonico Bianco");
INSERT IGNORE INTO Variety(id, name) VALUES(581, "Manzoni Bianco");
INSERT IGNORE INTO Variety(id, name) VALUES(582, "Marastina");
INSERT IGNORE INTO Variety(id, name) VALUES(583, "Maratheftiko");
INSERT IGNORE INTO Variety(id, name) VALUES(584, "Marechal Foch");
INSERT IGNORE INTO Variety(id, name) VALUES(585, "Marmajuelo");
INSERT IGNORE INTO Variety(id, name) VALUES(586, "Marquette");
INSERT IGNORE INTO Variety(id, name) VALUES(587, "Marsanne");
INSERT IGNORE INTO Variety(id, name) VALUES(588, "Marsanne - Roussanne");
INSERT IGNORE INTO Variety(id, name) VALUES(589, "Marselan");
INSERT IGNORE INTO Variety(id, name) VALUES(590, "Marzemino");
INSERT IGNORE INTO Variety(id, name) VALUES(591, "Matrassa");
INSERT IGNORE INTO Variety(id, name) VALUES(592, "Maturana Blanca");
INSERT IGNORE INTO Variety(id, name) VALUES(593, "Maturana Tinta");
INSERT IGNORE INTO Variety(id, name) VALUES(594, "Mauzac");
INSERT IGNORE INTO Variety(id, name) VALUES(595, "Mavro");
INSERT IGNORE INTO Variety(id, name) VALUES(596, "Mavrodaphne");
INSERT IGNORE INTO Variety(id, name) VALUES(597, "Mavrotragano");
INSERT IGNORE INTO Variety(id, name) VALUES(598, "Mavrud");
INSERT IGNORE INTO Variety(id, name) VALUES(599, "Mayolet");
INSERT IGNORE INTO Variety(id, name) VALUES(600, "Melara");
INSERT IGNORE INTO Variety(id, name) VALUES(601, "Melnik");
INSERT IGNORE INTO Variety(id, name) VALUES(602, "Melody");
INSERT IGNORE INTO Variety(id, name) VALUES(603, "Melomel");
INSERT IGNORE INTO Variety(id, name) VALUES(604, "Melon de Bourgogne");
INSERT IGNORE INTO Variety(id, name) VALUES(605, "Melon Queue Rouge");
INSERT IGNORE INTO Variety(id, name) VALUES(606, "Mencia");
INSERT IGNORE INTO Variety(id, name) VALUES(607, "Merille");
INSERT IGNORE INTO Variety(id, name) VALUES(608, "Meritage");
INSERT IGNORE INTO Variety(id, name) VALUES(609, "Merlot");
INSERT IGNORE INTO Variety(id, name) VALUES(610, "Merlot Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(611, "Merlot - Montepulciano");
INSERT IGNORE INTO Variety(id, name) VALUES(612, "Merlot - Nero d'Avola");
INSERT IGNORE INTO Variety(id, name) VALUES(613, "Merlot - Sagrantino - Sangiovese");
INSERT IGNORE INTO Variety(id, name) VALUES(614, "Merlot - Sangiovese");
INSERT IGNORE INTO Variety(id, name) VALUES(615, "Merlot - Sangiovese - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(616, "Merlot - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(617, "Merlot - Tannat");
INSERT IGNORE INTO Variety(id, name) VALUES(618, "Merlot - Tempranillo");
INSERT IGNORE INTO Variety(id, name) VALUES(619, "Merseguera");
INSERT IGNORE INTO Variety(id, name) VALUES(620, "Merwah");
INSERT IGNORE INTO Variety(id, name) VALUES(621, "Merzling");
INSERT IGNORE INTO Variety(id, name) VALUES(622, "Mezcal");
INSERT IGNORE INTO Variety(id, name) VALUES(623, "Milgranet");
INSERT IGNORE INTO Variety(id, name) VALUES(624, "Minhota");
INSERT IGNORE INTO Variety(id, name) VALUES(625, "Minnella");
INSERT IGNORE INTO Variety(id, name) VALUES(626, "Mischurnitz");
INSERT IGNORE INTO Variety(id, name) VALUES(627, "Miss Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(628, "Molinara");
INSERT IGNORE INTO Variety(id, name) VALUES(629, "Moll");
INSERT IGNORE INTO Variety(id, name) VALUES(630, "Monastrell - Tempranillo");
INSERT IGNORE INTO Variety(id, name) VALUES(631, "Mondeuse Blanche");
INSERT IGNORE INTO Variety(id, name) VALUES(632, "Mondeuse Noire");
INSERT IGNORE INTO Variety(id, name) VALUES(633, "Monica");
INSERT IGNORE INTO Variety(id, name) VALUES(634, "Montepulciano");
INSERT IGNORE INTO Variety(id, name) VALUES(635, "Montepulciano - Sangiovese");
INSERT IGNORE INTO Variety(id, name) VALUES(636, "Montepulciano - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(637, "Montonega");
INSERT IGNORE INTO Variety(id, name) VALUES(638, "Montuni");
INSERT IGNORE INTO Variety(id, name) VALUES(639, "Moravia Agria");
INSERT IGNORE INTO Variety(id, name) VALUES(640, "Moreto");
INSERT IGNORE INTO Variety(id, name) VALUES(641, "Morio-Muskat");
INSERT IGNORE INTO Variety(id, name) VALUES(642, "Moristel");
INSERT IGNORE INTO Variety(id, name) VALUES(643, "Moscato Giallo");
INSERT IGNORE INTO Variety(id, name) VALUES(644, "Moscato Rosa");
INSERT IGNORE INTO Variety(id, name) VALUES(645, "Moschofilero");
INSERT IGNORE INTO Variety(id, name) VALUES(646, "Moschofilero - Roditis");
INSERT IGNORE INTO Variety(id, name) VALUES(647, "Mourisco Tinto");
INSERT IGNORE INTO Variety(id, name) VALUES(648, "Mourvedre (Monastrell)");
INSERT IGNORE INTO Variety(id, name) VALUES(649, "Mourvedre - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(650, "Mtsvani");
INSERT IGNORE INTO Variety(id, name) VALUES(651, "Muller-Thurgau");
INSERT IGNORE INTO Variety(id, name) VALUES(652, "Muscadelle");
INSERT IGNORE INTO Variety(id, name) VALUES(653, "Muscadine");
INSERT IGNORE INTO Variety(id, name) VALUES(654, "Muscardin");
INSERT IGNORE INTO Variety(id, name) VALUES(655, "Muscat");
INSERT IGNORE INTO Variety(id, name) VALUES(656, "Muscat Bailey A");
INSERT IGNORE INTO Variety(id, name) VALUES(657, "Muscat Blanc a Petits Grains");
INSERT IGNORE INTO Variety(id, name) VALUES(658, "Muscat Hamburg (Muskat Trollinger)");
INSERT IGNORE INTO Variety(id, name) VALUES(659, "Muscat of Alexandria");
INSERT IGNORE INTO Variety(id, name) VALUES(660, "Muscat Ottonel");
INSERT IGNORE INTO Variety(id, name) VALUES(661, "Muscat - Viognier");
INSERT IGNORE INTO Variety(id, name) VALUES(662, "Muskat Moravsky");
INSERT IGNORE INTO Variety(id, name) VALUES(663, "Narince");
INSERT IGNORE INTO Variety(id, name) VALUES(664, "Nascetta");
INSERT IGNORE INTO Variety(id, name) VALUES(665, "Nasco");
INSERT IGNORE INTO Variety(id, name) VALUES(666, "Nebbiolo");
INSERT IGNORE INTO Variety(id, name) VALUES(667, "Negoska");
INSERT IGNORE INTO Variety(id, name) VALUES(668, "Negrara");
INSERT IGNORE INTO Variety(id, name) VALUES(669, "Negrette");
INSERT IGNORE INTO Variety(id, name) VALUES(670, "Negroamaro");
INSERT IGNORE INTO Variety(id, name) VALUES(671, "Negroamaro - Primitivo");
INSERT IGNORE INTO Variety(id, name) VALUES(672, "Nerello Cappuccio");
INSERT IGNORE INTO Variety(id, name) VALUES(673, "Nerello Cappuccio - Nerello Mascalese");
INSERT IGNORE INTO Variety(id, name) VALUES(674, "Nerello Mascalese");
INSERT IGNORE INTO Variety(id, name) VALUES(675, "Nero Buono");
INSERT IGNORE INTO Variety(id, name) VALUES(676, "Nero d'Avola");
INSERT IGNORE INTO Variety(id, name) VALUES(677, "Nero d'Avola - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(678, "Neuburger");
INSERT IGNORE INTO Variety(id, name) VALUES(679, "New-make Spirit");
INSERT IGNORE INTO Variety(id, name) VALUES(680, "Neyret");
INSERT IGNORE INTO Variety(id, name) VALUES(681, "Niagara");
INSERT IGNORE INTO Variety(id, name) VALUES(682, "Nielluccio - Sciaccarello");
INSERT IGNORE INTO Variety(id, name) VALUES(683, "Nincusa");
INSERT IGNORE INTO Variety(id, name) VALUES(684, "Noah");
INSERT IGNORE INTO Variety(id, name) VALUES(685, "Noblessa");
INSERT IGNORE INTO Variety(id, name) VALUES(686, "Nobling");
INSERT IGNORE INTO Variety(id, name) VALUES(687, "Nocera");
INSERT IGNORE INTO Variety(id, name) VALUES(688, "Noiret");
INSERT IGNORE INTO Variety(id, name) VALUES(689, "Norton");
INSERT IGNORE INTO Variety(id, name) VALUES(690, "Nosiola");
INSERT IGNORE INTO Variety(id, name) VALUES(691, "Nuragus");
INSERT IGNORE INTO Variety(id, name) VALUES(692, "Obaideh");
INSERT IGNORE INTO Variety(id, name) VALUES(693, "Ojaleshi");
INSERT IGNORE INTO Variety(id, name) VALUES(694, "Okuzgozu");
INSERT IGNORE INTO Variety(id, name) VALUES(695, "Olivella");
INSERT IGNORE INTO Variety(id, name) VALUES(696, "Ondenc");
INSERT IGNORE INTO Variety(id, name) VALUES(697, "Opthalmo");
INSERT IGNORE INTO Variety(id, name) VALUES(698, "Optima");
INSERT IGNORE INTO Variety(id, name) VALUES(699, "Orion");
INSERT IGNORE INTO Variety(id, name) VALUES(700, "Orleans");
INSERT IGNORE INTO Variety(id, name) VALUES(701, "Ortega");
INSERT IGNORE INTO Variety(id, name) VALUES(702, "Ortrugo");
INSERT IGNORE INTO Variety(id, name) VALUES(703, "Orvieto Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(704, "Oseleta");
INSERT IGNORE INTO Variety(id, name) VALUES(705, "Osiris");
INSERT IGNORE INTO Variety(id, name) VALUES(706, "Osteiner");
INSERT IGNORE INTO Variety(id, name) VALUES(707, "Pais (Mission)");
INSERT IGNORE INTO Variety(id, name) VALUES(708, "Palas");
INSERT IGNORE INTO Variety(id, name) VALUES(709, "Palava");
INSERT IGNORE INTO Variety(id, name) VALUES(710, "Pallagrello Bianco");
INSERT IGNORE INTO Variety(id, name) VALUES(711, "Pallagrello Nero");
INSERT IGNORE INTO Variety(id, name) VALUES(712, "Palomino");
INSERT IGNORE INTO Variety(id, name) VALUES(713, "Pamid");
INSERT IGNORE INTO Variety(id, name) VALUES(714, "Pampanuto");
INSERT IGNORE INTO Variety(id, name) VALUES(715, "Papazkarasi");
INSERT IGNORE INTO Variety(id, name) VALUES(716, "Parc");
INSERT IGNORE INTO Variety(id, name) VALUES(717, "Parellada");
INSERT IGNORE INTO Variety(id, name) VALUES(718, "Parraleta");
INSERT IGNORE INTO Variety(id, name) VALUES(719, "Pascal Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(720, "Passerina");
INSERT IGNORE INTO Variety(id, name) VALUES(721, "Passerina - Pecorino - Trebbiano");
INSERT IGNORE INTO Variety(id, name) VALUES(722, "Pecorino");
INSERT IGNORE INTO Variety(id, name) VALUES(723, "Pedral");
INSERT IGNORE INTO Variety(id, name) VALUES(724, "Pedro Ximenez");
INSERT IGNORE INTO Variety(id, name) VALUES(725, "Pelaverga");
INSERT IGNORE INTO Variety(id, name) VALUES(726, "Peloursin");
INSERT IGNORE INTO Variety(id, name) VALUES(727, "Perdea");
INSERT IGNORE INTO Variety(id, name) VALUES(728, "Perle");
INSERT IGNORE INTO Variety(id, name) VALUES(729, "Perricone");
INSERT IGNORE INTO Variety(id, name) VALUES(730, "Persan");
INSERT IGNORE INTO Variety(id, name) VALUES(731, "Petit Bouschet");
INSERT IGNORE INTO Variety(id, name) VALUES(732, "Petit Courbu");
INSERT IGNORE INTO Variety(id, name) VALUES(733, "Petite Arvine");
INSERT IGNORE INTO Variety(id, name) VALUES(734, "Petite Sirah (Durif)");
INSERT IGNORE INTO Variety(id, name) VALUES(735, "Petite Sirah - Syrah - Zinfandel");
INSERT IGNORE INTO Variety(id, name) VALUES(736, "Petite Sirah - Zinfandel");
INSERT IGNORE INTO Variety(id, name) VALUES(737, "Petit Manseng");
INSERT IGNORE INTO Variety(id, name) VALUES(738, "Petit Meslier");
INSERT IGNORE INTO Variety(id, name) VALUES(739, "Petit Rouge");
INSERT IGNORE INTO Variety(id, name) VALUES(740, "Petit Verdot");
INSERT IGNORE INTO Variety(id, name) VALUES(741, "Petroulianos");
INSERT IGNORE INTO Variety(id, name) VALUES(742, "Peurion");
INSERT IGNORE INTO Variety(id, name) VALUES(743, "Phoenix");
INSERT IGNORE INTO Variety(id, name) VALUES(744, "Piccola Nera");
INSERT IGNORE INTO Variety(id, name) VALUES(745, "Picolit");
INSERT IGNORE INTO Variety(id, name) VALUES(746, "Picpoul");
INSERT IGNORE INTO Variety(id, name) VALUES(747, "Picpoul Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(748, "Piculit Neri");
INSERT IGNORE INTO Variety(id, name) VALUES(749, "Piedirosso");
INSERT IGNORE INTO Variety(id, name) VALUES(750, "Pignerol");
INSERT IGNORE INTO Variety(id, name) VALUES(751, "Pignola");
INSERT IGNORE INTO Variety(id, name) VALUES(752, "Pignolo");
INSERT IGNORE INTO Variety(id, name) VALUES(753, "Pinard");
INSERT IGNORE INTO Variety(id, name) VALUES(754, "Pineau d'Aunis");
INSERT IGNORE INTO Variety(id, name) VALUES(755, "Pinella (Pinello)");
INSERT IGNORE INTO Variety(id, name) VALUES(756, "Pink Gin");
INSERT IGNORE INTO Variety(id, name) VALUES(757, "Pinotage");
INSERT IGNORE INTO Variety(id, name) VALUES(758, "Pinotage - Shiraz");
INSERT IGNORE INTO Variety(id, name) VALUES(759, "Pinot Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(760, "Pinot Blanc - Pinot Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(761, "Pinot d'Alsace");
INSERT IGNORE INTO Variety(id, name) VALUES(762, "Pinot Grigio");
INSERT IGNORE INTO Variety(id, name) VALUES(763, "Pinot Grigio - Zibibbo");
INSERT IGNORE INTO Variety(id, name) VALUES(764, "Pinot Gris");
INSERT IGNORE INTO Variety(id, name) VALUES(765, "Pinot Gris - Sauvignon Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(766, "Pinot Meunier");
INSERT IGNORE INTO Variety(id, name) VALUES(767, "Pinot Meunier - Pinot Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(768, "Pinot Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(769, "Pinot Noir - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(770, "Pinot Noir - Zweigelt");
INSERT IGNORE INTO Variety(id, name) VALUES(771, "Pinot - Poulsard - Trousseau");
INSERT IGNORE INTO Variety(id, name) VALUES(772, "Pisco");
INSERT IGNORE INTO Variety(id, name) VALUES(773, "Planta Fina de Pedralba");
INSERT IGNORE INTO Variety(id, name) VALUES(774, "Planta Nova");
INSERT IGNORE INTO Variety(id, name) VALUES(775, "Plantet");
INSERT IGNORE INTO Variety(id, name) VALUES(776, "Plavac Mali");
INSERT IGNORE INTO Variety(id, name) VALUES(777, "Plavac Veli");
INSERT IGNORE INTO Variety(id, name) VALUES(778, "Plavina");
INSERT IGNORE INTO Variety(id, name) VALUES(779, "Plyto");
INSERT IGNORE INTO Variety(id, name) VALUES(780, "Pollera Nera");
INSERT IGNORE INTO Variety(id, name) VALUES(781, "Pontac");
INSERT IGNORE INTO Variety(id, name) VALUES(782, "Portan");
INSERT IGNORE INTO Variety(id, name) VALUES(783, "Port Blend Red");
INSERT IGNORE INTO Variety(id, name) VALUES(784, "Port Blend White");
INSERT IGNORE INTO Variety(id, name) VALUES(785, "Portugieser");
INSERT IGNORE INTO Variety(id, name) VALUES(786, "Portuguese Red Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(787, "Portuguese White Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(788, "Posip");
INSERT IGNORE INTO Variety(id, name) VALUES(789, "Poulsard");
INSERT IGNORE INTO Variety(id, name) VALUES(790, "Precoce de Malingre");
INSERT IGNORE INTO Variety(id, name) VALUES(791, "Premetta");
INSERT IGNORE INTO Variety(id, name) VALUES(792, "Premixed Drinks");
INSERT IGNORE INTO Variety(id, name) VALUES(793, "Prie Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(794, "Prieto Picudo");
INSERT IGNORE INTO Variety(id, name) VALUES(795, "Primitivo");
INSERT IGNORE INTO Variety(id, name) VALUES(796, "Prokupac");
INSERT IGNORE INTO Variety(id, name) VALUES(797, "Prunelard Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(798, "Prunelard Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(799, "Pugnitello");
INSERT IGNORE INTO Variety(id, name) VALUES(800, "Quagliano");
INSERT IGNORE INTO Variety(id, name) VALUES(801, "Rabo de Ovelha");
INSERT IGNORE INTO Variety(id, name) VALUES(802, "Raboso");
INSERT IGNORE INTO Variety(id, name) VALUES(803, "Radler-Shandy");
INSERT IGNORE INTO Variety(id, name) VALUES(804, "Raffiat de Moncade");
INSERT IGNORE INTO Variety(id, name) VALUES(805, "Ramisco");
INSERT IGNORE INTO Variety(id, name) VALUES(806, "Rare Red Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(807, "Rare Rose Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(808, "Rare White Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(809, "Rassegui");
INSERT IGNORE INTO Variety(id, name) VALUES(810, "Ratafia");
INSERT IGNORE INTO Variety(id, name) VALUES(811, "Rathay");
INSERT IGNORE INTO Variety(id, name) VALUES(812, "Rauschling");
INSERT IGNORE INTO Variety(id, name) VALUES(813, "Ravat Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(814, "Ravat Vignoles");
INSERT IGNORE INTO Variety(id, name) VALUES(815, "Rayon d'Or");
INSERT IGNORE INTO Variety(id, name) VALUES(816, "Rebo");
INSERT IGNORE INTO Variety(id, name) VALUES(817, "Refosco");
INSERT IGNORE INTO Variety(id, name) VALUES(818, "Regent");
INSERT IGNORE INTO Variety(id, name) VALUES(819, "Regner");
INSERT IGNORE INTO Variety(id, name) VALUES(820, "Reichensteiner");
INSERT IGNORE INTO Variety(id, name) VALUES(821, "Reze");
INSERT IGNORE INTO Variety(id, name) VALUES(822, "Ribolla");
INSERT IGNORE INTO Variety(id, name) VALUES(823, "Rieslaner");
INSERT IGNORE INTO Variety(id, name) VALUES(824, "Riesling");
INSERT IGNORE INTO Variety(id, name) VALUES(825, "Riesling - Silvaner");
INSERT IGNORE INTO Variety(id, name) VALUES(826, "Rioja Red Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(827, "Rioja White Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(828, "Rkatsiteli");
INSERT IGNORE INTO Variety(id, name) VALUES(829, "Robola");
INSERT IGNORE INTO Variety(id, name) VALUES(830, "Roditis");
INSERT IGNORE INTO Variety(id, name) VALUES(831, "Roesler");
INSERT IGNORE INTO Variety(id, name) VALUES(832, "Rolle - Ugni Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(833, "Romorantin");
INSERT IGNORE INTO Variety(id, name) VALUES(834, "Rondinella");
INSERT IGNORE INTO Variety(id, name) VALUES(835, "Rondo");
INSERT IGNORE INTO Variety(id, name) VALUES(836, "Roscetto");
INSERT IGNORE INTO Variety(id, name) VALUES(837, "Rossara");
INSERT IGNORE INTO Variety(id, name) VALUES(838, "Rossese");
INSERT IGNORE INTO Variety(id, name) VALUES(839, "Rossola Nera");
INSERT IGNORE INTO Variety(id, name) VALUES(840, "Rotberger");
INSERT IGNORE INTO Variety(id, name) VALUES(841, "Roter Gutedel");
INSERT IGNORE INTO Variety(id, name) VALUES(842, "Roter Riesling");
INSERT IGNORE INTO Variety(id, name) VALUES(843, "Roter Traminer (Savagnin Rose)");
INSERT IGNORE INTO Variety(id, name) VALUES(844, "Roter Veltliner");
INSERT IGNORE INTO Variety(id, name) VALUES(845, "Rotgipfler");
INSERT IGNORE INTO Variety(id, name) VALUES(846, "Rougeon");
INSERT IGNORE INTO Variety(id, name) VALUES(847, "Roussanne");
INSERT IGNORE INTO Variety(id, name) VALUES(848, "Roussanne - Viognier");
INSERT IGNORE INTO Variety(id, name) VALUES(849, "Royalty");
INSERT IGNORE INTO Variety(id, name) VALUES(850, "Rubienne");
INSERT IGNORE INTO Variety(id, name) VALUES(851, "Rubin Bolgarskii");
INSERT IGNORE INTO Variety(id, name) VALUES(852, "Rubired");
INSERT IGNORE INTO Variety(id, name) VALUES(853, "Ruby Cabernet");
INSERT IGNORE INTO Variety(id, name) VALUES(854, "Ruche");
INSERT IGNORE INTO Variety(id, name) VALUES(855, "Rufete (Tinta Pinheira)");
INSERT IGNORE INTO Variety(id, name) VALUES(856, "Rum");
INSERT IGNORE INTO Variety(id, name) VALUES(857, "Rum - Liqueur - Flavored");
INSERT IGNORE INTO Variety(id, name) VALUES(858, "Sacy");
INSERT IGNORE INTO Variety(id, name) VALUES(859, "Sagrantino");
INSERT IGNORE INTO Variety(id, name) VALUES(860, "Sagrantino - Sangiovese");
INSERT IGNORE INTO Variety(id, name) VALUES(861, "Saint-Croix");
INSERT IGNORE INTO Variety(id, name) VALUES(862, "Saint-Jeannet");
INSERT IGNORE INTO Variety(id, name) VALUES(863, "Saint-Macaire");
INSERT IGNORE INTO Variety(id, name) VALUES(864, "Saint-Pepin");
INSERT IGNORE INTO Variety(id, name) VALUES(865, "Sake");
INSERT IGNORE INTO Variety(id, name) VALUES(866, "Samtrot");
INSERT IGNORE INTO Variety(id, name) VALUES(867, "Sangiovese");
INSERT IGNORE INTO Variety(id, name) VALUES(868, "Sangiovese - Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(869, "Sangria");
INSERT IGNORE INTO Variety(id, name) VALUES(870, "Sankt Laurent");
INSERT IGNORE INTO Variety(id, name) VALUES(871, "Santa Maria");
INSERT IGNORE INTO Variety(id, name) VALUES(872, "Saperavi");
INSERT IGNORE INTO Variety(id, name) VALUES(873, "Sauvignon Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(874, "Sauvignon Blanc - Semillon");
INSERT IGNORE INTO Variety(id, name) VALUES(875, "Sauvignon Blanc - Ugni Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(876, "Sauvignon Blanc - Verdejo");
INSERT IGNORE INTO Variety(id, name) VALUES(877, "Sauvignon Blanc - Vermentino");
INSERT IGNORE INTO Variety(id, name) VALUES(878, "Sauvignon Blanc - Viognier");
INSERT IGNORE INTO Variety(id, name) VALUES(879, "Sauvignon Gris");
INSERT IGNORE INTO Variety(id, name) VALUES(880, "Savagnin");
INSERT IGNORE INTO Variety(id, name) VALUES(881, "Savatiano");
INSERT IGNORE INTO Variety(id, name) VALUES(882, "Scheurebe");
INSERT IGNORE INTO Variety(id, name) VALUES(883, "Schiava");
INSERT IGNORE INTO Variety(id, name) VALUES(884, "Schioppettino");
INSERT IGNORE INTO Variety(id, name) VALUES(885, "Schnapps");
INSERT IGNORE INTO Variety(id, name) VALUES(886, "Schonburger");
INSERT IGNORE INTO Variety(id, name) VALUES(887, "Sciaccarello (Mammolo)");
INSERT IGNORE INTO Variety(id, name) VALUES(888, "Scuppernong");
INSERT IGNORE INTO Variety(id, name) VALUES(889, "Semidano");
INSERT IGNORE INTO Variety(id, name) VALUES(890, "Semillon");
INSERT IGNORE INTO Variety(id, name) VALUES(891, "Semillon - Rolle");
INSERT IGNORE INTO Variety(id, name) VALUES(892, "Sercial");
INSERT IGNORE INTO Variety(id, name) VALUES(893, "Seyval Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(894, "Sgavetta");
INSERT IGNORE INTO Variety(id, name) VALUES(895, "Sherry Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(896, "Shiraz");
INSERT IGNORE INTO Variety(id, name) VALUES(897, "Shochu");
INSERT IGNORE INTO Variety(id, name) VALUES(898, "Sideritis");
INSERT IGNORE INTO Variety(id, name) VALUES(899, "Siegerrebe");
INSERT IGNORE INTO Variety(id, name) VALUES(900, "Silcher");
INSERT IGNORE INTO Variety(id, name) VALUES(901, "Silvaner");
INSERT IGNORE INTO Variety(id, name) VALUES(902, "Siria (Roupeiro)");
INSERT IGNORE INTO Variety(id, name) VALUES(903, "Skrlet");
INSERT IGNORE INTO Variety(id, name) VALUES(904, "Smederevka");
INSERT IGNORE INTO Variety(id, name) VALUES(905, "Soave Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(906, "Soju");
INSERT IGNORE INTO Variety(id, name) VALUES(907, "Solaris");
INSERT IGNORE INTO Variety(id, name) VALUES(908, "Sotol");
INSERT IGNORE INTO Variety(id, name) VALUES(909, "Southern Rhone Red Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(910, "Southern Rhone White Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(911, "Spergola");
INSERT IGNORE INTO Variety(id, name) VALUES(912, "Stavroto");
INSERT IGNORE INTO Variety(id, name) VALUES(913, "Steuben");
INSERT IGNORE INTO Variety(id, name) VALUES(914, "Sultana");
INSERT IGNORE INTO Variety(id, name) VALUES(915, "Sumoll");
INSERT IGNORE INTO Variety(id, name) VALUES(916, "Sumoll Blanco");
INSERT IGNORE INTO Variety(id, name) VALUES(917, "Susumaniello");
INSERT IGNORE INTO Variety(id, name) VALUES(918, "Symphony");
INSERT IGNORE INTO Variety(id, name) VALUES(919, "Syrah");
INSERT IGNORE INTO Variety(id, name) VALUES(920, "Syrah - Tempranillo");
INSERT IGNORE INTO Variety(id, name) VALUES(921, "Syrah - Touriga");
INSERT IGNORE INTO Variety(id, name) VALUES(922, "Syrah - Viognier");
INSERT IGNORE INTO Variety(id, name) VALUES(923, "Syrah - Zinfandel");
INSERT IGNORE INTO Variety(id, name) VALUES(924, "Szagos Feher");
INSERT IGNORE INTO Variety(id, name) VALUES(925, "Taminga");
INSERT IGNORE INTO Variety(id, name) VALUES(926, "Tannat");
INSERT IGNORE INTO Variety(id, name) VALUES(927, "Tarrango");
INSERT IGNORE INTO Variety(id, name) VALUES(928, "Tavkveri");
INSERT IGNORE INTO Variety(id, name) VALUES(929, "Tazzelenghe");
INSERT IGNORE INTO Variety(id, name) VALUES(930, "Tempranillo");
INSERT IGNORE INTO Variety(id, name) VALUES(931, "Tempranillo Blanco");
INSERT IGNORE INTO Variety(id, name) VALUES(932, "Tequila");
INSERT IGNORE INTO Variety(id, name) VALUES(933, "Teroldego");
INSERT IGNORE INTO Variety(id, name) VALUES(934, "Terrantez");
INSERT IGNORE INTO Variety(id, name) VALUES(935, "Terret Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(936, "Terret Gris");
INSERT IGNORE INTO Variety(id, name) VALUES(937, "Terret Noir");
INSERT IGNORE INTO Variety(id, name) VALUES(938, "Tibouren");
INSERT IGNORE INTO Variety(id, name) VALUES(939, "Timorasso");
INSERT IGNORE INTO Variety(id, name) VALUES(940, "Tinta Amarela (Trincadeira)");
INSERT IGNORE INTO Variety(id, name) VALUES(941, "Tinta Barroca");
INSERT IGNORE INTO Variety(id, name) VALUES(942, "Tinta Barroca - Tinta Roriz - Touriga");
INSERT IGNORE INTO Variety(id, name) VALUES(943, "Tinta Caiada");
INSERT IGNORE INTO Variety(id, name) VALUES(944, "Tinta Carvalha");
INSERT IGNORE INTO Variety(id, name) VALUES(945, "Tinta Francisca");
INSERT IGNORE INTO Variety(id, name) VALUES(946, "Tinta Negra Mole");
INSERT IGNORE INTO Variety(id, name) VALUES(947, "Tinta Roriz (Aragonez) - Touriga");
INSERT IGNORE INTO Variety(id, name) VALUES(948, "Tinta Roriz - Tinto Cao - Touriga");
INSERT IGNORE INTO Variety(id, name) VALUES(949, "Tintilia");
INSERT IGNORE INTO Variety(id, name) VALUES(950, "Tinto Cao");
INSERT IGNORE INTO Variety(id, name) VALUES(951, "Tintore di Tramonti");
INSERT IGNORE INTO Variety(id, name) VALUES(952, "Titan");
INSERT IGNORE INTO Variety(id, name) VALUES(953, "Tokaji Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(954, "Torbato");
INSERT IGNORE INTO Variety(id, name) VALUES(955, "Torrontes");
INSERT IGNORE INTO Variety(id, name) VALUES(956, "Touriga Franca");
INSERT IGNORE INTO Variety(id, name) VALUES(957, "Touriga Franca - Touriga Nacional");
INSERT IGNORE INTO Variety(id, name) VALUES(958, "Touriga Nacional");
INSERT IGNORE INTO Variety(id, name) VALUES(959, "Trajadura (Treixadura)");
INSERT IGNORE INTO Variety(id, name) VALUES(960, "Traminer");
INSERT IGNORE INTO Variety(id, name) VALUES(961, "Traminette");
INSERT IGNORE INTO Variety(id, name) VALUES(962, "Trbljan");
INSERT IGNORE INTO Variety(id, name) VALUES(963, "Trebbiano Spoletino");
INSERT IGNORE INTO Variety(id, name) VALUES(964, "Trebbiano (Ugni Blanc)");
INSERT IGNORE INTO Variety(id, name) VALUES(965, "Trepat");
INSERT IGNORE INTO Variety(id, name) VALUES(966, "Trincadeira das Pratas");
INSERT IGNORE INTO Variety(id, name) VALUES(967, "Triomphe");
INSERT IGNORE INTO Variety(id, name) VALUES(968, "Trousseau (Bastardo)");
INSERT IGNORE INTO Variety(id, name) VALUES(969, "Trousseau Gris");
INSERT IGNORE INTO Variety(id, name) VALUES(970, "Tsaoussi");
INSERT IGNORE INTO Variety(id, name) VALUES(971, "Tsitska");
INSERT IGNORE INTO Variety(id, name) VALUES(972, "Tsolikouri");
INSERT IGNORE INTO Variety(id, name) VALUES(973, "Turan (Agria)");
INSERT IGNORE INTO Variety(id, name) VALUES(974, "Umeshu");
INSERT IGNORE INTO Variety(id, name) VALUES(975, "Usakhelauri");
INSERT IGNORE INTO Variety(id, name) VALUES(976, "Uva del Fantini");
INSERT IGNORE INTO Variety(id, name) VALUES(977, "Uva di Troia");
INSERT IGNORE INTO Variety(id, name) VALUES(978, "Uva Longanesi");
INSERT IGNORE INTO Variety(id, name) VALUES(979, "Uva Rara");
INSERT IGNORE INTO Variety(id, name) VALUES(980, "Vaccarese");
INSERT IGNORE INTO Variety(id, name) VALUES(981, "Valdiguie");
INSERT IGNORE INTO Variety(id, name) VALUES(982, "Valiant");
INSERT IGNORE INTO Variety(id, name) VALUES(983, "Valpolicella Blend");
INSERT IGNORE INTO Variety(id, name) VALUES(984, "Ventura");
INSERT IGNORE INTO Variety(id, name) VALUES(985, "Verdanel");
INSERT IGNORE INTO Variety(id, name) VALUES(986, "Verdea");
INSERT IGNORE INTO Variety(id, name) VALUES(987, "Verdeca");
INSERT IGNORE INTO Variety(id, name) VALUES(988, "Verdejo");
INSERT IGNORE INTO Variety(id, name) VALUES(989, "Verdejo - Viura");
INSERT IGNORE INTO Variety(id, name) VALUES(990, "Verdelet");
INSERT IGNORE INTO Variety(id, name) VALUES(991, "Verdelho");
INSERT IGNORE INTO Variety(id, name) VALUES(992, "Verdesse");
INSERT IGNORE INTO Variety(id, name) VALUES(993, "Verdicchio");
INSERT IGNORE INTO Variety(id, name) VALUES(994, "Verdil");
INSERT IGNORE INTO Variety(id, name) VALUES(995, "Verdiso");
INSERT IGNORE INTO Variety(id, name) VALUES(996, "Verdoncho");
INSERT IGNORE INTO Variety(id, name) VALUES(997, "Verduzzo");
INSERT IGNORE INTO Variety(id, name) VALUES(998, "Vermentino Nero");
INSERT IGNORE INTO Variety(id, name) VALUES(999, "Vermentino (Rolle)");
INSERT IGNORE INTO Variety(id, name) VALUES(1000, "Vermouth");
INSERT IGNORE INTO Variety(id, name) VALUES(1001, "Vernaccia");
INSERT IGNORE INTO Variety(id, name) VALUES(1002, "Vernaccia Nera");
INSERT IGNORE INTO Variety(id, name) VALUES(1003, "Vertzami");
INSERT IGNORE INTO Variety(id, name) VALUES(1004, "Vespaiolo");
INSERT IGNORE INTO Variety(id, name) VALUES(1005, "Vespolina");
INSERT IGNORE INTO Variety(id, name) VALUES(1006, "Vidadillo (Crespiello)");
INSERT IGNORE INTO Variety(id, name) VALUES(1007, "Vidal");
INSERT IGNORE INTO Variety(id, name) VALUES(1008, "Vidiano");
INSERT IGNORE INTO Variety(id, name) VALUES(1009, "Vien de Nus");
INSERT IGNORE INTO Variety(id, name) VALUES(1010, "Vijariego Blanco");
INSERT IGNORE INTO Variety(id, name) VALUES(1011, "Vijariego Negro");
INSERT IGNORE INTO Variety(id, name) VALUES(1012, "Vilana");
INSERT IGNORE INTO Variety(id, name) VALUES(1013, "Villard Blanc");
INSERT IGNORE INTO Variety(id, name) VALUES(1014, "Vin de Liqueur");
INSERT IGNORE INTO Variety(id, name) VALUES(1015, "Vinhao (Sousao)");
INSERT IGNORE INTO Variety(id, name) VALUES(1016, "Viognier");
INSERT IGNORE INTO Variety(id, name) VALUES(1017, "Viosinho");
INSERT IGNORE INTO Variety(id, name) VALUES(1018, "Vital");
INSERT IGNORE INTO Variety(id, name) VALUES(1019, "Vitovska");
INSERT IGNORE INTO Variety(id, name) VALUES(1020, "Vodka");
INSERT IGNORE INTO Variety(id, name) VALUES(1021, "Vodka - Flavored");
INSERT IGNORE INTO Variety(id, name) VALUES(1022, "Volitsa (Volidza)");
INSERT IGNORE INTO Variety(id, name) VALUES(1023, "Voudomato");
INSERT IGNORE INTO Variety(id, name) VALUES(1024, "Vradiano");
INSERT IGNORE INTO Variety(id, name) VALUES(1025, "Vranac");
INSERT IGNORE INTO Variety(id, name) VALUES(1026, "Vugava");
INSERT IGNORE INTO Variety(id, name) VALUES(1027, "Vuillermin");
INSERT IGNORE INTO Variety(id, name) VALUES(1028, "Welschriesling");
INSERT IGNORE INTO Variety(id, name) VALUES(1029, "Whiskey - America");
INSERT IGNORE INTO Variety(id, name) VALUES(1030, "Whiskey Bourbon");
INSERT IGNORE INTO Variety(id, name) VALUES(1031, "Whiskey Corn");
INSERT IGNORE INTO Variety(id, name) VALUES(1032, "Whiskey - Irish");
INSERT IGNORE INTO Variety(id, name) VALUES(1033, "Whiskey - Liqueur - Flavored");
INSERT IGNORE INTO Variety(id, name) VALUES(1034, "Whiskey - Rye");
INSERT IGNORE INTO Variety(id, name) VALUES(1035, "Whiskey - Wheat");
INSERT IGNORE INTO Variety(id, name) VALUES(1036, "Whisky - Australia");
INSERT IGNORE INTO Variety(id, name) VALUES(1037, "Whisky - Canada");
INSERT IGNORE INTO Variety(id, name) VALUES(1038, "Whisky - India");
INSERT IGNORE INTO Variety(id, name) VALUES(1039, "Whisky - Japan");
INSERT IGNORE INTO Variety(id, name) VALUES(1040, "Whisky - Whiskey Blended");
INSERT IGNORE INTO Variety(id, name) VALUES(1041, "Whisky - Whiskey Grain");
INSERT IGNORE INTO Variety(id, name) VALUES(1042, "Whisky - Whiskey Malt");
INSERT IGNORE INTO Variety(id, name) VALUES(1043, "Wurzer");
INSERT IGNORE INTO Variety(id, name) VALUES(1044, "Xarel-lo");
INSERT IGNORE INTO Variety(id, name) VALUES(1045, "Xinomavro");
INSERT IGNORE INTO Variety(id, name) VALUES(1046, "Xynisteri");
INSERT IGNORE INTO Variety(id, name) VALUES(1047, "Zalema");
INSERT IGNORE INTO Variety(id, name) VALUES(1048, "Zefir");
INSERT IGNORE INTO Variety(id, name) VALUES(1049, "Zelen");
INSERT IGNORE INTO Variety(id, name) VALUES(1050, "Zenit");
INSERT IGNORE INTO Variety(id, name) VALUES(1051, "Zeta");
INSERT IGNORE INTO Variety(id, name) VALUES(1052, "Zeus");
INSERT IGNORE INTO Variety(id, name) VALUES(1053, "Zierfandler");
INSERT IGNORE INTO Variety(id, name) VALUES(1054, "Zilavka");
INSERT IGNORE INTO Variety(id, name) VALUES(1055, "Zinfandel");
INSERT IGNORE INTO Variety(id, name) VALUES(1056, "Zlahtina");
INSERT IGNORE INTO Variety(id, name) VALUES(1057, "Zweigelt");
