INSERT INTO Varierity( ID , NAME ) VALUES( 1 , ' Abouriou ');
INSERT INTO Varierity( ID , NAME ) VALUES( 2 , ' Abrustine ');
INSERT INTO Varierity( ID , NAME ) VALUES( 3 , ' Absinthe ');
INSERT INTO Varierity( ID , NAME ) VALUES( 4 , ' Acadie Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 5 , ' Acolon ');
INSERT INTO Varierity( ID , NAME ) VALUES( 6 , ' Agave Spirit ');
INSERT INTO Varierity( ID , NAME ) VALUES( 7 , ' Agiorgitiko ');
INSERT INTO Varierity( ID , NAME ) VALUES( 8 , ' Aglianico ');
INSERT INTO Varierity( ID , NAME ) VALUES( 9 , ' Aglianico - Piedirosso ');
INSERT INTO Varierity( ID , NAME ) VALUES( 10 , ' Ahmeur bou Ahmeur ');
INSERT INTO Varierity( ID , NAME ) VALUES( 11 , ' Aidani ');
INSERT INTO Varierity( ID , NAME ) VALUES( 12 , ' Airen ');
INSERT INTO Varierity( ID , NAME ) VALUES( 13 , ' Aladasturi ');
INSERT INTO Varierity( ID , NAME ) VALUES( 14 , ' Alarijen ');
INSERT INTO Varierity( ID , NAME ) VALUES( 15 , ' Albalonga ');
INSERT INTO Varierity( ID , NAME ) VALUES( 16 , ' Albana ');
INSERT INTO Varierity( ID , NAME ) VALUES( 17 , ' Albanella ');
INSERT INTO Varierity( ID , NAME ) VALUES( 18 , ' Albarello Blanca ');
INSERT INTO Varierity( ID , NAME ) VALUES( 19 , ' Albarin Blanco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 20 , ' Albarino (Alvarinho) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 21 , ' Albarola ');
INSERT INTO Varierity( ID , NAME ) VALUES( 22 , ' Albarola - Bosco - Vermentino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 23 , ' Albarossa ');
INSERT INTO Varierity( ID , NAME ) VALUES( 24 , ' Albillo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 25 , ' Albillo Krimskii (Rachuli Tetra) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 26 , ' Alcohol-Free ');
INSERT INTO Varierity( ID , NAME ) VALUES( 27 , ' Aleatico ');
INSERT INTO Varierity( ID , NAME ) VALUES( 28 , ' Alexandrouli ');
INSERT INTO Varierity( ID , NAME ) VALUES( 29 , ' Alfrocheiro Preto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 30 , ' Alfrocheiro Preto - Tinta Roriz - Touriga ');
INSERT INTO Varierity( ID , NAME ) VALUES( 31 , ' Alfrocheiro Preto - Touriga ');
INSERT INTO Varierity( ID , NAME ) VALUES( 32 , ' Alibernet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 33 , ' Alicante Bouschet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 34 , ' Alicante Bouschet - Aragonez ');
INSERT INTO Varierity( ID , NAME ) VALUES( 35 , ' Alicante Bouschet - Aragonez - Trincadeira ');
INSERT INTO Varierity( ID , NAME ) VALUES( 36 , ' Alicante Bouschet - Touriga ');
INSERT INTO Varierity( ID , NAME ) VALUES( 37 , ' Alicante Ganzin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 38 , ' Aligote ');
INSERT INTO Varierity( ID , NAME ) VALUES( 39 , ' Alphonse Lavallee ');
INSERT INTO Varierity( ID , NAME ) VALUES( 40 , ' Altesse ');
INSERT INTO Varierity( ID , NAME ) VALUES( 41 , ' Alvarelhao ');
INSERT INTO Varierity( ID , NAME ) VALUES( 42 , ' Amigne ');
INSERT INTO Varierity( ID , NAME ) VALUES( 43 , ' Ancellotta ');
INSERT INTO Varierity( ID , NAME ) VALUES( 44 , ' Andre ');
INSERT INTO Varierity( ID , NAME ) VALUES( 45 , ' Antao Vaz ');
INSERT INTO Varierity( ID , NAME ) VALUES( 46 , ' Antao Vaz - Arinto (Pederna) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 47 , ' Aragonez (Tinta Roriz) - Castelao ');
INSERT INTO Varierity( ID , NAME ) VALUES( 48 , ' Aramon ');
INSERT INTO Varierity( ID , NAME ) VALUES( 49 , ' Aranel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 50 , ' Arany Sarfeher ');
INSERT INTO Varierity( ID , NAME ) VALUES( 51 , ' Arbane ');
INSERT INTO Varierity( ID , NAME ) VALUES( 52 , ' Arbois ');
INSERT INTO Varierity( ID , NAME ) VALUES( 53 , ' Areni Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 54 , ' Argaman ');
INSERT INTO Varierity( ID , NAME ) VALUES( 55 , ' Argant ');
INSERT INTO Varierity( ID , NAME ) VALUES( 56 , ' Arinarnoa ');
INSERT INTO Varierity( ID , NAME ) VALUES( 57 , ' Arinto (Pederna) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 58 , ' Arinto (Pederna) - Fernao Pires ');
INSERT INTO Varierity( ID , NAME ) VALUES( 59 , ' Arinto (Pederna) - Loureiro ');
INSERT INTO Varierity( ID , NAME ) VALUES( 60 , ' Arneis ');
INSERT INTO Varierity( ID , NAME ) VALUES( 61 , ' Arriloba ');
INSERT INTO Varierity( ID , NAME ) VALUES( 62 , ' Arrufiac ');
INSERT INTO Varierity( ID , NAME ) VALUES( 63 , ' Aspiran ');
INSERT INTO Varierity( ID , NAME ) VALUES( 64 , ' Assyrtiko ');
INSERT INTO Varierity( ID , NAME ) VALUES( 65 , ' Athiri ');
INSERT INTO Varierity( ID , NAME ) VALUES( 66 , ' Aubin Vert ');
INSERT INTO Varierity( ID , NAME ) VALUES( 67 , ' Aubun ');
INSERT INTO Varierity( ID , NAME ) VALUES( 68 , ' Aurore ');
INSERT INTO Varierity( ID , NAME ) VALUES( 69 , ' Auxerrois ');
INSERT INTO Varierity( ID , NAME ) VALUES( 70 , ' Avana ');
INSERT INTO Varierity( ID , NAME ) VALUES( 71 , ' Avarengo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 72 , ' Avesso ');
INSERT INTO Varierity( ID , NAME ) VALUES( 73 , ' Avgoustiatis ');
INSERT INTO Varierity( ID , NAME ) VALUES( 74 , ' Awamori ');
INSERT INTO Varierity( ID , NAME ) VALUES( 75 , ' Azal Branco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 76 , ' Azal Tinto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 77 , ' Babeasca Neagra ');
INSERT INTO Varierity( ID , NAME ) VALUES( 78 , ' Babic ');
INSERT INTO Varierity( ID , NAME ) VALUES( 79 , ' Bacchus ');
INSERT INTO Varierity( ID , NAME ) VALUES( 80 , ' Bachet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 81 , ' Baco Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 82 , ' Baco Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 83 , ' Baga ');
INSERT INTO Varierity( ID , NAME ) VALUES( 84 , ' Baijiu ');
INSERT INTO Varierity( ID , NAME ) VALUES( 85 , ' Baltica ');
INSERT INTO Varierity( ID , NAME ) VALUES( 86 , ' Barbarossa ');
INSERT INTO Varierity( ID , NAME ) VALUES( 87 , ' Barbera ');
INSERT INTO Varierity( ID , NAME ) VALUES( 88 , ' Barbera - Bonarda (Croatina) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 89 , ' Barbera - Dolcetto - Nebbiolo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 90 , ' Barbera - Nebbiolo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 91 , ' Barbera - Sangiovese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 92 , ' Baroque ');
INSERT INTO Varierity( ID , NAME ) VALUES( 93 , ' Barsaglina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 94 , ' Batiki ');
INSERT INTO Varierity( ID , NAME ) VALUES( 95 , ' Beaunoir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 96 , ' Beer ');
INSERT INTO Varierity( ID , NAME ) VALUES( 97 , ' Bellone Bianco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 98 , ' Bequignol ');
INSERT INTO Varierity( ID , NAME ) VALUES( 99 , ' Bervedino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 100 , ' Bianchello (Biancame) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 101 , ' Bianchetta Genovese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 102 , ' Bianco d'Alessano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 103 , ' Bianco d'Alessano - Verdeca ');
INSERT INTO Varierity( ID , NAME ) VALUES( 104 , ' Biancolella ');
INSERT INTO Varierity( ID , NAME ) VALUES( 105 , ' Biancone ');
INSERT INTO Varierity( ID , NAME ) VALUES( 106 , ' Biancu Gentile ');
INSERT INTO Varierity( ID , NAME ) VALUES( 107 , ' Bical ');
INSERT INTO Varierity( ID , NAME ) VALUES( 108 , ' Bigolona ');
INSERT INTO Varierity( ID , NAME ) VALUES( 109 , ' Bitters ');
INSERT INTO Varierity( ID , NAME ) VALUES( 110 , ' Black Monukka ');
INSERT INTO Varierity( ID , NAME ) VALUES( 111 , ' Black Spanish (Lenoir) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 112 , ' Blanc du Bois ');
INSERT INTO Varierity( ID , NAME ) VALUES( 113 , ' Blanqueiron ');
INSERT INTO Varierity( ID , NAME ) VALUES( 114 , ' Blatina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 115 , ' Blauburger ');
INSERT INTO Varierity( ID , NAME ) VALUES( 116 , ' Blauer Wildbacher ');
INSERT INTO Varierity( ID , NAME ) VALUES( 117 , ' Blaufrankisch - Cabernet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 118 , ' Blaufrankisch - Cabernet - Merlot ');
INSERT INTO Varierity( ID , NAME ) VALUES( 119 , ' Blaufrankisch (Lemberger) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 120 , ' Blaufrankisch - Zweigelt ');
INSERT INTO Varierity( ID , NAME ) VALUES( 121 , ' Bobal ');
INSERT INTO Varierity( ID , NAME ) VALUES( 122 , ' Bobal Blanco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 123 , ' Bogazkere ');
INSERT INTO Varierity( ID , NAME ) VALUES( 124 , ' Bogazkere - Okuzgozu ');
INSERT INTO Varierity( ID , NAME ) VALUES( 125 , ' Bogdanusa ');
INSERT INTO Varierity( ID , NAME ) VALUES( 126 , ' Bombino Bianco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 127 , ' Bombino Nero ');
INSERT INTO Varierity( ID , NAME ) VALUES( 128 , ' Bonarda - Malbec ');
INSERT INTO Varierity( ID , NAME ) VALUES( 129 , ' Bonarda Piemontese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 130 , ' Bondola ');
INSERT INTO Varierity( ID , NAME ) VALUES( 131 , ' Bordeaux Blend Red ');
INSERT INTO Varierity( ID , NAME ) VALUES( 132 , ' Bordeaux Blend White ');
INSERT INTO Varierity( ID , NAME ) VALUES( 133 , ' Bosco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 134 , ' Bourboulenc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 135 , ' Bouvier ');
INSERT INTO Varierity( ID , NAME ) VALUES( 136 , ' Brachetto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 137 , ' Brandy ');
INSERT INTO Varierity( ID , NAME ) VALUES( 138 , ' Braquet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 139 , ' Brauner Veltliner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 140 , ' Brianna ');
INSERT INTO Varierity( ID , NAME ) VALUES( 141 , ' Bronner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 142 , ' Bronx ');
INSERT INTO Varierity( ID , NAME ) VALUES( 143 , ' Brunal ');
INSERT INTO Varierity( ID , NAME ) VALUES( 144 , ' Brun Fourca ');
INSERT INTO Varierity( ID , NAME ) VALUES( 145 , ' Bual (Malvasia Fina) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 146 , ' Bukettraube ');
INSERT INTO Varierity( ID , NAME ) VALUES( 147 , ' Burger ');
INSERT INTO Varierity( ID , NAME ) VALUES( 148 , ' Cabernet Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 149 , ' Cabernet - Carignan - Grenache ');
INSERT INTO Varierity( ID , NAME ) VALUES( 150 , ' Cabernet - Carignan - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 151 , ' Cabernet Cubin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 152 , ' Cabernet Dorio ');
INSERT INTO Varierity( ID , NAME ) VALUES( 153 , ' Cabernet Dorsa ');
INSERT INTO Varierity( ID , NAME ) VALUES( 154 , ' Cabernet Franc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 155 , ' Cabernet Franc - Cabernet Sauvignon ');
INSERT INTO Varierity( ID , NAME ) VALUES( 156 , ' Cabernet Franc - Gamay ');
INSERT INTO Varierity( ID , NAME ) VALUES( 157 , ' Cabernet Franc - Malbec ');
INSERT INTO Varierity( ID , NAME ) VALUES( 158 , ' Cabernet Franc - Merlot ');
INSERT INTO Varierity( ID , NAME ) VALUES( 159 , ' Cabernet Franc - Pinot Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 160 , ' Cabernet Gernischt ');
INSERT INTO Varierity( ID , NAME ) VALUES( 161 , ' Cabernet - Grenache - Merlot - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 162 , ' Cabernet - Grenache - Mourvedre - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 163 , ' Cabernet - Grenache - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 164 , ' Cabernet Jura ');
INSERT INTO Varierity( ID , NAME ) VALUES( 165 , ' Cabernet - Malbec - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 166 , ' Cabernet - Merlot - Montepulciano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 167 , ' Cabernet - Merlot - Sangiovese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 168 , ' Cabernet - Merlot - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 169 , ' Cabernet - Merlot - Tempranillo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 170 , ' Cabernet - Merlot - Zinfandel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 171 , ' Cabernet - Merlot - Zweigelt ');
INSERT INTO Varierity( ID , NAME ) VALUES( 172 , ' Cabernet Mitos ');
INSERT INTO Varierity( ID , NAME ) VALUES( 173 , ' Cabernet - Montepulciano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 174 , ' Cabernet Moravia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 175 , ' Cabernet - Mourvedre - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 176 , ' Cabernet - Nero d'Avola ');
INSERT INTO Varierity( ID , NAME ) VALUES( 177 , ' Cabernet - Petit Verdot ');
INSERT INTO Varierity( ID , NAME ) VALUES( 178 , ' Cabernet Pfeffer ');
INSERT INTO Varierity( ID , NAME ) VALUES( 179 , ' Cabernet - Pinotage ');
INSERT INTO Varierity( ID , NAME ) VALUES( 180 , ' Cabernet - Sangiovese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 181 , ' Cabernet - Sangiovese - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 182 , ' Cabernet Sauvignon ');
INSERT INTO Varierity( ID , NAME ) VALUES( 183 , ' Cabernet Sauvignon - Carignan ');
INSERT INTO Varierity( ID , NAME ) VALUES( 184 , ' Cabernet Sauvignon - Carmenere ');
INSERT INTO Varierity( ID , NAME ) VALUES( 185 , ' Cabernet Sauvignon - Cinsaut ');
INSERT INTO Varierity( ID , NAME ) VALUES( 186 , ' Cabernet Sauvignon - Malbec ');
INSERT INTO Varierity( ID , NAME ) VALUES( 187 , ' Cabernet Sauvignon - Merlot ');
INSERT INTO Varierity( ID , NAME ) VALUES( 188 , ' Cabernet Sauvignon - Pinot Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 189 , ' Cabernets - Grolleau ');
INSERT INTO Varierity( ID , NAME ) VALUES( 190 , ' Cabernet - Syrah/Shiraz ');
INSERT INTO Varierity( ID , NAME ) VALUES( 191 , ' Cabernet - Syrah - Tempranillo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 192 , ' Cabernet - Syrah - Zinfandel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 193 , ' Cabernet - Tannat ');
INSERT INTO Varierity( ID , NAME ) VALUES( 194 , ' Cabernet - Tempranillo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 195 , ' Cabernet - Zinfandel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 196 , ' Cab Franc - Gamay - Malbec ');
INSERT INTO Varierity( ID , NAME ) VALUES( 197 , ' Cachaca ');
INSERT INTO Varierity( ID , NAME ) VALUES( 198 , ' Cagnulari ');
INSERT INTO Varierity( ID , NAME ) VALUES( 199 , ' Caino Tinto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 200 , ' Caladoc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 201 , ' Calbanesco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 202 , ' Calitor ');
INSERT INTO Varierity( ID , NAME ) VALUES( 203 , ' Cal Karasi ');
INSERT INTO Varierity( ID , NAME ) VALUES( 204 , ' Callet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 205 , ' Calzin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 206 , ' Camaralet de Lasseube ');
INSERT INTO Varierity( ID , NAME ) VALUES( 207 , ' Camarate ');
INSERT INTO Varierity( ID , NAME ) VALUES( 208 , ' Canaiolo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 209 , ' Canaiolo Bianco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 210 , ' Cannabis Drink ');
INSERT INTO Varierity( ID , NAME ) VALUES( 211 , ' Canocazo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 212 , ' Carcajolo Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 213 , ' Carcajolo Nero ');
INSERT INTO Varierity( ID , NAME ) VALUES( 214 , ' Caricalasino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 215 , ' Carignan Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 216 , ' Carignan (Carinena) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 217 , ' Carignan - Grenache - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 218 , ' Carignan - Grenache - Tempranillo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 219 , ' Carignan Gris ');
INSERT INTO Varierity( ID , NAME ) VALUES( 220 , ' Carignan - Merlot ');
INSERT INTO Varierity( ID , NAME ) VALUES( 221 , ' Carignan - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 222 , ' Carinena - Garnacha ');
INSERT INTO Varierity( ID , NAME ) VALUES( 223 , ' Carmenere ');
INSERT INTO Varierity( ID , NAME ) VALUES( 224 , ' Carmenere - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 225 , ' Carmine ');
INSERT INTO Varierity( ID , NAME ) VALUES( 226 , ' Carminoir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 227 , ' Carnelian ');
INSERT INTO Varierity( ID , NAME ) VALUES( 228 , ' Carrasquin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 229 , ' Carricante ');
INSERT INTO Varierity( ID , NAME ) VALUES( 230 , ' Carricante - Catarratto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 231 , ' Casavecchia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 232 , ' Casetta ');
INSERT INTO Varierity( ID , NAME ) VALUES( 233 , ' Cassady ');
INSERT INTO Varierity( ID , NAME ) VALUES( 234 , ' Castelao ');
INSERT INTO Varierity( ID , NAME ) VALUES( 235 , ' Castelao - Touriga ');
INSERT INTO Varierity( ID , NAME ) VALUES( 236 , ' Catarratto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 237 , ' Catarratto - Chardonnay ');
INSERT INTO Varierity( ID , NAME ) VALUES( 238 , ' Catarratto - Grillo - Inzolia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 239 , ' Catarratto - Inzolia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 240 , ' Catawba ');
INSERT INTO Varierity( ID , NAME ) VALUES( 241 , ' Cava Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 242 , ' Cayetana ');
INSERT INTO Varierity( ID , NAME ) VALUES( 243 , ' Cayuga ');
INSERT INTO Varierity( ID , NAME ) VALUES( 244 , ' Cecubo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 245 , ' Centesimino (Savignon Rosso) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 246 , ' Centurion ');
INSERT INTO Varierity( ID , NAME ) VALUES( 247 , ' Cerceal ');
INSERT INTO Varierity( ID , NAME ) VALUES( 248 , ' Cereza ');
INSERT INTO Varierity( ID , NAME ) VALUES( 249 , ' Cesanese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 250 , ' Cesar ');
INSERT INTO Varierity( ID , NAME ) VALUES( 251 , ' Cetinka ');
INSERT INTO Varierity( ID , NAME ) VALUES( 252 , ' Chambourcin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 253 , ' Champagne Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 254 , ' Chancellor ');
INSERT INTO Varierity( ID , NAME ) VALUES( 255 , ' Charbono (Bonarda) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 256 , ' Chardonel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 257 , ' Chardonnay ');
INSERT INTO Varierity( ID , NAME ) VALUES( 258 , ' Chardonnay - Chenin Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 259 , ' Chardonnay - Colombard ');
INSERT INTO Varierity( ID , NAME ) VALUES( 260 , ' Chardonnay - Garganega ');
INSERT INTO Varierity( ID , NAME ) VALUES( 261 , ' Chardonnay - Gewurztraminer ');
INSERT INTO Varierity( ID , NAME ) VALUES( 262 , ' Chardonnay - Muscat ');
INSERT INTO Varierity( ID , NAME ) VALUES( 263 , ' Chardonnay Musque ');
INSERT INTO Varierity( ID , NAME ) VALUES( 264 , ' Chardonnay - Pinot Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 265 , ' Chardonnay - Pinot Blanc - Pinot Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 266 , ' Chardonnay - Pinot Gris ');
INSERT INTO Varierity( ID , NAME ) VALUES( 267 , ' Chardonnay - Pinot Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 268 , ' Chardonnay - Riesling ');
INSERT INTO Varierity( ID , NAME ) VALUES( 269 , ' Chardonnay Rose ');
INSERT INTO Varierity( ID , NAME ) VALUES( 270 , ' Chardonnay - Roussanne ');
INSERT INTO Varierity( ID , NAME ) VALUES( 271 , ' Chardonnay - Roussanne - Viognier ');
INSERT INTO Varierity( ID , NAME ) VALUES( 272 , ' Chardonnay - Sauvignon Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 273 , ' Chardonnay - Sauvignon - Semillon ');
INSERT INTO Varierity( ID , NAME ) VALUES( 274 , ' Chardonnay - Savagnin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 275 , ' Chardonnay - Semillon ');
INSERT INTO Varierity( ID , NAME ) VALUES( 276 , ' Chardonnay - Torrontes ');
INSERT INTO Varierity( ID , NAME ) VALUES( 277 , ' Chardonnay - Verdelho ');
INSERT INTO Varierity( ID , NAME ) VALUES( 278 , ' Chardonnay - Vermentino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 279 , ' Chardonnay - Viognier ');
INSERT INTO Varierity( ID , NAME ) VALUES( 280 , ' Chardonnay - Viura ');
INSERT INTO Varierity( ID , NAME ) VALUES( 281 , ' Chardonnay - Xarel-lo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 282 , ' Charmont ');
INSERT INTO Varierity( ID , NAME ) VALUES( 283 , ' Chasan ');
INSERT INTO Varierity( ID , NAME ) VALUES( 284 , ' Chasselas ');
INSERT INTO Varierity( ID , NAME ) VALUES( 285 , ' Chelois ');
INSERT INTO Varierity( ID , NAME ) VALUES( 286 , ' Chenanson ');
INSERT INTO Varierity( ID , NAME ) VALUES( 287 , ' Chenel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 288 , ' Chenin Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 289 , ' Chianti Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 290 , ' Cider ');
INSERT INTO Varierity( ID , NAME ) VALUES( 291 , ' Cienna ');
INSERT INTO Varierity( ID , NAME ) VALUES( 292 , ' Ciliegiolo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 293 , ' Cinsaut ');
INSERT INTO Varierity( ID , NAME ) VALUES( 294 , ' Cinsaut - Grenache ');
INSERT INTO Varierity( ID , NAME ) VALUES( 295 , ' Cinsaut - Grenache - Mourvedre ');
INSERT INTO Varierity( ID , NAME ) VALUES( 296 , ' Cinsaut - Grenache - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 297 , ' Cinsaut - Mourvedre ');
INSERT INTO Varierity( ID , NAME ) VALUES( 298 , ' Cinsaut - Mourvedre - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 299 , ' Cinsaut - Pinotage ');
INSERT INTO Varierity( ID , NAME ) VALUES( 300 , ' Cinsaut - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 301 , ' Cividino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 302 , ' Clairette ');
INSERT INTO Varierity( ID , NAME ) VALUES( 303 , ' Clairette - Marsanne ');
INSERT INTO Varierity( ID , NAME ) VALUES( 304 , ' Clairette - Marsanne - Ugni ');
INSERT INTO Varierity( ID , NAME ) VALUES( 305 , ' Clairette - Muscat ');
INSERT INTO Varierity( ID , NAME ) VALUES( 306 , ' Clairette - Rolle ');
INSERT INTO Varierity( ID , NAME ) VALUES( 307 , ' Clairette - Ugni Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 308 , ' Claret de Gers ');
INSERT INTO Varierity( ID , NAME ) VALUES( 309 , ' Clinton ');
INSERT INTO Varierity( ID , NAME ) VALUES( 310 , ' Cococciola ');
INSERT INTO Varierity( ID , NAME ) VALUES( 311 , ' Coda di Volpe ');
INSERT INTO Varierity( ID , NAME ) VALUES( 312 , ' Codega do Larinho ');
INSERT INTO Varierity( ID , NAME ) VALUES( 313 , ' Colombard ');
INSERT INTO Varierity( ID , NAME ) VALUES( 314 , ' Colombard - Folle - Ugni ');
INSERT INTO Varierity( ID , NAME ) VALUES( 315 , ' Colombard - Ugni Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 316 , ' Colorino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 317 , ' Completer ');
INSERT INTO Varierity( ID , NAME ) VALUES( 318 , ' Concord ');
INSERT INTO Varierity( ID , NAME ) VALUES( 319 , ' Corinto Nero ');
INSERT INTO Varierity( ID , NAME ) VALUES( 320 , ' Cornalin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 321 , ' Cornifesto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 322 , ' Corot Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 323 , ' Cortese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 324 , ' Corvina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 325 , ' Corvina - Rondinella ');
INSERT INTO Varierity( ID , NAME ) VALUES( 326 , ' Corvinone ');
INSERT INTO Varierity( ID , NAME ) VALUES( 327 , ' Couderc Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 328 , ' Counoise ');
INSERT INTO Varierity( ID , NAME ) VALUES( 329 , ' Courbu Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 330 , ' Criolla Grande ');
INSERT INTO Varierity( ID , NAME ) VALUES( 331 , ' Croatina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 332 , ' Crouchen (Cape Riesling) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 333 , ' Crovino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 334 , ' Cserszegi Fuszeres ');
INSERT INTO Varierity( ID , NAME ) VALUES( 335 , ' Cygne Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 336 , ' Cyser ');
INSERT INTO Varierity( ID , NAME ) VALUES( 337 , ' Dafni ');
INSERT INTO Varierity( ID , NAME ) VALUES( 338 , ' Damaschino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 339 , ' Dameron ');
INSERT INTO Varierity( ID , NAME ) VALUES( 340 , ' Darnekusa ');
INSERT INTO Varierity( ID , NAME ) VALUES( 341 , ' Debina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 342 , ' Debit ');
INSERT INTO Varierity( ID , NAME ) VALUES( 343 , ' De Chaunac ');
INSERT INTO Varierity( ID , NAME ) VALUES( 344 , ' Delaware ');
INSERT INTO Varierity( ID , NAME ) VALUES( 345 , ' Diamond ');
INSERT INTO Varierity( ID , NAME ) VALUES( 346 , ' Dimiat ');
INSERT INTO Varierity( ID , NAME ) VALUES( 347 , ' Dindarella ');
INSERT INTO Varierity( ID , NAME ) VALUES( 348 , ' Diolinoir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 349 , ' Dobricic ');
INSERT INTO Varierity( ID , NAME ) VALUES( 350 , ' Dolcetto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 351 , ' Domina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 352 , ' Dona Blanca ');
INSERT INTO Varierity( ID , NAME ) VALUES( 353 , ' Donzelinho Branco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 354 , ' Doral ');
INSERT INTO Varierity( ID , NAME ) VALUES( 355 , ' Dornfelder ');
INSERT INTO Varierity( ID , NAME ) VALUES( 356 , ' Dorona di Venezia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 357 , ' Doux d'Henry ');
INSERT INTO Varierity( ID , NAME ) VALUES( 358 , ' Drink Mixer ');
INSERT INTO Varierity( ID , NAME ) VALUES( 359 , ' Dunkelfelder ');
INSERT INTO Varierity( ID , NAME ) VALUES( 360 , ' Duras ');
INSERT INTO Varierity( ID , NAME ) VALUES( 361 , ' Duras - Fer Servadou ');
INSERT INTO Varierity( ID , NAME ) VALUES( 362 , ' Duras - Fer - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 363 , ' Duras - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 364 , ' Durella ');
INSERT INTO Varierity( ID , NAME ) VALUES( 365 , ' Durif - Shiraz ');
INSERT INTO Varierity( ID , NAME ) VALUES( 366 , ' Durize ');
INSERT INTO Varierity( ID , NAME ) VALUES( 367 , ' Dzvelshava ');
INSERT INTO Varierity( ID , NAME ) VALUES( 368 , ' Early Muscat ');
INSERT INTO Varierity( ID , NAME ) VALUES( 369 , ' Eau-de-Vie ');
INSERT INTO Varierity( ID , NAME ) VALUES( 370 , ' Edelweiss ');
INSERT INTO Varierity( ID , NAME ) VALUES( 371 , ' Edelzwicker Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 372 , ' Egiodola ');
INSERT INTO Varierity( ID , NAME ) VALUES( 373 , ' Ehrenfelser ');
INSERT INTO Varierity( ID , NAME ) VALUES( 374 , ' Elbling ');
INSERT INTO Varierity( ID , NAME ) VALUES( 375 , ' Elvira ');
INSERT INTO Varierity( ID , NAME ) VALUES( 376 , ' Emerald Riesling ');
INSERT INTO Varierity( ID , NAME ) VALUES( 377 , ' Emir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 378 , ' Enantio ');
INSERT INTO Varierity( ID , NAME ) VALUES( 379 , ' Encruzado ');
INSERT INTO Varierity( ID , NAME ) VALUES( 380 , ' Erbaluce ');
INSERT INTO Varierity( ID , NAME ) VALUES( 381 , ' Espadeiro ');
INSERT INTO Varierity( ID , NAME ) VALUES( 382 , ' Etraire de l'Adui ');
INSERT INTO Varierity( ID , NAME ) VALUES( 383 , ' Eyholzer ');
INSERT INTO Varierity( ID , NAME ) VALUES( 384 , ' Ezerjo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 385 , ' Faber ');
INSERT INTO Varierity( ID , NAME ) VALUES( 386 , ' Falanghina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 387 , ' Fernao Pires ');
INSERT INTO Varierity( ID , NAME ) VALUES( 388 , ' Fer Servadou ');
INSERT INTO Varierity( ID , NAME ) VALUES( 389 , ' Feteasca Alba ');
INSERT INTO Varierity( ID , NAME ) VALUES( 390 , ' Feteasca Neagra ');
INSERT INTO Varierity( ID , NAME ) VALUES( 391 , ' Feteasca Regala ');
INSERT INTO Varierity( ID , NAME ) VALUES( 392 , ' Fiano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 393 , ' Findling ');
INSERT INTO Varierity( ID , NAME ) VALUES( 394 , ' Flavored - Spiced - Fruit Wine ');
INSERT INTO Varierity( ID , NAME ) VALUES( 395 , ' Flora ');
INSERT INTO Varierity( ID , NAME ) VALUES( 396 , ' Florental ');
INSERT INTO Varierity( ID , NAME ) VALUES( 397 , ' Foglia Tonda ');
INSERT INTO Varierity( ID , NAME ) VALUES( 398 , ' Fogoneu ');
INSERT INTO Varierity( ID , NAME ) VALUES( 399 , ' Folgasao ');
INSERT INTO Varierity( ID , NAME ) VALUES( 400 , ' Folle Blanche ');
INSERT INTO Varierity( ID , NAME ) VALUES( 401 , ' Forastera ');
INSERT INTO Varierity( ID , NAME ) VALUES( 402 , ' Fortana ');
INSERT INTO Varierity( ID , NAME ) VALUES( 403 , ' Francavilla ');
INSERT INTO Varierity( ID , NAME ) VALUES( 404 , ' Franc Noir de la Haute-Saone ');
INSERT INTO Varierity( ID , NAME ) VALUES( 405 , ' Francusa ');
INSERT INTO Varierity( ID , NAME ) VALUES( 406 , ' Frappato ');
INSERT INTO Varierity( ID , NAME ) VALUES( 407 , ' Frappato - Nero d'Avola ');
INSERT INTO Varierity( ID , NAME ) VALUES( 408 , ' Freisa ');
INSERT INTO Varierity( ID , NAME ) VALUES( 409 , ' Freisamer ');
INSERT INTO Varierity( ID , NAME ) VALUES( 410 , ' Friulano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 411 , ' Frontenac ');
INSERT INTO Varierity( ID , NAME ) VALUES( 412 , ' Frontenac Gris ');
INSERT INTO Varierity( ID , NAME ) VALUES( 413 , ' Fruhburgunder ');
INSERT INTO Varierity( ID , NAME ) VALUES( 414 , ' Fruhroter Veltliner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 415 , ' Fumin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 416 , ' Furmint ');
INSERT INTO Varierity( ID , NAME ) VALUES( 417 , ' Gaglioppo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 418 , ' Gaidoura ');
INSERT INTO Varierity( ID , NAME ) VALUES( 419 , ' Gamaret ');
INSERT INTO Varierity( ID , NAME ) VALUES( 420 , ' Gamaret - Garanoir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 421 , ' Gamaret - Garanoir - Pinot Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 422 , ' Gamay ');
INSERT INTO Varierity( ID , NAME ) VALUES( 423 , ' Gamay - Grolleau Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 424 , ' Gamay - Pinot Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 425 , ' Gamay - Poulsard ');
INSERT INTO Varierity( ID , NAME ) VALUES( 426 , ' Gamba di Pernice ');
INSERT INTO Varierity( ID , NAME ) VALUES( 427 , ' Garanoir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 428 , ' Garganega ');
INSERT INTO Varierity( ID , NAME ) VALUES( 429 , ' Garganega - Pinot Grigio ');
INSERT INTO Varierity( ID , NAME ) VALUES( 430 , ' Garnacha - Tempranillo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 431 , ' Garrido ');
INSERT INTO Varierity( ID , NAME ) VALUES( 432 , ' Gellewza ');
INSERT INTO Varierity( ID , NAME ) VALUES( 433 , ' Genever (Jenever) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 434 , ' Gewurztraminer ');
INSERT INTO Varierity( ID , NAME ) VALUES( 435 , ' Gewurztraminer - Riesling ');
INSERT INTO Varierity( ID , NAME ) VALUES( 436 , ' Gin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 437 , ' Gin Liqueur ');
INSERT INTO Varierity( ID , NAME ) VALUES( 438 , ' Girgentina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 439 , ' Giro ');
INSERT INTO Varierity( ID , NAME ) VALUES( 440 , ' Glera (Prosecco) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 441 , ' Godello ');
INSERT INTO Varierity( ID , NAME ) VALUES( 442 , ' Goldburger ');
INSERT INTO Varierity( ID , NAME ) VALUES( 443 , ' Goldriesling ');
INSERT INTO Varierity( ID , NAME ) VALUES( 444 , ' Gouais Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 445 , ' Gouveio ');
INSERT INTO Varierity( ID , NAME ) VALUES( 446 , ' Graciano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 447 , ' Grappa ');
INSERT INTO Varierity( ID , NAME ) VALUES( 448 , ' Grechetto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 449 , ' Grechetto Rosso ');
INSERT INTO Varierity( ID , NAME ) VALUES( 450 , ' Greco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 451 , ' Greco Bianco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 452 , ' Greco Nero ');
INSERT INTO Varierity( ID , NAME ) VALUES( 453 , ' Green Hungarian ');
INSERT INTO Varierity( ID , NAME ) VALUES( 454 , ' Grenache Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 455 , ' Grenache Blanc - Grenache Gris ');
INSERT INTO Varierity( ID , NAME ) VALUES( 456 , ' Grenache Blanc - Vermentino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 457 , ' Grenache (Garnacha) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 458 , ' Grenache Gris ');
INSERT INTO Varierity( ID , NAME ) VALUES( 459 , ' Grenache - Merlot - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 460 , ' Grenache - Mourvedre ');
INSERT INTO Varierity( ID , NAME ) VALUES( 461 , ' Grenache - Mourvedre - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 462 , ' Grenache - Sangiovese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 463 , ' Grenache - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 464 , ' Grignolino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 465 , ' Grillo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 466 , ' Gringet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 467 , ' Grk ');
INSERT INTO Varierity( ID , NAME ) VALUES( 468 , ' Grolleau Gris ');
INSERT INTO Varierity( ID , NAME ) VALUES( 469 , ' Grolleau Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 470 , ' Groppello ');
INSERT INTO Varierity( ID , NAME ) VALUES( 471 , ' Gros Manseng ');
INSERT INTO Varierity( ID , NAME ) VALUES( 472 , ' Gros Manseng - Petit Manseng ');
INSERT INTO Varierity( ID , NAME ) VALUES( 473 , ' Gros Manseng - Sauvignon Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 474 , ' Gros Verdot ');
INSERT INTO Varierity( ID , NAME ) VALUES( 475 , ' Gruner Veltliner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 476 , ' Gutenborner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 477 , ' Happoshu ');
INSERT INTO Varierity( ID , NAME ) VALUES( 478 , ' Hard Seltzer ');
INSERT INTO Varierity( ID , NAME ) VALUES( 479 , ' Harslevelu ');
INSERT INTO Varierity( ID , NAME ) VALUES( 480 , ' Helfensteiner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 481 , ' Heroldrebe ');
INSERT INTO Varierity( ID , NAME ) VALUES( 482 , ' Himbertscha ');
INSERT INTO Varierity( ID , NAME ) VALUES( 483 , ' Hondarrabi Beltza ');
INSERT INTO Varierity( ID , NAME ) VALUES( 484 , ' Hondarrabi Zuri ');
INSERT INTO Varierity( ID , NAME ) VALUES( 485 , ' Honey ');
INSERT INTO Varierity( ID , NAME ) VALUES( 486 , ' Humagne Blanche ');
INSERT INTO Varierity( ID , NAME ) VALUES( 487 , ' Humagne Rouge ');
INSERT INTO Varierity( ID , NAME ) VALUES( 488 , ' Huxelrebe ');
INSERT INTO Varierity( ID , NAME ) VALUES( 489 , ' Inzolia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 490 , ' Irsay Oliver ');
INSERT INTO Varierity( ID , NAME ) VALUES( 491 , ' Isabella ');
INSERT INTO Varierity( ID , NAME ) VALUES( 492 , ' Ives ');
INSERT INTO Varierity( ID , NAME ) VALUES( 493 , ' Jacquere ');
INSERT INTO Varierity( ID , NAME ) VALUES( 494 , ' Jampal ');
INSERT INTO Varierity( ID , NAME ) VALUES( 495 , ' Johanniter ');
INSERT INTO Varierity( ID , NAME ) VALUES( 496 , ' Joubertin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 497 , ' Juan Garcia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 498 , ' Juhfark ');
INSERT INTO Varierity( ID , NAME ) VALUES( 499 , ' Jurancon Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 500 , ' Jurancon Noir (Folle Noire) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 501 , ' Juwel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 502 , ' Kabar ');
INSERT INTO Varierity( ID , NAME ) VALUES( 503 , ' Kadarka Blau ');
INSERT INTO Varierity( ID , NAME ) VALUES( 504 , ' Kalecik Karasi ');
INSERT INTO Varierity( ID , NAME ) VALUES( 505 , ' Kanzler ');
INSERT INTO Varierity( ID , NAME ) VALUES( 506 , ' Karasakiz ');
INSERT INTO Varierity( ID , NAME ) VALUES( 507 , ' Katsano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 508 , ' Keduretuli (Mujuretuli) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 509 , ' Kekmedoc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 510 , ' Keknyelu ');
INSERT INTO Varierity( ID , NAME ) VALUES( 511 , ' Kerner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 512 , ' Kombucha ');
INSERT INTO Varierity( ID , NAME ) VALUES( 513 , ' Koshu ');
INSERT INTO Varierity( ID , NAME ) VALUES( 514 , ' Kotsifali ');
INSERT INTO Varierity( ID , NAME ) VALUES( 515 , ' Kotsifali - Mandilaria ');
INSERT INTO Varierity( ID , NAME ) VALUES( 516 , ' Koverszolo (Grasa de Cotnari) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 517 , ' Kovidinka ');
INSERT INTO Varierity( ID , NAME ) VALUES( 518 , ' Krakhuna ');
INSERT INTO Varierity( ID , NAME ) VALUES( 519 , ' Krassato ');
INSERT INTO Varierity( ID , NAME ) VALUES( 520 , ' Kuldzhinskii (Kouldjinka) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 521 , ' La Crescent ');
INSERT INTO Varierity( ID , NAME ) VALUES( 522 , ' Lacrima ');
INSERT INTO Varierity( ID , NAME ) VALUES( 523 , ' La Crosse ');
INSERT INTO Varierity( ID , NAME ) VALUES( 524 , ' Lado ');
INSERT INTO Varierity( ID , NAME ) VALUES( 525 , ' Lagorthi ');
INSERT INTO Varierity( ID , NAME ) VALUES( 526 , ' Lagrein ');
INSERT INTO Varierity( ID , NAME ) VALUES( 527 , ' Lambrusco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 528 , ' Landot Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 529 , ' Lasin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 530 , ' Lauzet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 531 , ' Leanyka ');
INSERT INTO Varierity( ID , NAME ) VALUES( 532 , ' Lemberger - Trollinger ');
INSERT INTO Varierity( ID , NAME ) VALUES( 533 , ' Len de l'El ');
INSERT INTO Varierity( ID , NAME ) VALUES( 534 , ' Len de l'El - Mauzac ');
INSERT INTO Varierity( ID , NAME ) VALUES( 535 , ' Leon Millot ');
INSERT INTO Varierity( ID , NAME ) VALUES( 536 , ' Liatiko ');
INSERT INTO Varierity( ID , NAME ) VALUES( 537 , ' Liebfraumilch ');
INSERT INTO Varierity( ID , NAME ) VALUES( 538 , ' Limnio ');
INSERT INTO Varierity( ID , NAME ) VALUES( 539 , ' Liqueur ');
INSERT INTO Varierity( ID , NAME ) VALUES( 540 , ' Liqueur - Anise ');
INSERT INTO Varierity( ID , NAME ) VALUES( 541 , ' Liqueur - Chocolate ');
INSERT INTO Varierity( ID , NAME ) VALUES( 542 , ' Liqueur - Coffee ');
INSERT INTO Varierity( ID , NAME ) VALUES( 543 , ' Liqueur - Cream ');
INSERT INTO Varierity( ID , NAME ) VALUES( 544 , ' Liqueur - Egg ');
INSERT INTO Varierity( ID , NAME ) VALUES( 545 , ' Liqueur - Fruit ');
INSERT INTO Varierity( ID , NAME ) VALUES( 546 , ' Liqueur - Herb - Spice ');
INSERT INTO Varierity( ID , NAME ) VALUES( 547 , ' Liqueur - Nut ');
INSERT INTO Varierity( ID , NAME ) VALUES( 548 , ' Liqueur - Toffee ');
INSERT INTO Varierity( ID , NAME ) VALUES( 549 , ' Listan Negro ');
INSERT INTO Varierity( ID , NAME ) VALUES( 550 , ' Lledoner Pelut ');
INSERT INTO Varierity( ID , NAME ) VALUES( 551 , ' Loureiro ');
INSERT INTO Varierity( ID , NAME ) VALUES( 552 , ' Lucie Kuhlmann ');
INSERT INTO Varierity( ID , NAME ) VALUES( 553 , ' Luglienga Bianca ');
INSERT INTO Varierity( ID , NAME ) VALUES( 554 , ' Lumassina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 555 , ' Macabeo - Parellada - Xarel-lo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 556 , ' Macabeo (Viura) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 557 , ' Maceratino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 558 , ' Madeleine Angevine ');
INSERT INTO Varierity( ID , NAME ) VALUES( 559 , ' Magliocco Canino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 560 , ' Majarca Alba ');
INSERT INTO Varierity( ID , NAME ) VALUES( 561 , ' Makgeolli ');
INSERT INTO Varierity( ID , NAME ) VALUES( 562 , ' Malagousia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 563 , ' Malbec ');
INSERT INTO Varierity( ID , NAME ) VALUES( 564 , ' Malbec - Merlot ');
INSERT INTO Varierity( ID , NAME ) VALUES( 565 , ' Malbec - Merlot - Tannat ');
INSERT INTO Varierity( ID , NAME ) VALUES( 566 , ' Malbec - Pinot Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 567 , ' Malbec - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 568 , ' Malbo Gentile ');
INSERT INTO Varierity( ID , NAME ) VALUES( 569 , ' Malt Beverage ');
INSERT INTO Varierity( ID , NAME ) VALUES( 570 , ' Malvar ');
INSERT INTO Varierity( ID , NAME ) VALUES( 571 , ' Malvasia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 572 , ' Malvasia Bianca ');
INSERT INTO Varierity( ID , NAME ) VALUES( 573 , ' Malvasia di Candia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 574 , ' Malvasia Nera ');
INSERT INTO Varierity( ID , NAME ) VALUES( 575 , ' Malvasia Nera - Negroamaro ');
INSERT INTO Varierity( ID , NAME ) VALUES( 576 , ' Malvasia - Trebbiano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 577 , ' Mandilaria (Amorghiano) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 578 , ' Mansengs - Petit Courbu ');
INSERT INTO Varierity( ID , NAME ) VALUES( 579 , ' Manto Negro ');
INSERT INTO Varierity( ID , NAME ) VALUES( 580 , ' Mantonico Bianco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 581 , ' Manzoni Bianco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 582 , ' Marastina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 583 , ' Maratheftiko ');
INSERT INTO Varierity( ID , NAME ) VALUES( 584 , ' Marechal Foch ');
INSERT INTO Varierity( ID , NAME ) VALUES( 585 , ' Marmajuelo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 586 , ' Marquette ');
INSERT INTO Varierity( ID , NAME ) VALUES( 587 , ' Marsanne ');
INSERT INTO Varierity( ID , NAME ) VALUES( 588 , ' Marsanne - Roussanne ');
INSERT INTO Varierity( ID , NAME ) VALUES( 589 , ' Marselan ');
INSERT INTO Varierity( ID , NAME ) VALUES( 590 , ' Marzemino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 591 , ' Matrassa ');
INSERT INTO Varierity( ID , NAME ) VALUES( 592 , ' Maturana Blanca ');
INSERT INTO Varierity( ID , NAME ) VALUES( 593 , ' Maturana Tinta ');
INSERT INTO Varierity( ID , NAME ) VALUES( 594 , ' Mauzac ');
INSERT INTO Varierity( ID , NAME ) VALUES( 595 , ' Mavro ');
INSERT INTO Varierity( ID , NAME ) VALUES( 596 , ' Mavrodaphne ');
INSERT INTO Varierity( ID , NAME ) VALUES( 597 , ' Mavrotragano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 598 , ' Mavrud ');
INSERT INTO Varierity( ID , NAME ) VALUES( 599 , ' Mayolet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 600 , ' Melara ');
INSERT INTO Varierity( ID , NAME ) VALUES( 601 , ' Melnik ');
INSERT INTO Varierity( ID , NAME ) VALUES( 602 , ' Melody ');
INSERT INTO Varierity( ID , NAME ) VALUES( 603 , ' Melomel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 604 , ' Melon de Bourgogne ');
INSERT INTO Varierity( ID , NAME ) VALUES( 605 , ' Melon Queue Rouge ');
INSERT INTO Varierity( ID , NAME ) VALUES( 606 , ' Mencia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 607 , ' Merille ');
INSERT INTO Varierity( ID , NAME ) VALUES( 608 , ' Meritage ');
INSERT INTO Varierity( ID , NAME ) VALUES( 609 , ' Merlot ');
INSERT INTO Varierity( ID , NAME ) VALUES( 610 , ' Merlot Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 611 , ' Merlot - Montepulciano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 612 , ' Merlot - Nero d'Avola ');
INSERT INTO Varierity( ID , NAME ) VALUES( 613 , ' Merlot - Sagrantino - Sangiovese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 614 , ' Merlot - Sangiovese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 615 , ' Merlot - Sangiovese - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 616 , ' Merlot - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 617 , ' Merlot - Tannat ');
INSERT INTO Varierity( ID , NAME ) VALUES( 618 , ' Merlot - Tempranillo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 619 , ' Merseguera ');
INSERT INTO Varierity( ID , NAME ) VALUES( 620 , ' Merwah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 621 , ' Merzling ');
INSERT INTO Varierity( ID , NAME ) VALUES( 622 , ' Mezcal ');
INSERT INTO Varierity( ID , NAME ) VALUES( 623 , ' Milgranet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 624 , ' Minhota ');
INSERT INTO Varierity( ID , NAME ) VALUES( 625 , ' Minnella ');
INSERT INTO Varierity( ID , NAME ) VALUES( 626 , ' Mischurnitz ');
INSERT INTO Varierity( ID , NAME ) VALUES( 627 , ' Miss Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 628 , ' Molinara ');
INSERT INTO Varierity( ID , NAME ) VALUES( 629 , ' Moll ');
INSERT INTO Varierity( ID , NAME ) VALUES( 630 , ' Monastrell - Tempranillo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 631 , ' Mondeuse Blanche ');
INSERT INTO Varierity( ID , NAME ) VALUES( 632 , ' Mondeuse Noire ');
INSERT INTO Varierity( ID , NAME ) VALUES( 633 , ' Monica ');
INSERT INTO Varierity( ID , NAME ) VALUES( 634 , ' Montepulciano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 635 , ' Montepulciano - Sangiovese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 636 , ' Montepulciano - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 637 , ' Montonega ');
INSERT INTO Varierity( ID , NAME ) VALUES( 638 , ' Montuni ');
INSERT INTO Varierity( ID , NAME ) VALUES( 639 , ' Moravia Agria ');
INSERT INTO Varierity( ID , NAME ) VALUES( 640 , ' Moreto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 641 , ' Morio-Muskat ');
INSERT INTO Varierity( ID , NAME ) VALUES( 642 , ' Moristel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 643 , ' Moscato Giallo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 644 , ' Moscato Rosa ');
INSERT INTO Varierity( ID , NAME ) VALUES( 645 , ' Moschofilero ');
INSERT INTO Varierity( ID , NAME ) VALUES( 646 , ' Moschofilero - Roditis ');
INSERT INTO Varierity( ID , NAME ) VALUES( 647 , ' Mourisco Tinto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 648 , ' Mourvedre (Monastrell) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 649 , ' Mourvedre - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 650 , ' Mtsvani ');
INSERT INTO Varierity( ID , NAME ) VALUES( 651 , ' Muller-Thurgau ');
INSERT INTO Varierity( ID , NAME ) VALUES( 652 , ' Muscadelle ');
INSERT INTO Varierity( ID , NAME ) VALUES( 653 , ' Muscadine ');
INSERT INTO Varierity( ID , NAME ) VALUES( 654 , ' Muscardin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 655 , ' Muscat ');
INSERT INTO Varierity( ID , NAME ) VALUES( 656 , ' Muscat Bailey A ');
INSERT INTO Varierity( ID , NAME ) VALUES( 657 , ' Muscat Blanc a Petits Grains ');
INSERT INTO Varierity( ID , NAME ) VALUES( 658 , ' Muscat Hamburg (Muskat Trollinger) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 659 , ' Muscat of Alexandria ');
INSERT INTO Varierity( ID , NAME ) VALUES( 660 , ' Muscat Ottonel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 661 , ' Muscat - Viognier ');
INSERT INTO Varierity( ID , NAME ) VALUES( 662 , ' Muskat Moravsky ');
INSERT INTO Varierity( ID , NAME ) VALUES( 663 , ' Narince ');
INSERT INTO Varierity( ID , NAME ) VALUES( 664 , ' Nascetta ');
INSERT INTO Varierity( ID , NAME ) VALUES( 665 , ' Nasco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 666 , ' Nebbiolo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 667 , ' Negoska ');
INSERT INTO Varierity( ID , NAME ) VALUES( 668 , ' Negrara ');
INSERT INTO Varierity( ID , NAME ) VALUES( 669 , ' Negrette ');
INSERT INTO Varierity( ID , NAME ) VALUES( 670 , ' Negroamaro ');
INSERT INTO Varierity( ID , NAME ) VALUES( 671 , ' Negroamaro - Primitivo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 672 , ' Nerello Cappuccio ');
INSERT INTO Varierity( ID , NAME ) VALUES( 673 , ' Nerello Cappuccio - Nerello Mascalese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 674 , ' Nerello Mascalese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 675 , ' Nero Buono ');
INSERT INTO Varierity( ID , NAME ) VALUES( 676 , ' Nero d'Avola ');
INSERT INTO Varierity( ID , NAME ) VALUES( 677 , ' Nero d'Avola - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 678 , ' Neuburger ');
INSERT INTO Varierity( ID , NAME ) VALUES( 679 , ' New-make Spirit ');
INSERT INTO Varierity( ID , NAME ) VALUES( 680 , ' Neyret ');
INSERT INTO Varierity( ID , NAME ) VALUES( 681 , ' Niagara ');
INSERT INTO Varierity( ID , NAME ) VALUES( 682 , ' Nielluccio - Sciaccarello ');
INSERT INTO Varierity( ID , NAME ) VALUES( 683 , ' Nincusa ');
INSERT INTO Varierity( ID , NAME ) VALUES( 684 , ' Noah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 685 , ' Noblessa ');
INSERT INTO Varierity( ID , NAME ) VALUES( 686 , ' Nobling ');
INSERT INTO Varierity( ID , NAME ) VALUES( 687 , ' Nocera ');
INSERT INTO Varierity( ID , NAME ) VALUES( 688 , ' Noiret ');
INSERT INTO Varierity( ID , NAME ) VALUES( 689 , ' Norton ');
INSERT INTO Varierity( ID , NAME ) VALUES( 690 , ' Nosiola ');
INSERT INTO Varierity( ID , NAME ) VALUES( 691 , ' Nuragus ');
INSERT INTO Varierity( ID , NAME ) VALUES( 692 , ' Obaideh ');
INSERT INTO Varierity( ID , NAME ) VALUES( 693 , ' Ojaleshi ');
INSERT INTO Varierity( ID , NAME ) VALUES( 694 , ' Okuzgozu ');
INSERT INTO Varierity( ID , NAME ) VALUES( 695 , ' Olivella ');
INSERT INTO Varierity( ID , NAME ) VALUES( 696 , ' Ondenc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 697 , ' Opthalmo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 698 , ' Optima ');
INSERT INTO Varierity( ID , NAME ) VALUES( 699 , ' Orion ');
INSERT INTO Varierity( ID , NAME ) VALUES( 700 , ' Orleans ');
INSERT INTO Varierity( ID , NAME ) VALUES( 701 , ' Ortega ');
INSERT INTO Varierity( ID , NAME ) VALUES( 702 , ' Ortrugo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 703 , ' Orvieto Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 704 , ' Oseleta ');
INSERT INTO Varierity( ID , NAME ) VALUES( 705 , ' Osiris ');
INSERT INTO Varierity( ID , NAME ) VALUES( 706 , ' Osteiner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 707 , ' Pais (Mission) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 708 , ' Palas ');
INSERT INTO Varierity( ID , NAME ) VALUES( 709 , ' Palava ');
INSERT INTO Varierity( ID , NAME ) VALUES( 710 , ' Pallagrello Bianco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 711 , ' Pallagrello Nero ');
INSERT INTO Varierity( ID , NAME ) VALUES( 712 , ' Palomino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 713 , ' Pamid ');
INSERT INTO Varierity( ID , NAME ) VALUES( 714 , ' Pampanuto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 715 , ' Papazkarasi ');
INSERT INTO Varierity( ID , NAME ) VALUES( 716 , ' Parc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 717 , ' Parellada ');
INSERT INTO Varierity( ID , NAME ) VALUES( 718 , ' Parraleta ');
INSERT INTO Varierity( ID , NAME ) VALUES( 719 , ' Pascal Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 720 , ' Passerina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 721 , ' Passerina - Pecorino - Trebbiano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 722 , ' Pecorino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 723 , ' Pedral ');
INSERT INTO Varierity( ID , NAME ) VALUES( 724 , ' Pedro Ximenez ');
INSERT INTO Varierity( ID , NAME ) VALUES( 725 , ' Pelaverga ');
INSERT INTO Varierity( ID , NAME ) VALUES( 726 , ' Peloursin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 727 , ' Perdea ');
INSERT INTO Varierity( ID , NAME ) VALUES( 728 , ' Perle ');
INSERT INTO Varierity( ID , NAME ) VALUES( 729 , ' Perricone ');
INSERT INTO Varierity( ID , NAME ) VALUES( 730 , ' Persan ');
INSERT INTO Varierity( ID , NAME ) VALUES( 731 , ' Petit Bouschet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 732 , ' Petit Courbu ');
INSERT INTO Varierity( ID , NAME ) VALUES( 733 , ' Petite Arvine ');
INSERT INTO Varierity( ID , NAME ) VALUES( 734 , ' Petite Sirah (Durif) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 735 , ' Petite Sirah - Syrah - Zinfandel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 736 , ' Petite Sirah - Zinfandel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 737 , ' Petit Manseng ');
INSERT INTO Varierity( ID , NAME ) VALUES( 738 , ' Petit Meslier ');
INSERT INTO Varierity( ID , NAME ) VALUES( 739 , ' Petit Rouge ');
INSERT INTO Varierity( ID , NAME ) VALUES( 740 , ' Petit Verdot ');
INSERT INTO Varierity( ID , NAME ) VALUES( 741 , ' Petroulianos ');
INSERT INTO Varierity( ID , NAME ) VALUES( 742 , ' Peurion ');
INSERT INTO Varierity( ID , NAME ) VALUES( 743 , ' Phoenix ');
INSERT INTO Varierity( ID , NAME ) VALUES( 744 , ' Piccola Nera ');
INSERT INTO Varierity( ID , NAME ) VALUES( 745 , ' Picolit ');
INSERT INTO Varierity( ID , NAME ) VALUES( 746 , ' Picpoul ');
INSERT INTO Varierity( ID , NAME ) VALUES( 747 , ' Picpoul Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 748 , ' Piculit Neri ');
INSERT INTO Varierity( ID , NAME ) VALUES( 749 , ' Piedirosso ');
INSERT INTO Varierity( ID , NAME ) VALUES( 750 , ' Pignerol ');
INSERT INTO Varierity( ID , NAME ) VALUES( 751 , ' Pignola ');
INSERT INTO Varierity( ID , NAME ) VALUES( 752 , ' Pignolo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 753 , ' Pinard ');
INSERT INTO Varierity( ID , NAME ) VALUES( 754 , ' Pineau d'Aunis ');
INSERT INTO Varierity( ID , NAME ) VALUES( 755 , ' Pinella (Pinello) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 756 , ' Pink Gin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 757 , ' Pinotage ');
INSERT INTO Varierity( ID , NAME ) VALUES( 758 , ' Pinotage - Shiraz ');
INSERT INTO Varierity( ID , NAME ) VALUES( 759 , ' Pinot Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 760 , ' Pinot Blanc - Pinot Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 761 , ' Pinot d'Alsace ');
INSERT INTO Varierity( ID , NAME ) VALUES( 762 , ' Pinot Grigio ');
INSERT INTO Varierity( ID , NAME ) VALUES( 763 , ' Pinot Grigio - Zibibbo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 764 , ' Pinot Gris ');
INSERT INTO Varierity( ID , NAME ) VALUES( 765 , ' Pinot Gris - Sauvignon Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 766 , ' Pinot Meunier ');
INSERT INTO Varierity( ID , NAME ) VALUES( 767 , ' Pinot Meunier - Pinot Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 768 , ' Pinot Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 769 , ' Pinot Noir - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 770 , ' Pinot Noir - Zweigelt ');
INSERT INTO Varierity( ID , NAME ) VALUES( 771 , ' Pinot - Poulsard - Trousseau ');
INSERT INTO Varierity( ID , NAME ) VALUES( 772 , ' Pisco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 773 , ' Planta Fina de Pedralba ');
INSERT INTO Varierity( ID , NAME ) VALUES( 774 , ' Planta Nova ');
INSERT INTO Varierity( ID , NAME ) VALUES( 775 , ' Plantet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 776 , ' Plavac Mali ');
INSERT INTO Varierity( ID , NAME ) VALUES( 777 , ' Plavac Veli ');
INSERT INTO Varierity( ID , NAME ) VALUES( 778 , ' Plavina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 779 , ' Plyto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 780 , ' Pollera Nera ');
INSERT INTO Varierity( ID , NAME ) VALUES( 781 , ' Pontac ');
INSERT INTO Varierity( ID , NAME ) VALUES( 782 , ' Portan ');
INSERT INTO Varierity( ID , NAME ) VALUES( 783 , ' Port Blend Red ');
INSERT INTO Varierity( ID , NAME ) VALUES( 784 , ' Port Blend White ');
INSERT INTO Varierity( ID , NAME ) VALUES( 785 , ' Portugieser ');
INSERT INTO Varierity( ID , NAME ) VALUES( 786 , ' Portuguese Red Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 787 , ' Portuguese White Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 788 , ' Posip ');
INSERT INTO Varierity( ID , NAME ) VALUES( 789 , ' Poulsard ');
INSERT INTO Varierity( ID , NAME ) VALUES( 790 , ' Precoce de Malingre ');
INSERT INTO Varierity( ID , NAME ) VALUES( 791 , ' Premetta ');
INSERT INTO Varierity( ID , NAME ) VALUES( 792 , ' Premixed Drinks ');
INSERT INTO Varierity( ID , NAME ) VALUES( 793 , ' Prie Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 794 , ' Prieto Picudo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 795 , ' Primitivo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 796 , ' Prokupac ');
INSERT INTO Varierity( ID , NAME ) VALUES( 797 , ' Prunelard Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 798 , ' Prunelard Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 799 , ' Pugnitello ');
INSERT INTO Varierity( ID , NAME ) VALUES( 800 , ' Quagliano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 801 , ' Rabo de Ovelha ');
INSERT INTO Varierity( ID , NAME ) VALUES( 802 , ' Raboso ');
INSERT INTO Varierity( ID , NAME ) VALUES( 803 , ' Radler-Shandy ');
INSERT INTO Varierity( ID , NAME ) VALUES( 804 , ' Raffiat de Moncade ');
INSERT INTO Varierity( ID , NAME ) VALUES( 805 , ' Ramisco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 806 , ' Rare Red Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 807 , ' Rare Rose Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 808 , ' Rare White Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 809 , ' Rassegui ');
INSERT INTO Varierity( ID , NAME ) VALUES( 810 , ' Ratafia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 811 , ' Rathay ');
INSERT INTO Varierity( ID , NAME ) VALUES( 812 , ' Rauschling ');
INSERT INTO Varierity( ID , NAME ) VALUES( 813 , ' Ravat Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 814 , ' Ravat Vignoles ');
INSERT INTO Varierity( ID , NAME ) VALUES( 815 , ' Rayon d'Or ');
INSERT INTO Varierity( ID , NAME ) VALUES( 816 , ' Rebo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 817 , ' Refosco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 818 , ' Regent ');
INSERT INTO Varierity( ID , NAME ) VALUES( 819 , ' Regner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 820 , ' Reichensteiner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 821 , ' Reze ');
INSERT INTO Varierity( ID , NAME ) VALUES( 822 , ' Ribolla ');
INSERT INTO Varierity( ID , NAME ) VALUES( 823 , ' Rieslaner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 824 , ' Riesling ');
INSERT INTO Varierity( ID , NAME ) VALUES( 825 , ' Riesling - Silvaner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 826 , ' Rioja Red Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 827 , ' Rioja White Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 828 , ' Rkatsiteli ');
INSERT INTO Varierity( ID , NAME ) VALUES( 829 , ' Robola ');
INSERT INTO Varierity( ID , NAME ) VALUES( 830 , ' Roditis ');
INSERT INTO Varierity( ID , NAME ) VALUES( 831 , ' Roesler ');
INSERT INTO Varierity( ID , NAME ) VALUES( 832 , ' Rolle - Ugni Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 833 , ' Romorantin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 834 , ' Rondinella ');
INSERT INTO Varierity( ID , NAME ) VALUES( 835 , ' Rondo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 836 , ' Roscetto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 837 , ' Rossara ');
INSERT INTO Varierity( ID , NAME ) VALUES( 838 , ' Rossese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 839 , ' Rossola Nera ');
INSERT INTO Varierity( ID , NAME ) VALUES( 840 , ' Rotberger ');
INSERT INTO Varierity( ID , NAME ) VALUES( 841 , ' Roter Gutedel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 842 , ' Roter Riesling ');
INSERT INTO Varierity( ID , NAME ) VALUES( 843 , ' Roter Traminer (Savagnin Rose) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 844 , ' Roter Veltliner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 845 , ' Rotgipfler ');
INSERT INTO Varierity( ID , NAME ) VALUES( 846 , ' Rougeon ');
INSERT INTO Varierity( ID , NAME ) VALUES( 847 , ' Roussanne ');
INSERT INTO Varierity( ID , NAME ) VALUES( 848 , ' Roussanne - Viognier ');
INSERT INTO Varierity( ID , NAME ) VALUES( 849 , ' Royalty ');
INSERT INTO Varierity( ID , NAME ) VALUES( 850 , ' Rubienne ');
INSERT INTO Varierity( ID , NAME ) VALUES( 851 , ' Rubin Bolgarskii ');
INSERT INTO Varierity( ID , NAME ) VALUES( 852 , ' Rubired ');
INSERT INTO Varierity( ID , NAME ) VALUES( 853 , ' Ruby Cabernet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 854 , ' Ruche ');
INSERT INTO Varierity( ID , NAME ) VALUES( 855 , ' Rufete (Tinta Pinheira) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 856 , ' Rum ');
INSERT INTO Varierity( ID , NAME ) VALUES( 857 , ' Rum - Liqueur - Flavored ');
INSERT INTO Varierity( ID , NAME ) VALUES( 858 , ' Sacy ');
INSERT INTO Varierity( ID , NAME ) VALUES( 859 , ' Sagrantino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 860 , ' Sagrantino - Sangiovese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 861 , ' Saint-Croix ');
INSERT INTO Varierity( ID , NAME ) VALUES( 862 , ' Saint-Jeannet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 863 , ' Saint-Macaire ');
INSERT INTO Varierity( ID , NAME ) VALUES( 864 , ' Saint-Pepin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 865 , ' Sake ');
INSERT INTO Varierity( ID , NAME ) VALUES( 866 , ' Samtrot ');
INSERT INTO Varierity( ID , NAME ) VALUES( 867 , ' Sangiovese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 868 , ' Sangiovese - Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 869 , ' Sangria ');
INSERT INTO Varierity( ID , NAME ) VALUES( 870 , ' Sankt Laurent ');
INSERT INTO Varierity( ID , NAME ) VALUES( 871 , ' Santa Maria ');
INSERT INTO Varierity( ID , NAME ) VALUES( 872 , ' Saperavi ');
INSERT INTO Varierity( ID , NAME ) VALUES( 873 , ' Sauvignon Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 874 , ' Sauvignon Blanc - Semillon ');
INSERT INTO Varierity( ID , NAME ) VALUES( 875 , ' Sauvignon Blanc - Ugni Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 876 , ' Sauvignon Blanc - Verdejo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 877 , ' Sauvignon Blanc - Vermentino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 878 , ' Sauvignon Blanc - Viognier ');
INSERT INTO Varierity( ID , NAME ) VALUES( 879 , ' Sauvignon Gris ');
INSERT INTO Varierity( ID , NAME ) VALUES( 880 , ' Savagnin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 881 , ' Savatiano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 882 , ' Scheurebe ');
INSERT INTO Varierity( ID , NAME ) VALUES( 883 , ' Schiava ');
INSERT INTO Varierity( ID , NAME ) VALUES( 884 , ' Schioppettino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 885 , ' Schnapps ');
INSERT INTO Varierity( ID , NAME ) VALUES( 886 , ' Schonburger ');
INSERT INTO Varierity( ID , NAME ) VALUES( 887 , ' Sciaccarello (Mammolo) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 888 , ' Scuppernong ');
INSERT INTO Varierity( ID , NAME ) VALUES( 889 , ' Semidano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 890 , ' Semillon ');
INSERT INTO Varierity( ID , NAME ) VALUES( 891 , ' Semillon - Rolle ');
INSERT INTO Varierity( ID , NAME ) VALUES( 892 , ' Sercial ');
INSERT INTO Varierity( ID , NAME ) VALUES( 893 , ' Seyval Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 894 , ' Sgavetta ');
INSERT INTO Varierity( ID , NAME ) VALUES( 895 , ' Sherry Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 896 , ' Shiraz ');
INSERT INTO Varierity( ID , NAME ) VALUES( 897 , ' Shochu ');
INSERT INTO Varierity( ID , NAME ) VALUES( 898 , ' Sideritis ');
INSERT INTO Varierity( ID , NAME ) VALUES( 899 , ' Siegerrebe ');
INSERT INTO Varierity( ID , NAME ) VALUES( 900 , ' Silcher ');
INSERT INTO Varierity( ID , NAME ) VALUES( 901 , ' Silvaner ');
INSERT INTO Varierity( ID , NAME ) VALUES( 902 , ' Siria (Roupeiro) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 903 , ' Skrlet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 904 , ' Smederevka ');
INSERT INTO Varierity( ID , NAME ) VALUES( 905 , ' Soave Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 906 , ' Soju ');
INSERT INTO Varierity( ID , NAME ) VALUES( 907 , ' Solaris ');
INSERT INTO Varierity( ID , NAME ) VALUES( 908 , ' Sotol ');
INSERT INTO Varierity( ID , NAME ) VALUES( 909 , ' Southern Rhone Red Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 910 , ' Southern Rhone White Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 911 , ' Spergola ');
INSERT INTO Varierity( ID , NAME ) VALUES( 912 , ' Stavroto ');
INSERT INTO Varierity( ID , NAME ) VALUES( 913 , ' Steuben ');
INSERT INTO Varierity( ID , NAME ) VALUES( 914 , ' Sultana ');
INSERT INTO Varierity( ID , NAME ) VALUES( 915 , ' Sumoll ');
INSERT INTO Varierity( ID , NAME ) VALUES( 916 , ' Sumoll Blanco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 917 , ' Susumaniello ');
INSERT INTO Varierity( ID , NAME ) VALUES( 918 , ' Symphony ');
INSERT INTO Varierity( ID , NAME ) VALUES( 919 , ' Syrah ');
INSERT INTO Varierity( ID , NAME ) VALUES( 920 , ' Syrah - Tempranillo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 921 , ' Syrah - Touriga ');
INSERT INTO Varierity( ID , NAME ) VALUES( 922 , ' Syrah - Viognier ');
INSERT INTO Varierity( ID , NAME ) VALUES( 923 , ' Syrah - Zinfandel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 924 , ' Szagos Feher ');
INSERT INTO Varierity( ID , NAME ) VALUES( 925 , ' Taminga ');
INSERT INTO Varierity( ID , NAME ) VALUES( 926 , ' Tannat ');
INSERT INTO Varierity( ID , NAME ) VALUES( 927 , ' Tarrango ');
INSERT INTO Varierity( ID , NAME ) VALUES( 928 , ' Tavkveri ');
INSERT INTO Varierity( ID , NAME ) VALUES( 929 , ' Tazzelenghe ');
INSERT INTO Varierity( ID , NAME ) VALUES( 930 , ' Tempranillo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 931 , ' Tempranillo Blanco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 932 , ' Tequila ');
INSERT INTO Varierity( ID , NAME ) VALUES( 933 , ' Teroldego ');
INSERT INTO Varierity( ID , NAME ) VALUES( 934 , ' Terrantez ');
INSERT INTO Varierity( ID , NAME ) VALUES( 935 , ' Terret Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 936 , ' Terret Gris ');
INSERT INTO Varierity( ID , NAME ) VALUES( 937 , ' Terret Noir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 938 , ' Tibouren ');
INSERT INTO Varierity( ID , NAME ) VALUES( 939 , ' Timorasso ');
INSERT INTO Varierity( ID , NAME ) VALUES( 940 , ' Tinta Amarela (Trincadeira) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 941 , ' Tinta Barroca ');
INSERT INTO Varierity( ID , NAME ) VALUES( 942 , ' Tinta Barroca - Tinta Roriz - Touriga ');
INSERT INTO Varierity( ID , NAME ) VALUES( 943 , ' Tinta Caiada ');
INSERT INTO Varierity( ID , NAME ) VALUES( 944 , ' Tinta Carvalha ');
INSERT INTO Varierity( ID , NAME ) VALUES( 945 , ' Tinta Francisca ');
INSERT INTO Varierity( ID , NAME ) VALUES( 946 , ' Tinta Negra Mole ');
INSERT INTO Varierity( ID , NAME ) VALUES( 947 , ' Tinta Roriz (Aragonez) - Touriga ');
INSERT INTO Varierity( ID , NAME ) VALUES( 948 , ' Tinta Roriz - Tinto Cao - Touriga ');
INSERT INTO Varierity( ID , NAME ) VALUES( 949 , ' Tintilia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 950 , ' Tinto Cao ');
INSERT INTO Varierity( ID , NAME ) VALUES( 951 , ' Tintore di Tramonti ');
INSERT INTO Varierity( ID , NAME ) VALUES( 952 , ' Titan ');
INSERT INTO Varierity( ID , NAME ) VALUES( 953 , ' Tokaji Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 954 , ' Torbato ');
INSERT INTO Varierity( ID , NAME ) VALUES( 955 , ' Torrontes ');
INSERT INTO Varierity( ID , NAME ) VALUES( 956 , ' Touriga Franca ');
INSERT INTO Varierity( ID , NAME ) VALUES( 957 , ' Touriga Franca - Touriga Nacional ');
INSERT INTO Varierity( ID , NAME ) VALUES( 958 , ' Touriga Nacional ');
INSERT INTO Varierity( ID , NAME ) VALUES( 959 , ' Trajadura (Treixadura) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 960 , ' Traminer ');
INSERT INTO Varierity( ID , NAME ) VALUES( 961 , ' Traminette ');
INSERT INTO Varierity( ID , NAME ) VALUES( 962 , ' Trbljan ');
INSERT INTO Varierity( ID , NAME ) VALUES( 963 , ' Trebbiano Spoletino ');
INSERT INTO Varierity( ID , NAME ) VALUES( 964 , ' Trebbiano (Ugni Blanc) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 965 , ' Trepat ');
INSERT INTO Varierity( ID , NAME ) VALUES( 966 , ' Trincadeira das Pratas ');
INSERT INTO Varierity( ID , NAME ) VALUES( 967 , ' Triomphe ');
INSERT INTO Varierity( ID , NAME ) VALUES( 968 , ' Trousseau (Bastardo) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 969 , ' Trousseau Gris ');
INSERT INTO Varierity( ID , NAME ) VALUES( 970 , ' Tsaoussi ');
INSERT INTO Varierity( ID , NAME ) VALUES( 971 , ' Tsitska ');
INSERT INTO Varierity( ID , NAME ) VALUES( 972 , ' Tsolikouri ');
INSERT INTO Varierity( ID , NAME ) VALUES( 973 , ' Turan (Agria) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 974 , ' Umeshu ');
INSERT INTO Varierity( ID , NAME ) VALUES( 975 , ' Usakhelauri ');
INSERT INTO Varierity( ID , NAME ) VALUES( 976 , ' Uva del Fantini ');
INSERT INTO Varierity( ID , NAME ) VALUES( 977 , ' Uva di Troia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 978 , ' Uva Longanesi ');
INSERT INTO Varierity( ID , NAME ) VALUES( 979 , ' Uva Rara ');
INSERT INTO Varierity( ID , NAME ) VALUES( 980 , ' Vaccarese ');
INSERT INTO Varierity( ID , NAME ) VALUES( 981 , ' Valdiguie ');
INSERT INTO Varierity( ID , NAME ) VALUES( 982 , ' Valiant ');
INSERT INTO Varierity( ID , NAME ) VALUES( 983 , ' Valpolicella Blend ');
INSERT INTO Varierity( ID , NAME ) VALUES( 984 , ' Ventura ');
INSERT INTO Varierity( ID , NAME ) VALUES( 985 , ' Verdanel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 986 , ' Verdea ');
INSERT INTO Varierity( ID , NAME ) VALUES( 987 , ' Verdeca ');
INSERT INTO Varierity( ID , NAME ) VALUES( 988 , ' Verdejo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 989 , ' Verdejo - Viura ');
INSERT INTO Varierity( ID , NAME ) VALUES( 990 , ' Verdelet ');
INSERT INTO Varierity( ID , NAME ) VALUES( 991 , ' Verdelho ');
INSERT INTO Varierity( ID , NAME ) VALUES( 992 , ' Verdesse ');
INSERT INTO Varierity( ID , NAME ) VALUES( 993 , ' Verdicchio ');
INSERT INTO Varierity( ID , NAME ) VALUES( 994 , ' Verdil ');
INSERT INTO Varierity( ID , NAME ) VALUES( 995 , ' Verdiso ');
INSERT INTO Varierity( ID , NAME ) VALUES( 996 , ' Verdoncho ');
INSERT INTO Varierity( ID , NAME ) VALUES( 997 , ' Verduzzo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 998 , ' Vermentino Nero ');
INSERT INTO Varierity( ID , NAME ) VALUES( 999 , ' Vermentino (Rolle) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1000 , ' Vermouth ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1001 , ' Vernaccia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1002 , ' Vernaccia Nera ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1003 , ' Vertzami ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1004 , ' Vespaiolo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1005 , ' Vespolina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1006 , ' Vidadillo (Crespiello) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1007 , ' Vidal ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1008 , ' Vidiano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1009 , ' Vien de Nus ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1010 , ' Vijariego Blanco ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1011 , ' Vijariego Negro ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1012 , ' Vilana ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1013 , ' Villard Blanc ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1014 , ' Vin de Liqueur ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1015 , ' Vinhao (Sousao) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1016 , ' Viognier ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1017 , ' Viosinho ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1018 , ' Vital ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1019 , ' Vitovska ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1020 , ' Vodka ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1021 , ' Vodka - Flavored ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1022 , ' Volitsa (Volidza) ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1023 , ' Voudomato ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1024 , ' Vradiano ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1025 , ' Vranac ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1026 , ' Vugava ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1027 , ' Vuillermin ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1028 , ' Welschriesling ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1029 , ' Whiskey - America ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1030 , ' Whiskey Bourbon ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1031 , ' Whiskey Corn ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1032 , ' Whiskey - Irish ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1033 , ' Whiskey - Liqueur - Flavored ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1034 , ' Whiskey - Rye ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1035 , ' Whiskey - Wheat ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1036 , ' Whisky - Australia ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1037 , ' Whisky - Canada ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1038 , ' Whisky - India ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1039 , ' Whisky - Japan ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1040 , ' Whisky - Whiskey Blended ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1041 , ' Whisky - Whiskey Grain ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1042 , ' Whisky - Whiskey Malt ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1043 , ' Wurzer ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1044 , ' Xarel-lo ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1045 , ' Xinomavro ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1046 , ' Xynisteri ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1047 , ' Zalema ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1048 , ' Zefir ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1049 , ' Zelen ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1050 , ' Zenit ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1051 , ' Zeta ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1052 , ' Zeus ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1053 , ' Zierfandler ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1054 , ' Zilavka ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1055 , ' Zinfandel ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1056 , ' Zlahtina ');
INSERT INTO Varierity( ID , NAME ) VALUES( 1057 , ' Zweigelt ');
