INSERT INTO Volumes(name, volume) VALUES("Split or Piccolo", 00.188);
INSERT INTO Volumes(name, volume) VALUES("Half or Demi", 00.375);
INSERT INTO Volumes(name, volume) VALUES("Half-liter or Jennie", 00.500);
INSERT INTO Volumes(name, volume) VALUES("Standard", 00.750);
INSERT INTO Volumes(name, volume) VALUES("Liter", 01.000);
INSERT INTO Volumes(name, volume) VALUES("Magnum", 01.500);
INSERT INTO Volumes(name, volume) VALUES("Jeroboam or Double Magnum", 03.000);
INSERT INTO Volumes(name, volume) VALUES("Rehoboam (Jeroboam in Bordeaux)", 04.500);
INSERT INTO Volumes(name, volume) VALUES("Methuselah or Imperial (Bordeaux)", 06.000);
INSERT INTO Volumes(name, volume) VALUES("Salmanazar", 09.000);
INSERT INTO Volumes(name, volume) VALUES("Balthazar", 12.000);
INSERT INTO Volumes(name, volume) VALUES("Nebuchadnezzar", 15.000);
INSERT INTO Volumes(name, volume) VALUES("Melchior", 18.000);
INSERT INTO Volumes(name, volume) VALUES("Solomon", 20.000);
INSERT INTO Volumes(name, volume) VALUES("Sovereign", 26.000);
INSERT INTO Volumes(name, volume) VALUES("Primat or Goliath", 27.000);
INSERT INTO Volumes(name, volume) VALUES("Melchizedek or Midas", 30.000);
