INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 1 , ' Split or Piccolo ', 00.188 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 2 , ' Half or Demi ', 00.375 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 3 , ' Half-liter or Jennie ', 00.500 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 4 , ' Standard ', 00.750 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 5 , ' Liter ', 01.000 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 6 , ' Magnum ', 01.500 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 7 , ' Jeroboam or Double Magnum ', 03.000 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 8 , ' Rehoboam (Jeroboam in Bordeaux) ', 04.500 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 9 , ' Methuselah or Imperial (Bordeaux) ', 06.000 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 10 , ' Salmanazar ', 09.000 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 11 , ' Balthazar ', 12.000 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 12 , ' Nebuchadnezzar ', 15.000 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 13 , ' Melchior ', 18.000 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 14 , ' Solomon ', 20.000 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 15 , ' Sovereign ', 26.000 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 16 , ' Primat or Goliath ', 27.000 );
INSERT INTO Volumes( ID , NAME , VOLUME ) VALUES( 17 , ' Melchizedek or Midas ', 30.000 );
