INSERT INTO Wine(name, description, id_taste, id_variety, id_style) VALUES("First", "Some", 1, 123, 1);
INSERT INTO Wine(name, description, id_taste, id_variety, id_style) VALUES("Second", "Description", 1, 111, 2);
INSERT INTO Wine(name, description, id_taste, id_variety, id_style) VALUES("Third", "", 4, 2, 3);
INSERT INTO Wine(name, description, id_taste, id_variety, id_style) VALUES("Fourth", "", 1, 23, 4);
INSERT INTO Wine(name, description, id_taste, id_variety, id_style) VALUES("Fifth", "Not", 3, 45, 5);
INSERT INTO Wine(name, description, id_taste, id_variety, id_style) VALUES("Sixth", "Important", 2, 88, 6);
INSERT INTO Wine(name, description, id_taste, id_variety, id_style) VALUES("Seventh", "", 2, 64, 7);
INSERT INTO Wine(name, description, id_taste, id_variety, id_style) VALUES("Eighth", "Not enough time", 4, 604, 8);
INSERT INTO Wine(name, description, id_taste, id_variety, id_style) VALUES("Ninth", "", 3, 888, 9);
INSERT INTO Wine(name, description, id_taste, id_variety, id_style) VALUES("Tenth", "", 2, 1000, 10);
