INSERT INTO Wine(id, name, description, id_taste, id_variety, id_style) VALUES(1, "First", "Some", 1, 123, 1);
INSERT INTO Wine(id, name, description, id_taste, id_variety, id_style) VALUES(2, "Second", "Description", 1, 111, 2);
INSERT INTO Wine(id, name, description, id_taste, id_variety, id_style) VALUES(3, "Third", "", 4, 2, 3);
INSERT INTO Wine(id, name, description, id_taste, id_variety, id_style) VALUES(4, "Fourth", "", 1, 23, 4);
INSERT INTO Wine(id, name, description, id_taste, id_variety, id_style) VALUES(5, "Fifth", "Not", 3, 45, 5);
INSERT INTO Wine(id, name, description, id_taste, id_variety, id_style) VALUES(6, "Sixth", "Important", 2, 88, 6);
INSERT INTO Wine(id, name, description, id_taste, id_variety, id_style) VALUES(7, "Seventh", "", 2, 64, 7);
INSERT INTO Wine(id, name, description, id_taste, id_variety, id_style) VALUES(8, "Eighth", "Not enough time", 4, 604, 8);
INSERT INTO Wine(id, name, description, id_taste, id_variety, id_style) VALUES(9, "Ninth", "", 3, 888, 9);
INSERT INTO Wine(id, name, description, id_taste, id_variety, id_style) VALUES(10, "Tenth", "", 2, 1000, 10);
